package com.ftkj.util.charset;

import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.TreeMap;

/**
 * @author Marc.Wang 2011-10-31 下午07:33:14
 * 功能：德语版
 */
public class DE {
	private static Map<Integer,String> key = new HashMap<Integer,String>();

	public static Map<Integer,String> getMap(){
		return key;
	}
	static{
		/**
		key.put(Keys.创建联盟, "Liga erstellen");
		key.put(Keys.学习战术, "Taktik lernen„{1}“");
		key.put(Keys.注册球队, "Mannschaft registrieren");
		key.put(Keys.领取球员, "Spieler abholen");
		key.put(Keys.提升工资帽, "Höchstlohn erhöhen");

		key.put(Keys.提升联盟服务星级, "„{1}“ Die Liga wird von Stufe {2} auf Stufe {3} erhöht");
		key.put(Keys.联盟创建, "Liga entsteht");
		key.put(Keys.提升联盟星级, "„{1}“ Die Liga wird auf Stufe{2} erhöht");
		key.put(Keys.加入联盟, "neue Mitglied „{1}“ in die Liga");
		key.put(Keys.退出联盟, "„{1}“ verlasst die Liga");
		key.put(Keys.被逐出联盟, "„{1}“ wird von der Liga entfernt");
		key.put(Keys.接任盟主, "„{1}“ wird der neue Chef der Liga");
		key.put(Keys.任命理事, "„{1}“ wird als Senator ernannt");
		key.put(Keys.任命副盟主, "„{1}“ wird als Vize-chef ernannt");
		key.put(Keys.捐献经费, "„{1}“ hat {2} Finanzierung beitragen, Finanzierung der Liga erhöht sich um {2}");
		key.put(Keys.答题奖励, "Belohnung des Quiz");
		key.put(Keys.系统, "System");
		key.put(Keys.升级, "Upgrade");

		key.put(Keys.盟战挑战成功返还系统托管经费, "Sie haben den Wettkampf von Ligen schon gewinnen. Die von System verwaltete Finanzierung {1} wird rückerstattet");
		key.put(Keys.盟战挑战成功掠夺联盟经费,"Sie haben den Wettkampf von Ligen schon gewinnen. Sie werden Finanzierung {1} von Gegner bekommen");
		key.put(Keys.盟战防御失败被掠夺联盟经费,"Sie haben den Wettkampf verloren. Ihre Finanzierung {1} wird von gegner besitzt");
		key.put(Keys.盟战挑战成功掠夺联盟建设度,"Sie haben Ihre Gegner besiegt, erhalten Sie ein {1} Baustufe");
		key.put(Keys.盟战防御失败被掠夺联盟建设度,"Sie haben den Wettkampf verloren. Verlieren Sie ein {1} Baustufe");
		key.put(Keys.盟战挑战失败不返还系统托管经费,"Sie haben den Wettkampf von Ligen verloren, die von System verwaltete Finanzierung {1} wird nicht rückerstattet");
		key.put(Keys.发起联盟挑战扣联盟经费, "Sie haben den Wettkampf hervorgeruft, Finanzierung {1} von Ihrer Liga wird abgezogen");
		key.put(Keys.系统托管可能挑战失败的惩罚扣联盟经费, "Mit System Verwaltung wird {1} Kredit abgezogen");

		key.put(Keys.捐献联盟资金, "Zu Liga beitragen");
		key.put(Keys.任务奖励, "Belohnung der Aufgabe");
		key.put(Keys.奢侈税, "Luxussteuer");
		key.put(Keys.交易, "handel mit „{1}“");
		key.put(Keys.系统解聘球员, "Spieler {1} wird von System gefeuert,{2}W");
		key.put(Keys.自由买卖区交易球员, "Spieler{1} wird gehandelt in Frei-Handel-Zone");
		key.put(Keys.选秀球员, "Draft-Spieler {1}");
		key.put(Keys.竞价球员, "Spieler-Angebot {1}");

		key.put(Keys.新手引导奖励, "Belohnung von Neue");
		key.put(Keys.新手引导签约球员奖励, "Belohnung von Aufgabe „Unterzeichnen mit einem Spieler“");
		key.put(Keys.新手引导回答问题奖励, "Belohnung von Aufgabe „Quiz machen“");

		key.put(Keys.未指定, "umbestimmt");
		key.put(Keys.回收道具, "Rückruf von Stütze„{1}“{2}");
		key.put(Keys.购买道具, "Kaufen die Stütze „{1}“{2}");
		key.put(Keys.使用道具, "Benutzen die Stütze „{1}“");
		key.put(Keys.学习天赋, "Talent lernen„{1}“");
		key.put(Keys.解聘球员, "Spieler feuern {1},{2}W");
		key.put(Keys.签约球员, "Mit einem Spieler unterzeichnen {1}");

		key.put(Keys.得分王,"scoring leader");
		key.put(Keys.篮板王,"Rebound Leader");
		key.put(Keys.助攻王,"Assist Leader");
		key.put(Keys.MVP, "MVP");
		key.put(Keys.比赛, "Wettkampf");
		key.put(Keys.杯赛报名费, "Anmeldekosten");
		key.put(Keys.退还杯赛报名费, "Rückerstattung von Anmeldekosten");
		key.put(Keys.丢弃装备, " Verlassen{1}„{2}“");
		key.put(Keys.强化装备等级, "Stufe von Ausrüstung verstärken");
		key.put(Keys.团体赛报名费, "Anmelden von Multi-Spieler Wettkampf");
		key.put(Keys.退还团体赛报名费, "Rückerstattung von Anmeldekosten der Multi-Spieler Wettkampf");
		key.put(Keys.正在比赛, "Im Spiel");
		key.put(Keys.工资超帽, "Gesamtlohn ist jetzt über den Höchstlohn");
		key.put(Keys.总工资低于4000万, "Gesamtlohn ist niederiger als 4000");
		key.put(Keys.团体赛奖励, "Belohnung von Multi-Spieler Wettkampf");
		key.put(Keys.购买装备, "Kaufen {2}„{1}“");
		key.put(Keys.在线奖励, "Online Belohnung");
		key.put(Keys.健康球员不足7人, "Gesunde Spieler ist unter 7");
		key.put(Keys.参加NBA联赛, "an die NBA-Spiel teilnehmen");
		key.put(Keys.转移装备, "Ausrüstung-Transfer");
		key.put(Keys.梦幻组合训练, "Trainieren von The Dream Team");
		key.put(Keys.完成梦幻组合训练, "Das Trainieren von The Dream Team ist fertig");
		key.put(Keys.橙色装备转移, "Transfer der orangen Ausrüstung");
		key.put(Keys.道具奖励, "Belohnung der Stürze");
		key.put(Keys.万经费, "Kredit");
		key.put(Keys.声望, "Ruf");
		key.put(Keys.球馆争霸赛奖励,"Belohnung des Wettkampf zwischen Stadin");
		key.put(Keys.助威扣费, "Hochruf");
		key.put(Keys.补充体力扣球券, "Kraft verfüllen mit Abzog von Geld");
		key.put(Keys.装备合成, "装备合成");
		key.put(Keys.比赛奖励, "比赛奖励");
		key.put(Keys.梦幻征程赠送, "梦幻征程赠送");
		key.put(Keys.新手引导赠送, "新手引导赠送");
		key.put(Keys.道具获得, "道具获得");
		key.put(Keys.勋章兑换装备, "勋章兑换装备“{1}”{2}个");
		key.put(Keys.合成装备, "合成{1}个“{2}”装备");
		key.put(Keys.积分购买装备, "{1}积分购买装备“{2}”{3}个");
		key.put(Keys.经费购买装备, "经费购买装备“{1}”{2}个");
		key.put(Keys.装备分解, "分解“{1}”装备");

		key.put(Keys.强攻内线,"Angriff der Innen");
		key.put(Keys.外线投篮,"Korbschuss außen dreierlinie");
		key.put(Keys.老鹰进攻,"Eagle Angriff");
		key.put(Keys.三角进攻战术,"Dreiecke Angriff");
		key.put(Keys.挡拆进攻,"stoßen Angriff");
		key.put(Keys.内线策应,"Innen Assist");
		key.put(Keys.跑轰战术,"Laufen und schießen");
		key.put(Keys.普林斯顿战术,"Princeton Taktik");
		key.put(Keys.盯人内线,"Personverteigigung innen Dreierlinie");
		key.put(Keys.盯人外线,"Personverteigigung außen Dreierlinie");
		key.put(Keys.M2_3联防,"2-3 Zoneverteidigung");
		key.put(Keys.M2_1_2联防,"2-1-2 Zoneverteidigung");
		key.put(Keys.M3_2联防,"3-2 Zoneverteidigung");
		key.put(Keys.M1_3_1联防,"1-3-1 Zoneverteidigung");
		key.put(Keys.混合防守,"Mischformen Verteidigung");
		key.put(Keys.全场紧逼,"1 gegen 1 Verteigigung");

		key.put(Keys.联盟服务_行政中心, "administrative Zentrum");
		key.put(Keys.联盟服务_酒店, "Hotel");
		key.put(Keys.联盟服务_训练场, "Training Zentrum");
		key.put(Keys.联盟服务_摩天大厦, "Wolkenkratzer");
		key.put(Keys.联盟服务_装备中心, "Ausrüstungszentrum");
		key.put(Keys.联盟服务_战术中心, "Taktik Zentrum");
		key.put(Keys.联盟等级_一,"1");
		key.put(Keys.联盟等级_二,"2");
		key.put(Keys.联盟等级_三,"3");
		key.put(Keys.联盟等级_四,"4");
		key.put(Keys.联盟等级_五,"5");

		key.put(Keys.提示_在自由买卖区交易成功, "Ihrer Spieler {1} ist in den Frei-Handel-Zone erfolglich gehandelt");
		key.put(Keys.提示_所有场上球员打气, "{1} ermuntert alle Spieler von {2}, dessen Kraft wird sich um {3} erholen.");
		key.put(Keys.提示_朝对手咆哮, "{1} knurrt an alle Spieler von gegner {2}, dessen Kraft wird sich um {3} reduzieren.");
		key.put(Keys.提示_知己知彼, "Gegenwärtige Taktik von Gegner, Angriff {1}  Verteiging {2}.");
		key.put(Keys.提示_道具使用失败被对方的机敏天赋干扰,"Ihrer Requist{1} wirkt nicht,ist von Talent Findig gestört");
		key.put(Keys.提示_咆哮, "{1} benutzt {2},Kraft von {4} aus {3} um {5} reduziert.");
		key.put(Keys.提示_嘘声,"{1} benutzt {2},Kraft von allen Spielern aus {3} um {4} reduziert.");
		key.put(Keys.提示_喝彩,"{1} benutzt {2},Kraft von allen Spielern aus {1} um {3} erhöht,Kraft von allen Spielern aus {4} um {5} reduziert.");
		key.put(Keys.提示_一个球员体力恢复, "{1} benutzt {2},Kraft von {3} aus {1} um {4} erhöht.");
		key.put(Keys.提示_全部球员体力恢复, "{1} benutzt {2},Kraft von allen Spielern aus {1} um {3} erhöht.");
		key.put(Keys.提示_繁忙状态无法比赛, "Entschudigung, Manager. Wegen {1} ist das geplante um {2} beginnende Spiel {3} abgesagt,{4}.");
		key.put(Keys.提示_人数不满无法比赛, "Entschudigung, Manager. Denn die angemeldete Spieler haben die vorschreibende Zahl nicht erreichen, wird das geplante um {1} beginnende Spiel {2} abgesagt.");
		key.put(Keys.提示_退还报名费, ", Die Anmeldungskosten ist auch schon auf Ihr Konto übergewiesen");
		key.put(Keys.提示_有玩家坐桌子通知房主进入, "„{1}“hat in das von Ihr erstellte Handelzimmer eintreten");
		key.put(Keys.提示_直接晋级,"Wegen {1} von Ihrem Gegner werden Sie das Spiel mit 20:0 gewinnen");
		key.put(Keys.提示_直接淘汰,"Wegen {1} von Ihrer Gegner Mannschaft, werden Sie das Spiel mit 0:20 verlieren");
		key.put(Keys.提示_球员被偷, "您的球员{1}被您的好友{2}签约。");
		key.put(Keys.提示_战术升级, "恭喜您“{1}”升级到“{2}”！");
		key.put(Keys.战术_等级,"A;入门;初级;中级;高级;特级;专家级");

		key.put(Keys.联盟提示_加入联盟,"„{1}“hat die Liga anschließen");
		key.put(Keys.联盟提示_捐献经费,"„{1}“hat {2} Finanzierung zu Liga beigetragen");
		key.put(Keys.联盟提示_修改联盟公告,"Ankündigung:{1}");
		key.put(Keys.联盟提示_逐出联盟,"„{1}“wird aus der Liga rausgeworfen");
		key.put(Keys.联盟提示_挑战成功,"【Liga-Liga】Sie haben Wettkampf zwischen Liga gewinnen，haben {2} Baustufe,{3} Finanzierung von [{1}] geplündert");
		key.put(Keys.联盟提示_防守失败,"【Liga-Liga】Sie haben Wettkampf zwischen Liga verlieren，{2} Baustufe,{3} Finanzierung wird von [{1}] geplündert");
		key.put(Keys.联盟提示_挑战失败,"【Liga-Liga】Sie haben Wettkampf zwischen Liga verlieren，{1} Finanzierung wird abgezogen");
		key.put(Keys.联盟提示_防守成功,"【Liga-Liga】Sie haben die Kampfansage von [{1}]gewinnen");
		key.put(Keys.联盟提示_行政中心," Verwaltungszentrum von Liga hat {1} Stern erreichen.Die Liga kann 25 Mehr Spieler als Mitgelieder annehmen.");
		key.put(Keys.联盟提示_酒店,"Restaurant von Liga hat {1} Stern erreichen.Die Liga kann 25 Mehr Spieler als Mitgelieder annehmen.");
		key.put(Keys.联盟提示_训练场,"Trainingsplatz von Liga hat {1} Stern erreichen. Merkmal von allen Spielern aus dieser Liga wird um 2% erhöhen.");
		key.put(Keys.联盟提示_摩天大厦,"Wolkenkratzer von Liga hat {1} Stern erreichen. Höchstlohn von allen Spielern aus dieser Liga wird um 100 erhöhen.");
		key.put(Keys.联盟提示_装备中心,"Ausrüstungszentrum von Liga hat {1} Stern erreichen. Erfolgsquote zur Verstärkung wird um 2% erhöhen.");
		key.put(Keys.联盟提示_战术中心,"Taktikszentrum von Liga hat {1} Stern erreichen. Geschicktheit von Taktik wird um 2% erhöhen.");
		key.put(Keys.联盟提示_申请加入联盟, "“{1}”申请加入联盟");

		key.put(Keys.防守, "Verteidigung");
		key.put(Keys.进攻, "Angriff");

		key.put(Keys.道具日报_玩家使用,"man benutzt es");
		key.put(Keys.道具日报_系统奖励,"Belohnung");
		key.put(Keys.道具日报_使用礼包,"Sie haben “{1}” eröffnet");
		key.put(Keys.道具日报_购买,"Kaufen");
		key.put(Keys.道具日报_积分兑换, "{1}积分兑换道具“{2}”{3}个");
		key.put(Keys.球队日报_清洗天赋, "清洗天赋");
		key.put(Keys.球队日报_幸运答题活动, "幸运答题活动");

		key.put(Keys.球员日报_球探签约 ,"unterzeichnen durch Scount");
		key.put(Keys.球员日报_选秀签约,"unterzeichen in Draft-Halle");
		key.put(Keys.球员日报_创建球队,"Mannschaft gründen");
		key.put(Keys.球员日报_交易,"Handeln mit “{1}”");
		key.put(Keys.球员日报_自由买卖区购买,"handeln in der Frei-Handel-Zone");
		key.put(Keys.球员日报_多人对战赛奖励,"Belohnung für Multi-Spieler ");
		key.put(Keys.球员日报_杯赛系统奖励,"Belohnung für Dream Cup");
		key.put(Keys.球员日报_使用道具,"man benutzt requiste");
		key.put(Keys.球员日报_其它 ,"andere");
		key.put(Keys.球员日报_自行解雇,"Sie haben den Spieler gefeuert");
		key.put(Keys.球员日报_系统解雇 ,"von System gefeuert");
		key.put(Keys.球员日报_自由买卖区出售,"verkaufen in der Frei-Handel-Zone");
		key.put(Keys.球员日报_竞价获取球员,"Durch Angebot neuen Spieler bekommen");
		key.put(Keys.球员日报_节日送祝福,"fröhliche Weichnachten");
		key.put(Keys.球员日报_名人堂奖励,"名人堂奖励");
		key.put(Keys.装备日报_竞技宝箱奖励,"竞技宝箱奖励");
		key.put(Keys.球队日报_提交申请书,"提交申请书");
		key.put(Keys.球队日报_竞猜奖励,"竞猜奖励");
		key.put(Keys.球队日报_付费挑战迷宫,"挑战迷宫");
		key.put(Keys.球队日报_完成教练训练,"教练训练");
		key.put(Keys.球队日报_劳资协议降低工资, "使用劳资协议书，工资从{1}变成{2}万");
		key.put(Keys.球队日报_装备分解, "装备分解");
		key.put(Keys.球队日报_充值奖励,"充值奖励");
		key.put(Keys.道具日报_天梯赛奖励,"天梯赛奖励");
		key.put(Keys.球队日报_邀请好友奖励,"好友{1}达到{2}级，领取奖励");
		key.put(Keys.球队日报_端午奖励,"端午节奖励");
		key.put(Keys.球队日报_活动奖励, "活动奖励");
		key.put(Keys.球队日报_vip打折卡,"Vip返绑定球券");

		key.put(Keys.装备属性_抢断, "（抢断）");
		key.put(Keys.装备属性_助攻, "（助攻）");
		key.put(Keys.装备属性_得分, "（得分）");
		key.put(Keys.装备属性_篮板, "（篮板）");
		key.put(Keys.装备属性_盖帽, "（盖帽）");

		key.put(Keys.天赋技能_千手观音, "千手观音");
		key.put(Keys.天赋技能_乌云盖顶, "乌云盖顶");
		key.put(Keys.天赋技能_神来之笔, "神来之笔");
		key.put(Keys.天赋技能_拔地而起, "拔地而起");
		key.put(Keys.天赋技能_知己知彼, "知己知彼");
		key.put(Keys.天赋技能_阵容调整, "阵容调整");
		key.put(Keys.天赋技能_精准, "精准");
		key.put(Keys.天赋技能_机敏, "机敏");
		key.put(Keys.天赋技能_以逸待劳, "以逸待劳");
		key.put(Keys.天赋技能_士气大振, "士气大振");
		key.put(Keys.天赋技能_体力充盈, "体力充盈");
		key.put(Keys.天赋技能_变幻莫测, "变幻莫测");
		key.put(Keys.天赋技能_抛砖引玉, "抛砖引玉");
		key.put(Keys.天赋技能_怒吼, "怒吼");
		key.put(Keys.天赋技能_终极绝杀, "终极绝杀");
		key.put(Keys.天赋技能_畅聊, "畅聊");
		key.put(Keys.天赋技能_成竹在胸, "成竹在胸");
		key.put(Keys.天赋技能_激励, "激励");
		key.put(Keys.天赋技能_睿智, "睿智");
		key.put(Keys.天赋技能_薄利多销, "薄利多销");
		key.put(Keys.天赋技能_战术大师, "战术大师");
		key.put(Keys.天赋技能_地位尊崇, "地位尊崇");
		key.put(Keys.天赋技能_慕名而来, "慕名而来");
		key.put(Keys.天赋技能_好运, "好运");
		key.put(Keys.天赋技能_最佳教练, "最佳教练");
		key.put(Keys.天赋技能_嘉奖, "嘉奖");
		key.put(Keys.天赋技能_人品爆发, "人品爆发");
		key.put(Keys.天赋技能_鼓舞, "鼓舞");
		key.put(Keys.天赋技能_极品球探, "极品球探");
		key.put(Keys.天赋技能_梦之队, "梦之队");
		key.put(Keys.天赋技能_新的形象, "新的形象");
		key.put(Keys.天赋技能_激情球探, "激情球探");
		key.put(Keys.天赋技能_亲友团, "亲友团");
		key.put(Keys.天赋技能_神秘球员, "神秘球员");
		key.put(Keys.天赋技能_反客为主, "反客为主");
		key.put(Keys.天赋技能_自由买卖, "自由买卖");
		key.put(Keys.天赋技能_伤病无忧, "伤病无忧");
		key.put(Keys.天赋技能_顶级球员, "顶级球员");
		key.put(Keys.天赋技能_完美搭档, "完美搭档");
		key.put(Keys.天赋技能_生龙活虎, "生龙活虎");
		key.put(Keys.天赋技能_常胜将军, "常胜将军");
		key.put(Keys.天赋技能_选秀无限, "选秀无限");
		key.put(Keys.天赋技能_超帽, "超帽");
		key.put(Keys.天赋技能_奢侈不收税, "奢侈不收税");
		key.put(Keys.天赋技能_超级底薪, "超级底薪");

		key.put(Keys.提示_啦啦队热舞,"Erfolgreich benutzt. ErhöhlungsTempo von Spieler wird 5 Punkte/halbe Stunde höher");
		key.put(Keys.提示_经费兑换券,"Erfolgreich benutzt. Sie haben 100 Kredit bekommen");
		key.put(Keys.提示_高级经费兑换券,"Erfolgreich benutzt. Sie haben 1000 Kredit bekommen");
		key.put(Keys.提示_高级双倍声望卡,"Erfolgreich benutzt. Innerhalb 7 Tage werden die Ruf-belohnung verdoppelt");
		key.put(Keys.提示_双倍声望卡,"Erfolgreich benutzt.Erfolgreich benutzt. Innerhalb 1 Tag werden die Ruf-belohnung verdoppelt");
		key.put(Keys.提示_激情板凳卡,"Erfolgreich benutzt.ErhöhlungsTempo von Bench-Spieler wird in 3 Tage um 15% erhöht");
		key.put(Keys.提示_超值大礼包,  "Sie haben eine hochwertige Kredit-Welchselx1, Minimum-Lohn Star Kartex1,Sportgetränke(groß)x5, Draft-Kartex5 bekommen");
		key.put(Keys.提示_facebook礼包,"您获得了球探召回卡x1、运动饮料小x2、运动饮料中x2、经费兑换券x1");
		key.put(Keys.提示_充值大礼包, "Sie haben Rückruf-karte der Kundeschafterx1, 3-Stufe-Verstärkungsstern x1, Knurrenx1, Energy-Drink(mittel)x1 bekommen");
		key.put(Keys.提示_5级新手礼包, "Sie haben Knurrenx1,Hochrufx1,Rückruf-karte der Kundeschafterx2, Sportgetränke(klein)x2,10-Stufe Belohnungenx1 bekommen");
		key.put(Keys.提示_10级新手礼包,"Sie haben Apfelsaft(groß)x5, Lautsprecherx3, Mineralwasser(mittel)x5,20-Stufe Belohnungenx1,Kleid aus Mischgewebex1, elastische Kniehutx1 bekommen");
		key.put(Keys.提示_20级新手礼包,"Sie haben Verdoppelte-Ruf-Kartex2, NBA-Herausforderung Kartex2, Sportgetränke(mittel)x2, Kleid aus Kohlefaserx1, Kniehut aus Kohlefaserx1 bekommen");
		key.put(Keys.提示_补偿礼包A,"Sie haben Rückruf-Karte der Kundeschafterx1, Sportgetränke(klein)x1, Knurrenx1 bekommen");
		key.put(Keys.提示_补偿礼包B,"Sie haben NBA-Herausforderung Kartex1, Sportgetränke(mittel)x1, Knurrenx1 bekommen");
		key.put(Keys.提示_补偿礼包C,"Sie haben Verdoppelte-Ruf-Kartex2, Sportgetränke(groß)x1, Knurrenx1 bekommen");
		key.put(Keys.提示_补偿礼包D,"Sie haben Minimum-Lohn Reservist Kartex1 bekommen");
		key.put(Keys.提示_补偿礼包E,"您获得了{1}、双倍声望卡x1、运动饮料（大）x1、幸运符x1、嘘声x1");
		key.put(Keys.提示_电玩大礼包,"Sie haben Rückruf von Scountsx1,Sportgetränke(klein)x2, Sportgetränke(mittel)x2,Kredit Kartex1 erhalten.");
		key.put(Keys.提示_新春礼包,"您获得了咆哮x1、运动饮料小x1、选秀卡x1、洞悉敌情x1、球探召回卡x2。");
		key.put(Keys.提示_新春大礼包,"您获得了底薪替补卡x1、喝彩x1、选秀卡x1、运动饮料中x2、洞悉敌情x2。");
		key.put(Keys.提示_新春超级礼包,"您获得了5级强化石x3、4级强化石x3、超级巨星卡x1、幸运符x2、神佑符x2、洞悉敌情x6、运动饮料大x3、劳资协议书x4。");
		key.put(Keys.提示_节日粽子,"情人节快乐！使用成功，您获得了{1}。");
		key.put(Keys.提示_梦之队祝福,"劳动节快乐！恭喜您获得了{1}。");
		key.put(Keys.提示_劳资协议书,"Nach einer intensiver Lohn-Verhandlung, stimmen Sie endlich mit{2} von {1} ein");
		key.put(Keys.提示_底薪替补卡,"Erfolgreich benutzt. Sie haben {1} bekommen");
		key.put(Keys.提示_底薪替补卡赠,"Erfolgreich benutzt. Sie haben {1} bekommen");
		key.put(Keys.提示_球星卡,	"Erfolgreich benutzt. Sie haben {1} bekommen");
		key.put(Keys.提示_超级巨星卡,"Erfolgreich benutzt. Sie haben {1} bekommen");
		key.put(Keys.提示_底薪球星卡,"Erfolgreich benutzt. Sie haben {1} bekommen");
		key.put(Keys.提示_传奇巨星随机卡,"Erfolgreich benutzt, Die super Star in Ihrer Mannschaft ist jetzt {1}");
		key.put(Keys.提示_传奇巨星更换卡,"Erfolgreich benutzt, Die super Star in Ihrer Mannschaft ist jetzt {1}");
		key.put(Keys.提示_助威小礼包,"Erfolgreich benutzt. Sie haben {1} bekommen");
		key.put(Keys.提示_声望卷,"Erfolgreich benutzt. Sie haben {1} bekommen");
		key.put(Keys.提示_禁言协管员, "Wegen Unangebrachte Wörter, Ihre Rede wird innerhalb 60 Minuten in Welt, Handel channel Verboten.");
		key.put(Keys.提示_禁言管理員, "Wegen Unangebrachte Wörter, Ihre Rede wird innerhalb 180 Minuten in Welt, Handel,Liga, Lautsprecher channel Verboten.");
		key.put(Keys.提示_禁言广播协管员, "<font color='#ff0000'>【System】</font>[{1}]Wegen Unangebrachte Wörter, Ihre Rede wird innerhalb 60 Minuten in Welt, Handel channel Verboten");
		key.put(Keys.提示_禁言广播管理員, "<font color='#ff0000'>【System】</font>[{1}]Wegen Unangebrachte Wörter, Ihre Rede wird innerhalb 180 Minuten in Welt, Handel,Liga channel Verboten");
		key.put(Keys.提示_盟战发出挑战, "<font color='#ff0000'>【Liga-Liga】</font>[{1}]montiert eine Herausforderung an [{2}]");
		key.put(Keys.提示_盟战防守成功, "<font color='#ff0000'>【Liga-Liga】</font>[{1}] haben in der Verteidigung [{2}] besiegt");
		key.put(Keys.提示_盟战挑战成功, "<font color='#ff0000'>【Liga-Liga】</font>[{1}] haben in der Herausforderung [{2}] besiegt");
		key.put(Keys.提示_获得联盟英雄称号, "Kongratuliere, Sie haben die Auszeichnung[Held der Liga] erhlaten");
		key.put(Keys.提示_强化装备世界广播, "<font color='#ff0000'>【System】</font>Ausrüstung[{2}] von [{1}] ist auf Stufe {3} verstärkt");
		key.put(Keys.提示_强化装备9级世界广播, "“{1}”的装备[{2}]强化到了9级！九九归一，望施主早日修成正果！");
		key.put(Keys.提示_强化装备10级世界广播, "“{1}”的装备[{2}]强化到了10级！十全十美？还差一步之遥！");
		key.put(Keys.提示_强化装备11级世界广播, "“{1}”的装备[{2}]强化到了11级！天啊，11,12，傻傻分不清楚！");
		key.put(Keys.提示_强化装备12级世界广播, "“{1}”的装备[{2}]强化到了12级！有如此神器，夫复何求！");
		key.put(Keys.提示_赠送巧克力, "您赠送{1}个巧克力给{2}");
		key.put(Keys.提示_被赠送巧克力, "{1}赠送您{2}个巧克力");
		key.put(Keys.提示_创建联盟, "<font color='#ff0000'>【System】</font>[{1}] haben Liga[{2}] gegründet");
		key.put(Keys.提示_杯赛预选赛, "<font color='#ff0000'>【System】</font>The Dream Team Cup startet schon. Wenn Sie an sie teilnehmen will, bitte anmelden Sie sich schnell.");
		key.put(Keys.提示_争霸赛系统退出, "Manager, weil die Gesamtlohn von Ihrer Mannschaft über Höchstlohn order die gesunden Spieler unten 7 ist, Sie können an den Wettkampf zwischen Stadion nicht teilnehmen. Bitte lösen Sie die Probleme, und wieder an den Wettkampf teilnehmen.");
		key.put(Keys.提示_竞价活动开始, "<font color='#ff0000'>【System】</font>Spieler-Kaufangebot beginnt schon. Komm schnell und gewinn an Top-Spieler mit niedriegste Lohn.");
		key.put(Keys.提示_竞价活动结束, "<font color='#ff0000'>【System】</font>Spieler-Kaufangebot endet schon. Wenn Sie die Angebot schon gewonnen haben, Laufen schnell, und unterzeichnen mit dem Spieler.");
		key.put(Keys.提示_名人堂抽奖奖品, "恭喜您获得了{1}");
		key.put(Keys.提示_名人堂比赛失败, "經理，很遺憾，由於<font color='#ff0000'>{1}</font>以<font color='#ff0000'>{2}</font>輸給了名人堂元老隊，因此您的隊伍沒有通過考驗，請做好準備，下次繼續挑戰。");
		key.put(Keys.提示_名人堂房主踢人, "您已被踢出隊伍！");
		key.put(Keys.提示_名人堂房主解散队伍, "您所在隊伍已解散！");
		key.put(Keys.提示_强化大礼包, "您获得了3级强化石*10、4级强化石*10、5级强化石*20、幸运符*10 。");
		key.put(Keys.提示_恢复大礼包, "您获得了运动饮料（小）*10、运动饮料（中）*10、功能饮料（中）*10 。");
		key.put(Keys.提示_比赛大礼包, "您获得了咆哮*5、嘘声*5、洞悉敌情*5、运动饮料（小）*5、运动饮料（中）*5 。");
		key.put(Keys.提示_名人堂比赛判负, "由于您在与名人堂元老队的挑战中被0:20判负，因此您无法获得奖励，本次挑战不计算比赛次数。");
		key.put(Keys.提示_豪华礼包, "使用成功，你获得了球员竞价券*1、喝彩*1、嘘声*1、球探召回卡*2 。");
		key.put(Keys.提示_大豪华礼包, "使用成功，你获得了底薪替补卡*1、喝彩*1、选秀卡*1、咆哮*1、洞悉敌情*1。");
		key.put(Keys.提示_超级豪华礼包, "使用成功，你获得了超级巨星卡*1、4级强化石*1、洞悉敌情*2、运动饮料（中）*3、劳资协议书*2、选秀卡*1、球探召回卡*1。");
		key.put(Keys.提示_申请书, "感谢您为竞技大赛提交申请书，您获得了{1}声望。");
		key.put(Keys.提示_申请书道具, "感谢您为竞技大赛提交申请书，您获得了{1}声望、{2}的奖励。");
		key.put(Keys.提示_竞技宝箱, "使用成功，您获得了{1}。");
		key.put(Keys.提示_竞技赛开始, "<font color='#ff0000'>【系统】</font>竞技赛已经开始，请大家赶快去参加活动，赢取竞技宝箱。");
		key.put(Keys.提示_勋章, "使用成功，您获得了{1}。");
		key.put(Keys.提示_掉落宝箱, "很抱歉您的竞技宝箱已掉落。");
		key.put(Keys.提示_得到宝箱, "恭喜您打败对手，抢夺了对方的竞技宝箱。（退出比赛或者被打败，竞技宝箱将会掉落。）");
		key.put(Keys.提示_奖励宝箱, "通过重重考验，您获得最终的胜利，得到了竞技宝箱道具。");
		key.put(Keys.提示_比赛掉落宝箱, "您被对手击败，竞技宝箱被对方夺取。");
		key.put(Keys.提示_竞猜结束, "恭喜您成功竞猜{1}场比赛，获得了{2}万经费的奖励。");
		key.put(Keys.提示_迷宫奖励, "恭喜您获得了{1}、{2}的奖励。");
		key.put(Keys.提示_迷宫胜利跳层, "您战胜对手，来到了球馆迷宫的第{1}层。");
		key.put(Keys.提示_迷宫失败跳层, "您被对手击败，来到了球馆迷宫的第{1}层。");
		key.put(Keys.提示_多人赛即将开赛, "您报名的{1}将于15分钟后开启，请认真准备，积极迎战！");
		key.put(Keys.提示_超级豪华礼包, "使用成功，你获得了底薪球星卡*1、经费兑换券*1、4级强化石*1。");
		key.put(Keys.提示_年费会员大礼包,"使用成功，您获得了底薪球星卡*1，经费兑换券*1，4级强化石*1。");
		key.put(Keys.提示_月费会员大礼包, "使用成功，你获得了选秀卡*1、2级强化石*1、矿泉水（小）*1。");
		key.put(Keys.提示_空间活动大礼包, "使用成功，你获得了选秀卡*1、球探召回卡*2、4级强化石*1、双倍声望卡*1、功能饮料（大）*1、运动饮料（中）*1。");
		key.put(Keys.提示_充值奖品A礼包, "使用成功，您获得了球探召回卡*1。");
		key.put(Keys.提示_充值奖品B礼包, "使用成功，您获得了球探召回卡*2、矿泉水（中）*3。");
		key.put(Keys.提示_充值奖品C礼包, "使用成功，您获得了劳资协议书*2、选秀卡*1、运动饮料（小）*2。");
		key.put(Keys.提示_充值奖品D礼包, "使用成功，您获得了劳资协议书*3、嘘声*2、5级强化石*1");
		key.put(Keys.提示_充值奖品E礼包, "使用成功，您获得了底薪球星卡*1、恢复大礼包*1、5级强化石*2。");
		key.put(Keys.提示_充值奖品F礼包, "使用成功，您获得了底薪球星卡*2、恢复大礼包*1、比赛大礼包*1、5级强化石*4。");
		key.put(Keys.提示_梦之队礼包, "使用成功，您获得了功能饮料（中）*10、矿泉水（中）*8、运动饮料（中）*8。");

		key.put(Keys.装备_头巾1, "Kopfband aus grobes Tuch");
		key.put(Keys.装备_头巾2, "Kopfband aus Sackleinen");
		key.put(Keys.装备_头巾3, "grobes Kopfband");
		key.put(Keys.装备_头巾4, "Kopfband aus Baumwolle");
		key.put(Keys.装备_头巾5, "leichter Kopfband");
		key.put(Keys.装备_头巾6, "Kopfband aus Leder");
		key.put(Keys.装备_头巾7, "elastischer Kopfband");
		key.put(Keys.装备_头巾8, "Kopfband aus Seide");
		key.put(Keys.装备_头巾9, "feiner Kopfband");
		key.put(Keys.装备_头巾10, "hochwertiger Kopfband");
		key.put(Keys.装备_头巾11, "Kopfband aus Faser");
		key.put(Keys.装备_头巾12, "Kopfband aus Kohlefaser");
		key.put(Keys.装备_头巾13, "Kopfband aus Terylen");
		key.put(Keys.装备_头巾14, "glänzender Kopfband");
		key.put(Keys.装备_头巾15, "Traum Kopfband");
		key.put(Keys.装备_头巾16, "Blitz Kopfband");
		key.put(Keys.装备_头巾17, "Flieger Kopfband");
		key.put(Keys.装备_头巾18, "König Kopfband");
		key.put(Keys.装备_头巾19, "Gespenst Kopfband");
		key.put(Keys.装备_头巾20, "Rose Kopfband");
		key.put(Keys.装备_头巾21, "Melone Kopfband");
		key.put(Keys.装备_头巾22, "Bienenkönigin Kopfband");
		key.put(Keys.装备_头巾23, "Donner Kopfband");
		key.put(Keys.装备_头巾24, "Dirkules´Kopfband");
		key.put(Keys.装备_头巾25, "霸王头巾");
		key.put(Keys.装备_头巾26, "狼王头巾");

		key.put(Keys.装备_护腕1, "Handhut aus Kattun");
		key.put(Keys.装备_护腕2, "Handhut aus Sackleinen");
		key.put(Keys.装备_护腕3, "Handhut aus Nylon");
		key.put(Keys.装备_护腕4, "Handhut aus Baumwolle");
		key.put(Keys.装备_护腕5, "harter Handhut");
		key.put(Keys.装备_护腕6, "Handhut aus Rubber");
		key.put(Keys.装备_护腕7, "leichter Handhut");
		key.put(Keys.装备_护腕8, "Handhut aus Seide");
		key.put(Keys.装备_护腕9, "Feiner Handhut");
		key.put(Keys.装备_护腕10, "Hochwertiger Handhut");
		key.put(Keys.装备_护腕11, "Handhut aus Faser");
		key.put(Keys.装备_护腕12, "Handhut aus Kohlefaser");
		key.put(Keys.装备_护腕13, "Handhut aus Terylen");
		key.put(Keys.装备_护腕14, "zutreffender Handhut");
		key.put(Keys.装备_护腕15, "Handhut mit Hoheit");
		key.put(Keys.装备_护腕16, "Blitz Handhut");
		key.put(Keys.装备_护腕17, "Flieger Handhut");
		key.put(Keys.装备_护腕18, "König Handhut");
		key.put(Keys.装备_护腕19, "Gespenst Handhut");
		key.put(Keys.装备_护腕20, "Rose Handhut");
		key.put(Keys.装备_护腕21, "Melone Handhut");
		key.put(Keys.装备_护腕22, "Bienenkönigin Handhut");
		key.put(Keys.装备_护腕23, "Donner Handhut");
		key.put(Keys.装备_护腕24, "Dirkules´Handhut");
		key.put(Keys.装备_护腕25, "霸王护腕");
		key.put(Keys.装备_护腕26, "狼王护腕");

		key.put(Keys.装备_战袍1, "Kleid aus blaue Stoff");
		key.put(Keys.装备_战袍2, "Kleid aus Sackleinen");
		key.put(Keys.装备_战袍3, "Kleid aus Nylon");
		key.put(Keys.装备_战袍4, "Kleid aus Baumwolle");
		key.put(Keys.装备_战袍5, "Kleid aus Chemiefaser");
		key.put(Keys.装备_战袍6, "leichter Kleid");
		key.put(Keys.装备_战袍7, "Zäh Kleid");
		key.put(Keys.装备_战袍8, "Kleid aus Seide");
		key.put(Keys.装备_战袍9, "Kleid aus Mischgewebe");
		key.put(Keys.装备_战袍10, "Glanz Kleid");
		key.put(Keys.装备_战袍11, "Kleid aus Faser");
		key.put(Keys.装备_战袍12, "Kleid aus Kohlerfaser");
		key.put(Keys.装备_战袍13, "Kleid aus Terylen");
		key.put(Keys.装备_战袍14, "Revolution Kleid");
		key.put(Keys.装备_战袍15, "Glorie Kleid");
		key.put(Keys.装备_战袍16, "Blitz Kleid");
		key.put(Keys.装备_战袍17, "Flieger Kleid");
		key.put(Keys.装备_战袍18, "König Kleid");
		key.put(Keys.装备_战袍19, "Gespenst Kleid");
		key.put(Keys.装备_战袍20, "Rose Kleid");
		key.put(Keys.装备_战袍21, "Melone Kleid");
		key.put(Keys.装备_战袍22, "Bienenkönigin Kleid");
		key.put(Keys.装备_战袍23, "Thor´s Kleid");
		key.put(Keys.装备_战袍24, "Dirkules´Kleid");
		key.put(Keys.装备_战袍25, "霸王战袍");
		key.put(Keys.装备_战袍26, "狼王战袍");

		key.put(Keys.装备_护膝1, "Kniehut aus rote Stoff");
		key.put(Keys.装备_护膝2, "Kniehut aus Sackleinen");
		key.put(Keys.装备_护膝3, "grober Kniehut");
		key.put(Keys.装备_护膝4, "Kniehut aus Baumwolle");
		key.put(Keys.装备_护膝5, "Kniehut aus Leder");
		key.put(Keys.装备_护膝6, "Kniehut aus Rubber");
		key.put(Keys.装备_护膝7, "feiner Kniehut");
		key.put(Keys.装备_护膝8, "Kniehut aus Seide");
		key.put(Keys.装备_护膝9, "elastische Kniehut");
		key.put(Keys.装备_护膝10, "Zäh Kniehut");
		key.put(Keys.装备_护膝11, "Kniehut aus Faser");
		key.put(Keys.装备_护膝12, "Kniehut aus Kohlerfaser");
		key.put(Keys.装备_护膝13, "Kniehut aus Terylen");
		key.put(Keys.装备_护膝14, "Kraft Kniehut");
		key.put(Keys.装备_护膝15, "Kriegsgott Kniehut");
		key.put(Keys.装备_护膝16, "Blitz Kniehut");
		key.put(Keys.装备_护膝17, "Flieger Kniehut");
		key.put(Keys.装备_护膝18, "König Kniehut");
		key.put(Keys.装备_护膝19, "Gespenst Kniehut");
		key.put(Keys.装备_护膝20, "Rose Kniehut");
		key.put(Keys.装备_护膝21, "Melone Kniehut");
		key.put(Keys.装备_护膝22, "Bienenkönigin Kniehut");
		key.put(Keys.装备_护膝23, "Thor´s Kniehut");
		key.put(Keys.装备_护膝24, "Dirkules´Kniehut");
		key.put(Keys.装备_护膝25, "霸王护膝");
		key.put(Keys.装备_护膝26, "狼王护膝");

		key.put(Keys.装备_战靴1, "cloth shoes");
		key.put(Keys.装备_战靴2, "Skate Schuhe");
		key.put(Keys.装备_战靴3, "Gummischuh");
		key.put(Keys.装备_战靴4, "Kraft Schuhe");
		key.put(Keys.装备_战靴5, "Sandalette");
		key.put(Keys.装备_战靴6, "Schuhe aus Rubber");
		key.put(Keys.装备_战靴7, "Sprung Schuhe aus Rubber");
		key.put(Keys.装备_战靴8, "Luftkissen Schuhe");
		key.put(Keys.装备_战靴9, "Sport Schuhe");
		key.put(Keys.装备_战靴10, "Bienenstock Schuhe");
		key.put(Keys.装备_战靴11, "Hoher Druck-Luftkissen Schuhe");
		key.put(Keys.装备_战靴12, "Schuhe aus Kohlerfaser");
		key.put(Keys.装备_战靴13, "Legierung Schuhe");
		key.put(Keys.装备_战靴14, "Ausfederung Schuhe");
		key.put(Keys.装备_战靴15, "Zauber Schuhe");
		key.put(Keys.装备_战靴16, "Blitz Schuhe");
		key.put(Keys.装备_战靴17, "Flieger Schuhe");
		key.put(Keys.装备_战靴18, "König Schuhe");
		key.put(Keys.装备_战靴19, "Gespenst Schuhe");
		key.put(Keys.装备_战靴20, "Rose Schuhe");
		key.put(Keys.装备_战靴21, "Melone Schuhe");
		key.put(Keys.装备_战靴22, "Bienenkönigin Schuhe");
		key.put(Keys.装备_战靴23, "Thor´s Schuhe");
		key.put(Keys.装备_战靴24, "Dirkules´Schuhe");
		key.put(Keys.装备_战靴25, "霸王战靴");
		key.put(Keys.装备_战靴26, "狼王战靴");

		key.put(Keys.描述_头巾1, "Kopfband aus grobes Tuch, ganz grob.");
		key.put(Keys.描述_头巾2, "grobe Lein, hart, aber nicht bequem.");
		key.put(Keys.描述_头巾3, "normaler Stoff, gute Durchlässigkeit, aber nicht so schön.");
		key.put(Keys.描述_头巾4, "Kopfband aus Baumwolle, kann die Schweiß besser aufnehmen.");
		key.put(Keys.描述_头巾5, "leichter Kopfband, weich, wie nichts.");
		key.put(Keys.描述_头巾6, "Kopfband aus Leder, kann den Kopf besser verteidigen, aber kann die schweiß nicht besser aufnehmen.");
		key.put(Keys.描述_头巾7, "große Nachgiebigkeit, kann den Kopf besser verteigigen.");
		key.put(Keys.描述_头巾8, "aus feiner Seide. Weich und bequem.");
		key.put(Keys.描述_头巾9, "aus hochwertige Stoff, fein gemacht.große Nachgiebigkeit. Sicher und bequem.");
		key.put(Keys.描述_头巾10, "hoch Qualitäte, bequem, kann den Kopf besser Verteidigen. und kann die Schweiß besser aufnehmen.");
		key.put(Keys.描述_头巾11, "aus natürliche Faser. Bequem und kann die Schweiß besser aufnehmen.");
		key.put(Keys.描述_头巾12, "Mit Kohlerfaser ist es sehr leicht, hart. sicher und langlebig.");
		key.put(Keys.描述_头巾13, "Hart, gute Elastizität. Kann den Kopf wirksam verteidigen.");
		key.put(Keys.描述_头巾14, "aus Spezialle Stoff, blitzend und blumig, kann die Gegner aber stören.");
		key.put(Keys.描述_头巾15, "Es tragt Basketball Dream und besitzt mächtige Fähigkeit");
		key.put(Keys.描述_头巾16, "Wade´s Kopfband, oder?");
		key.put(Keys.描述_头巾17, "Kobe´s Kopfband, oder?");
		key.put(Keys.描述_头巾18, "James´Kopfband, oder?");
		key.put(Keys.描述_头巾19, "Howard´s Kopfband, nicht wahr?");
		key.put(Keys.描述_头巾20, "Rose´s Kopfband, nicht wahr?");
		key.put(Keys.描述_头巾21, "Anthony´s Kopfband, nicht wahr?");
		key.put(Keys.描述_头巾22, "Paul´s Kopfband, nicht wahr?");
		key.put(Keys.描述_头巾23, "Durant´s Kopfband, nicht wahr?");
		key.put(Keys.描述_头巾24, "Das warNowitzki´s Kopfband, nicht wahr ?");
		key.put(Keys.描述_头巾25, "小霸王斯塔德迈尔穿戴过的头巾，有木有？有木有！");
		key.put(Keys.描述_头巾26, "狼王加内特穿戴过的头巾，有木有？有木有！");

		key.put(Keys.描述_护腕1, "einfache Handhut aus Kattun, wird aber den Handgelenk verteidigen.");
		key.put(Keys.描述_护腕2, "aus Sackleinen. Grob, aber kann den Handgelenk verteidigen.");
		key.put(Keys.描述_护腕3, "aus Nylon. hat hoche Beständigkeit und Härte.");
		key.put(Keys.描述_护腕4, "aus Baumwolle mit hoch Qualität. fein gemacht. schöne Saugfähigkeit und Gasdurchlässigkeit.");
		key.put(Keys.描述_护腕5, "Hart,robust. Aber die Mobilität ist relativ schlecht.");
		key.put(Keys.描述_护腕6, "Aus Mix von Rubber und Leder. Kann die Kraft von Handgelenk verbessern.");
		key.put(Keys.描述_护腕7, "Aus Filoselle. ganz elegant.Hoche Mobilität.");
		key.put(Keys.描述_护腕8, "Aus Seide. ganz bequem. schlechte Saugfähigkeit.");
		key.put(Keys.描述_护腕9, "Aus ramie cotton, fein gemacht. bequem und saugfähig.");
		key.put(Keys.描述_护腕10, "hoch Qualität, die Spieler kann seine Stärke völlig entfalten.");
		key.put(Keys.描述_护腕11, "aus natürliche Faser.natürlich und bequem.");
		key.put(Keys.描述_护腕12, "aus harte Kohlefaser, besitzt sehr hohe Zähigkei.");
		key.put(Keys.描述_护腕13, "aus Terylen, Kann die Kraft von Handgelenk verbessern.");
		key.put(Keys.描述_护腕14, "aus spezielle Stoffe, kann die Korbquote verbessern.");
		key.put(Keys.描述_护腕15, "Hoheit. Kann die Kraft von Gelenk, Korbquote verbessen. und kann Handgelenk effektiv verteidigen.");
		key.put(Keys.描述_护腕16, "Wade´s Handhut, oder?");
		key.put(Keys.描述_护腕17, "Kobe´s Handhut, oder?");
		key.put(Keys.描述_护腕18, "James´Handhut, oder?");
		key.put(Keys.描述_护腕19, "Howard´s Handhut, nicht wahr?");
		key.put(Keys.描述_护腕20, "Rose´s Handhut, nicht wahr?");
		key.put(Keys.描述_护腕21, "Anthony´s Handhut, nicht wahr?");
		key.put(Keys.描述_护腕22, "Paul´s Handhut, nicht wahr?");
		key.put(Keys.描述_护腕23, "Durant´s Handhut, nicht wahr?");
		key.put(Keys.描述_护腕24, "Nowitzki´s Handht, verstehst du?");
		key.put(Keys.描述_护腕25, "小霸王斯塔德迈尔戴过的护腕，你懂的…");
		key.put(Keys.描述_护腕26, "狼王加内特戴过的护腕，你懂的…");

		key.put(Keys.描述_战袍1, "Aus blaue Stoff, ganz einfach und normal.");
		key.put(Keys.描述_战袍2, "aus Sackleinen, nicht bequem. Aussehen sit auch grob und hart.");
		key.put(Keys.描述_战袍3, "Aus Nylon. besitzt hoche Härte. es ist geeignet für heftige Kampf.");
		key.put(Keys.描述_战袍4, "aus Baumwolle, hat gute Gasdurchlässigkeit. sehr bequeme Kleid.");
		key.put(Keys.描述_战袍5, "Aus Chemiefaser. samtartig und bequem.");
		key.put(Keys.描述_战袍6, "elegant, hohe Mobilität.");
		key.put(Keys.描述_战袍7, "aus natürliche Stoffe. ganz hart und gute Gasdurchlässigkeit.");
		key.put(Keys.描述_战袍8, "aus harte Seide. samtartig und robust.");
		key.put(Keys.描述_战袍9, "aus Mix von natürliche Faser und Chemiefaser.preiswert und von guter Qualität.");
		key.put(Keys.描述_战袍10, "glänzend und lebendig.");
		key.put(Keys.描述_战袍11, "Hi-Tech Faser als Stoffe, fein gemacht sowie die Natur.");
		key.put(Keys.描述_战袍12, "Hi-Tech Kohlerfaser als Stoffe, samtartig, bequem. besitzt sehr hohe Härte.");
		key.put(Keys.描述_战袍13, "aus Terylen, saugfähig und gasdurchlässig, hart.");
		key.put(Keys.描述_战袍14, "leichter, gasdurchlässiger, freiheitlicher, robuster, popülärer, umweltfreundlicher.");
		key.put(Keys.描述_战袍15, "Es ist ein Symbol mit zahlreicher Glorie. Kann die Fähigkeit von Spieler verbessern.");
		key.put(Keys.描述_战袍16, "Gott, das ist eigentlich Kleid von Wade´s.");
		key.put(Keys.描述_战袍17, "Gott, das ist eigentlich Kleid von Kobe´s.");
		key.put(Keys.描述_战袍18, "Gott, das ist eigentlich Kleid von James´.");
		key.put(Keys.描述_战袍19, "Gott, das ist eigentlich Kleid von Howard´s.");
		key.put(Keys.描述_战袍20, "Gott, das ist eigentlich Kleid von Rose´s.");
		key.put(Keys.描述_战袍21, "Gott, das ist eigentlich Kleid von Anthony´s.");
		key.put(Keys.描述_战袍22, "Gott, das ist eigentlich Kleid von Paul´s.");
		key.put(Keys.描述_战袍23, "Gott, das ist eigentlich Kleid von Durant´s.");
		key.put(Keys.描述_战袍24, "Gott, das war eigentlich Nowitzki´s Kleid！");
		key.put(Keys.描述_战袍25, "尼玛，原来是小霸王斯塔德迈尔穿过的战袍！");
		key.put(Keys.描述_战袍26, "尼玛，原来是狼王加内特穿过的战袍！");

		key.put(Keys.描述_护膝1, "aus rote Stoff, um Knie zu Verteidigen. aber schlechte Stoff.");
		key.put(Keys.描述_护膝2, "Aus Sacklein, hoch Gasdurchlässigkeit, aber schlechte Härte.");
		key.put(Keys.描述_护膝3, "Aus Mix von Baumwolle und Seide. Ganz grob.");
		key.put(Keys.描述_护膝4, "Aus Baumwolle, fein gemacht. hoch saugfähig, bequem.");
		key.put(Keys.描述_护膝5, "aus weiche Leder. Hoch Härte. robust.");
		key.put(Keys.描述_护膝6, "aus hoch qualität Rubber gemacht. Kann die Knie effektiv verteigigen. aber veraltet sich relativ schneller.");
		key.put(Keys.描述_护膝7, "aus Mix von Baumwolle, Seide, Sackleinen. fein gemacht.preiswert und von guter Qualität.");
		key.put(Keys.描述_护膝8, "Aus Seide mit hoch Qualität. fein gemacht. Weich, bequem, hart.");
		key.put(Keys.描述_护膝9, "besitzt hohe Elastizität. Kann die Knie effektiv verteidigen.");
		key.put(Keys.描述_护膝10, "Aus Stoffe mit hoche Intensität. Besitzt hohe Zähigkeit.");
		key.put(Keys.描述_护膝11, "aus durch Chemie gemachte natürliche Faser. besitzt hohe Dehnbarkeit und Zähigkeit.");
		key.put(Keys.描述_护膝12, "Aus Hi-Tech Kohlerfaser. kann die Knie sehr gut verteidigen.");
		key.put(Keys.描述_护膝13, "Aus Terylen. Hohe Härte. robust.");
		key.put(Keys.描述_护膝14, "kann die Kraft von Knie verbessern. und den Aufpralle von Spieler verbessern.");
		key.put(Keys.描述_护膝15, "aus Hi-tech gehende Kniehut, kann die Kampffähigkeit von Spieler dauerhaft verbessern.");
		key.put(Keys.描述_护膝16, "Gott, das ist eigentlich Kniehut von Wade´s");
		key.put(Keys.描述_护膝17, "Gott, das ist eigentlich Kniehut von Kobe´s");
		key.put(Keys.描述_护膝18, "Gott, das ist eigentlich Kniehut von James´");
		key.put(Keys.描述_护膝19, "Gott, das ist eigentlich Kniehut von Howard´s");
		key.put(Keys.描述_护膝20, "Gott, das ist eigentlich Kniehut von Rose´s");
		key.put(Keys.描述_护膝21, "Gott, das ist eigentlich Kniehut von Anthony´s");
		key.put(Keys.描述_护膝22, "Gott, das ist eigentlich Kniehut von Paul´s");
		key.put(Keys.描述_护膝23, "Gott, das ist eigentlich Kniehut von Durant´s");
		key.put(Keys.描述_护膝24, "Gott, das war eigentlich Kniehut von Nowitzki´s");
		key.put(Keys.描述_护膝25, "小霸王斯塔德迈尔佩戴的护膝，你伤不起…");
		key.put(Keys.描述_护膝26, "狼王加内特佩戴的护膝，你伤不起…");

		key.put(Keys.描述_战靴1, "von Mama Selbst gemachte Schuhe, warm und bequem.");
		key.put(Keys.描述_战靴2, "Rubber Schuhe. Stoßfest, ganz hart.");
		key.put(Keys.描述_战靴3, "normaler aus Rubber gemacht Schuhe. hart. geeignet für Sport.");
		key.put(Keys.描述_战靴4, "allgemeine Sportschuhe, ätherisch.");
		key.put(Keys.描述_战靴5, "aus Segel gemacht. ätherisch und biegsam.");
		key.put(Keys.描述_战靴6, "aus Rubber gemacht.ganz hart.");
		key.put(Keys.描述_战靴7, "Die Schuhe hat sehr große Auffederung.Kann die Sprungfähigkeit von Spieler verbessern.");
		key.put(Keys.描述_战靴8, "Aus Mix von natürliche Leder und synthetische Leder. Innen gibt es Luftkissen. besitzt hohe Sprungsfähigkeit.");
		key.put(Keys.描述_战靴9, "aus Kinematik-Theorie gemachte Schuhe. Spezielle für Sport gemacht.");
		key.put(Keys.描述_战靴10, "Benutzt Bienenstock Technik. besitzt Abschwächung Funktion. ist eine hochgradige Schuhe.");
		key.put(Keys.描述_战靴11, "hoch druck. Luftkissen. Kann die Fuß besser verteidgien. besitzt gute Zähigkeit.");
		key.put(Keys.描述_战靴12, "die Meisten Fläche aus Kohlerfaser gemacht. Besitzt sehr gute Zähigkeit.");
		key.put(Keys.描述_战靴13, "aus leichte Legierung gamacht. Leicht, bequem, Modern und sehr blühend.");
		key.put(Keys.描述_战靴14, "Aus Stoffe mit super Ausfederung. besitzt super Sprungsfähigkeit und gute Abschwächung Funktion.");
		key.put(Keys.描述_战靴15, "eine zauber Schuhe. besitzt super Sprungsfähigkeit. Abschwächung, und Beschleunigung Funktion.");
		key.put(Keys.描述_战靴16, "Es ist Klar.das ist eigentlich Schuhe von Wade´s");
		key.put(Keys.描述_战靴17, "Es ist Klar.das ist eigentlich Schuhe von Kobe´s");
		key.put(Keys.描述_战靴18, "Es ist Klar.das ist eigentlich Schuhe von James´");
		key.put(Keys.描述_战靴19, "Es ist Klar.das ist eigentlich Schuhe von Howard´s");
		key.put(Keys.描述_战靴20, "Es ist Klar.das ist eigentlich Schuhe von Rose´s");
		key.put(Keys.描述_战靴21, "Es ist Klar.das ist eigentlich Schuhe von Anthony´s");
		key.put(Keys.描述_战靴22, "Es ist Klar.das ist eigentlich Schuhe von Paul´s");
		key.put(Keys.描述_战靴23, "Es ist Klar.das ist eigentlich Schuhe von Durant´s");
		key.put(Keys.描述_战靴24, "Es ist Klar. Das ist eigentlich Schuhe von Nowitzki´s");
		key.put(Keys.描述_战靴25, "小霸王斯塔德迈尔穿过的战靴，不解释…");
		key.put(Keys.描述_战靴26, "狼王加内特穿过的战靴，不解释…");

		key.put(Keys.道具_选秀卡,"Draft-Karte");
		key.put(Keys.道具_队徽卡,"plakette-Karte");
		key.put(Keys.道具_奢侈卡,"Luxus Karte");
		key.put(Keys.道具_球探召回卡,"Rückruf von Scounts");
		key.put(Keys.道具_洗髓经,"Talent Wechsel");
		key.put(Keys.道具_小秘书更换卡,"Welchsel der Sekretärin");
		key.put(Keys.道具_交易许可券,"Erlaubnis zu Handel");
		key.put(Keys.道具_联盟令,"Liga Befehl");
		key.put(Keys.道具_小喇叭,"Lautsprecher");
		key.put(Keys.道具_球队名更换卡,"Name Welchsel Karte");
		key.put(Keys.道具_负场清除卡,"Verlor entfernen Karte");
		key.put(Keys.道具_级强化石1,"1 Stufe-Verstärkung");
		key.put(Keys.道具_级强化石2,"2 Stufe-Verstärkung");
		key.put(Keys.道具_级强化石3,"3 Stufe-Verstärkung");
		key.put(Keys.道具_级强化石4,"4 Stufe-Verstärkung");
		key.put(Keys.道具_级强化石5,"5 Stufe-Verstärkung");
		key.put(Keys.道具_幸运符,"Glückspapier");
		key.put(Keys.道具_神佑符,"Versicherungspapier");
		key.put(Keys.道具_咆哮,"Knurren");
		key.put(Keys.道具_嘘声,"zischen");
		key.put(Keys.道具_喝彩,"Hochruf");
		key.put(Keys.道具_洞悉敌情,"Durchsehen");
		key.put(Keys.道具_啦啦队热舞,"Cheerleaders");
		key.put(Keys.道具_NBA挑战券,"NBA Herausforderungspapier");
		key.put(Keys.道具_经费兑换券,"Kredit Karte");
		key.put(Keys.道具_高级经费兑换券,"Top-Kredit Gegenwechsel");
		key.put(Keys.道具_高级双倍声望卡,"Top verdoppelte Ruf");
		key.put(Keys.道具_双倍声望卡,"doppelte Ruf Karte");
		key.put(Keys.道具_底薪替补卡,"Minimum-Lohn Ersatz");
		key.put(Keys.道具_底薪替补卡赠,"底薪替补卡（赠）");
		key.put(Keys.道具_封闭针,"封闭针");
		key.put(Keys.道具_球星卡,"Stern Karte");
		key.put(Keys.道具_超级巨星卡,"Super Star Karte");
		key.put(Keys.道具_底薪球星卡,"Minimum-Lohn Star");
		key.put(Keys.道具_激情板凳卡,"Passion-Bench");
		key.put(Keys.道具_超值大礼包,"Über-Wert Paket");
		key.put(Keys.道具_助威小礼包,"Cheer Paket");
		key.put(Keys.道具_Facebook礼包,"Facebook Paket");
		key.put(Keys.道具_充值大礼包,"Aufladungs paket");
		key.put(Keys.道具_工资帽,"50 Höchstlohn");
		key.put(Keys.道具_5级新手礼包,"5 Stufe Belohnungen");
		key.put(Keys.道具_10级新手礼包,"10 Stufe Belohnungen");
		key.put(Keys.道具_20级新手礼包,"20 Stufe Belohnungen");
		key.put(Keys.道具_传奇巨星随机卡,"X-Superstar Stochastik");
		key.put(Keys.道具_传奇巨星更换卡,"X-Superstar Wechsel");
		key.put(Keys.道具_补偿礼包A, "Kompensation A");
		key.put(Keys.道具_补偿礼包B, "Kompensation B");
		key.put(Keys.道具_补偿礼包C, "Kompensation C");
		key.put(Keys.道具_补偿礼包D, "Kompensation D");
		key.put(Keys.道具_补偿礼包E, "Kompensation E");
		key.put(Keys.道具_功能饮料小,"Energy-Drink(klein)");
		key.put(Keys.道具_功能饮料中,"Energy-Drink(mittel)");
		key.put(Keys.道具_功能饮料大,"Energy-Drink(groß)");
		key.put(Keys.道具_运动饮料小,"Sportgetränke(klein)");
		key.put(Keys.道具_运动饮料中,"Sportgetränke(Mittel)");
		key.put(Keys.道具_运动饮料大,"Sportgetränke(groß)");
		key.put(Keys.道具_矿泉水小,"Mineralwasser(klein)");
		key.put(Keys.道具_矿泉水中,"Mineralwasser(mittel)");
		key.put(Keys.道具_矿泉水大,"Mineralwasser(groß)");
		key.put(Keys.道具_苹果汁小,"Apfelsaft(klein)");
		key.put(Keys.道具_苹果汁中,"Apfelsaft(mittel)");
		key.put(Keys.道具_苹果汁大,"Apfelsaft(groß)");
		key.put(Keys.道具_效果重置卡, "Effekt Rückstellen");
		key.put(Keys.道具_声望卷, "Mondkuchen");
		key.put(Keys.道具_电玩大礼包, "Online game Biweekly Paket");
		key.put(Keys.道具_劳资协议书,"Arbeitsvertrag");
		key.put(Keys.道具_球员竞价券,"Spieler-Kaufangebot");
		key.put(Keys.道具_璀璨碎片,"璀璨碎片");
		key.put(Keys.道具_新春礼包,"新春礼包");
		key.put(Keys.道具_新春大礼包,"新春大礼包");
		key.put(Keys.道具_抽奖道具,"冰激凌");
		key.put(Keys.道具_强化大礼包,"强化大礼包");
		key.put(Keys.道具_恢复大礼包,"恢复大礼包");
		key.put(Keys.道具_比赛大礼包,"比赛大礼包");
		key.put(Keys.道具_豪华礼包,"豪华礼包");
		key.put(Keys.道具_大豪华礼包,"大豪华礼包");
		key.put(Keys.道具_超级豪华礼包,"超级豪华礼包");
		key.put(Keys.道具_申请书,"申请书");
		key.put(Keys.道具_竞技宝箱,"竞技宝箱");
		key.put(Keys.道具_勋章,"勋章");
		key.put(Keys.道具_球员召集令,"球员召集令");
		key.put(Keys.道具_教练更换卡,"教练更换卡");
		key.put(Keys.道具_战术训练卡,"战术训练卡");
		key.put(Keys.道具_任务令,"任务令");
		key.put(Keys.道具_年费会员大礼包,"年费会员大礼包");
		key.put(Keys.道具_月费会员大礼包,"月费会员大礼包");
		key.put(Keys.道具_空间活动大礼包,"空间活动大礼包");
		key.put(Keys.道具_充值奖品A礼包,"储值礼包A");
		key.put(Keys.道具_充值奖品B礼包,"储值礼包B");
		key.put(Keys.道具_充值奖品C礼包,"储值礼包C");
		key.put(Keys.道具_充值奖品D礼包,"储值礼包D");
		key.put(Keys.道具_充值奖品E礼包,"储值礼包E");
		key.put(Keys.道具_充值奖品F礼包,"储值礼包F");
		key.put(Keys.道具_vip打折卡, "Vip打折卡");
		key.put(Keys.道具_彩石,      "彩石");
		key.put(Keys.道具_绑定球券,   "绑定球券");
		key.put(Keys.道具_状态更换卡, "状态更换卡");
		key.put(Keys.描述_选秀卡,"wenn Sie die Karte benutzen, können Sie ins Draft-Zimmer im Voraus eintreten. Und VIP genießen.");
		key.put(Keys.描述_队徽卡,"Wenn Sie die Karte benutzen, können Sie die Palakett von Ihrer Mannschaft welchseln.");
		key.put(Keys.描述_奢侈卡,"Wenn Sie die Karte benutzen, werden die Luxusplatz für mehrere Spieler aktiviert. Sie können mehrere Spieler in Ihrer mannschaft behalten.");
		key.put(Keys.描述_球探召回卡,"Wenn Sie die Karte benutzen,werden die Kundschafter zwanghaft zurückgeruft. Sie können mit zurückgebrachte Spieler unterzeichnen.");
		key.put(Keys.描述_洗髓经,"Wenn Sie die Karte benutzen, können Sie Talent von Ihrer Mannschaft wieder auswählen.");
		key.put(Keys.描述_小秘书更换卡,"Wenn Sie die Karte benutzen, können Sie die Sekretärin wechseln.");
		key.put(Keys.描述_交易许可券,"Mit Erlaubnis Karte zu Handel können Sie Ihre Spieler in frei Handel Zone verkaufen.");
		key.put(Keys.描述_联盟令,"Wenn Sie die Karte benutzen, können Sie eine Liga gründen.");
		key.put(Keys.描述_小喇叭,"Mit Lautsprecher können Ihre Rede an alle Server mitteilen. Es besitzt auch spezielle Effekt.");
		key.put(Keys.描述_球队名更换卡,"Mit dieser Karte können Sie Ihre Mannschaft eine schönen Name benennen.");
		key.put(Keys.描述_负场清除卡,"Mit diese Karte können Sie Ihre 10 Verlierte Spiel von Rekord entfernen.");
		key.put(Keys.描述_级强化石1,"Damit kann man seine Ausrüstung-Verstärkung Erfolgsquote erhöhen.");
		key.put(Keys.描述_级强化石2,"Damit kann man seine Ausrüstung-Verstärkung Erfolgsquote höher als Stufe 1 erhöhen.");
		key.put(Keys.描述_级强化石3,"Damit kann man seine Ausrüstung-Verstärkung Erfolgsquote höher als Stufe 2 erhöhen.");
		key.put(Keys.描述_级强化石4,"Damit kann man seine Ausrüstung-Verstärkung Erfolgsquote höher als Stufe 3 erhöhen.");
		key.put(Keys.描述_级强化石5,"Damit kann man seine Ausrüstung-Verstärkung Erfolgsquote höher als Stufe 4 erhöhen.");
		key.put(Keys.描述_幸运符,"Wenn man es benutzt, werde die Erfolgsquote um 25% aufgestiegen.");
		key.put(Keys.描述_神佑符,"Wenn man es benutzt, und die Verstärkung verloren geht, werden die Verstärungsstufe zurückgehen.");
		key.put(Keys.描述_劳资协议书,"Wenn man es benutzt, kann man mit bestimmtem Spieler über den Lohn erneuert verhandeln. Und dessen Lohn in den vergangenen 30 Tage wird verändert");
		key.put(Keys.描述_球员竞价券,"Wenn man es besitzt, kann man an die Spieler-Kaufangebot teilnehmen. Dadurch gewinnt man an den verliebten Spieler mit niedriegsten Lohn.");
		key.put(Keys.描述_璀璨碎片,"用来点亮璀璨套装，点亮后可以获得该装备。");
		key.put(Keys.描述_咆哮,"Spieler aus eigener Mannschaft knurren, werden Kraft von einer Spieler aus Gegner um 30 Punkt senken.");
		key.put(Keys.描述_嘘声,"Wegen Stärke von Hause,Spieler aus eigener Mannschaft zischen. Kraft von allen Spielern aus Gegner um 10 Punkt senken.");
		key.put(Keys.描述_喝彩,"Wenn Sie gut entfaltet, Zuschauer werden hochrufen. Kraft von allen Spieler aus Ihrer Mannschaft um 3 Punkt aufsteigen, die von Gegener um 5 Punkt senken.");
		key.put(Keys.描述_洞悉敌情,"wenn Sie Während des Spiels es benutzen, werden Sie die Taktik von Gegner wissen.");
		key.put(Keys.描述_啦啦队热舞,"Cheerleader werden für Sie hochrufen. Erholungstempo werden sich um 5 Punkt/ halbe Stunde erhöhen。Es ist gültig innerhalb 3 Tage.");
		key.put(Keys.描述_NBA挑战券,"Wenn Sie die Karte benutzen, können Sie extra Chance bekommen, an NBA-SPiel noch mal teilnehmen, um die reichste Belohnung zu gewinnen.");
		key.put(Keys.描述_经费兑换券,"Wenn Sie es benutzt, werden Sie 100 Kredit bekommen.");
		key.put(Keys.描述_高级经费兑换券,"Wenn Sie es benutzt, werden Sie 1000 Kredit bekommen.");
		key.put(Keys.描述_高级双倍声望卡,"Nach Abschluss des Spiels werden der Ruf verdoppelt. gültig in 7 Tage.");
		key.put(Keys.描述_双倍声望卡,"Nach Abschluss des Spiels werden der Ruf verdoppelt. gültig in 1 Tage.");
		key.put(Keys.描述_底薪替补卡,"Wenn Sie die Minimum-Lohn Reservist Karte benutzt, werden ein Spieler für Ihre Mannschaft ausgewählt. Lohn der Spieler senken um 10%.");
		key.put(Keys.描述_底薪替补卡赠,"Wenn Sie die Minimum-Lohn Reservist Karte benutzt, werden ein Spieler für Ihre Mannschaft ausgewählt. Lohn der Spieler senken um 10%.");
		key.put(Keys.描述_封闭针,"对受伤的球员使用封闭针，可以让其在24小时内正常参加比赛。若该球员被交易后，则封闭针自动失效。");
		key.put(Keys.描述_申请书,"竞技大赛开启的必需品，提交可以获得声望奖励，还有一定概率获得橙装奖励。");
		key.put(Keys.描述_竞技宝箱,"竞技大赛中争夺的宝箱，胜利者获得拥有权。比赛结束后可开启，获得丰厚奖励。");
		key.put(Keys.描述_勋章,"竞技大赛中为战绩卓越的篮球经理颁发的奖励。可以用来兑换部分道具或装备。");
		key.put(Keys.描述_球员召集令,"拥有召集令，随时可以签约好友球探带回的自由球员。");
		key.put(Keys.描述_教练更换卡,"拥有此卡，可以更换球队聘请的教练，提高相应攻防战术的熟练度上限。");
		key.put(Keys.描述_战术训练卡,"拥有此卡，可以进行特级以上战术的训练，最高可将战术训练至专家级。");
		key.put(Keys.描述_任务令,"拥有此令，可以直接完成日常任务或联盟任务，获得丰厚奖励。");
		key.put(Keys.描述_球星卡,"Wenn Sie die Stern karte benutzt, System werden einen Stern Spieler für Sie wählen. Bewertung der Spieler ist A.");
		key.put(Keys.描述_超级巨星卡,"Wenn Sie die Super Stern karte benutzt, System werden einen Super Stern Spieler für Sie wählen. Bewertung der Spieler ist S.");
		key.put(Keys.描述_底薪球星卡,"Wenn Sie Minimum-Lohn Star Karte benutzt, System werdeen einen Spieler für Sie wählen, dessen Bewertung ist S oder A. Lohn werden sich sum 10% senken.");
		key.put(Keys.描述_激情板凳卡,"Wenn Sie es benutzt,erhöht Erholungstempo von Bench-Spieler um 15%, gültig in 3 Tage");
		key.put(Keys.描述_超值大礼包,"eröffnen das Paket, Sie werden die folgende Artikel bekommen, hochgradige Kredit karte x1,Minimum-Lohn Star Karte x1,Sportgetränke x5, Draft karte x5.");
		key.put(Keys.描述_助威小礼包,"Wenn der Spieler, an den Sie hochruft, das Spiel gewinnen, gibt es Prozent, das Paket zu bekommen.");
		key.put(Keys.描述_Facebook礼包,"Wenn Sie alle Aufgaben von Facebook verschaffen, werden Sie Rückruf von Scountsx1,Sportgetränke(klein)x2, Sportgetränke(mittel)x2,Kredit Kartex1 erhalten.");
		key.put(Keys.描述_功能饮料小,"Es gibt darin verschiedene Ernährungen. Es kann die Kraft von allen Spielern um 10 Punkt erhöht. Wärend des Spiels kann man es nicht benutzt");
		key.put(Keys.描述_功能饮料中,"Es gibt darin verschiedene Ernährungen. Es kann die Kraft von allen Spielern um 30 Punkt erhöht. Wärend des Spiels kann man es nicht benutzt.");
		key.put(Keys.描述_功能饮料大,"Es gibt darin verschiedene Ernährungen. Es kann die Kraft von allen Spielern um 50 Punkt erhöht. Wärend des Spiels kann man es nicht benutzt.");
		key.put(Keys.描述_运动饮料小,"Sportgetränke besitzt Zucker und Elektrolyt in richtiger Menge. Nach benutzung werden die Kraft von alle Spielern um 10 Punkt erhöht. Während des Spieles kann man es benutzen");
		key.put(Keys.描述_运动饮料中,"Sportgetränke besitzt Zucker und Elektrolyt in richtiger Menge. Nach benutzung werden die Kraft von alle Spielern um 30 Punkt erhöht. Während des Spieles kann man es benutzen");
		key.put(Keys.描述_运动饮料大,"Sportgetränke besitzt Zucker und Elektrolyt in richtiger Menge. Nach benutzung werden die Kraft von alle Spielern um 50 Punkt erhöht. Während des Spieles kann man es benutzen");
		key.put(Keys.描述_矿泉水小,"Es gibt reiche Mineralien in den Mineralwasser. Nach benutzung kann Kraft einer von deinen Spielern um 10 Punkt erhöhen. Während des Spiels kann man es benutzen");
		key.put(Keys.描述_矿泉水中,"Es gibt reiche Mineralien in den Mineralwasser. Nach benutzung kann Kraft einer von deinen Spielern um 30 Punkt erhöhen. Während des Spiels kann man es benutzen");
		key.put(Keys.描述_矿泉水大,"Es gibt reiche Mineralien in den Mineralwasser. Nach benutzung kann Kraft einer von deinen Spielern um 50 Punkt erhöhen. Während des Spiels kann man es benutzen");
		key.put(Keys.描述_苹果汁小,"Grün, natürlich, gesund, umweltfreudlich. Voller Vitamin und verschiedenen Ernährungen. Nach Benutzung kann die Kraft von einer Spieler um 10 Punkt erhöhen. Während des Spiels kann man es nicht benutzen");
		key.put(Keys.描述_苹果汁中,"Grün, natürlich, gesund, umweltfreudlich. Voller Vitamin und verschiedenen Ernährungen. Nach Benutzung kann die Kraft von einer Spieler um 30 Punkt erhöhen. Während des Spiels kann man es nicht benutzen");
		key.put(Keys.描述_苹果汁大,"Grün, natürlich, gesund, umweltfreudlich. Voller Vitamin und verschiedenen Ernährungen. Nach Benutzung kann die Kraft von einer Spieler um 50 Punkt erhöhen. Während des Spiels kann man es nicht benutzen");
		key.put(Keys.描述_工资帽,"Es kann um 50 Höchstlohn erhöhen. Damit kann man besserer Spieler unterzeichnen.");
		key.put(Keys.描述_5级新手礼包,"Wenn Sie Stufe-5 erreicht, können Sie es eröffnen.");
		key.put(Keys.描述_10级新手礼包,"Wenn Sie Stufe-10 erreicht, können Sie es eröffnen.");
		key.put(Keys.描述_20级新手礼包,"Wenn Sie Stufe-20 erreicht, können Sie es eröffnen.");
		key.put(Keys.描述_强化大礼包, "装备强化必备大礼包，打开可获得：3级强化石*10、4级强化石*10、5级强化石*20、幸运符*10 。");
		key.put(Keys.描述_恢复大礼包, "球员体力恢复大礼包，打开可获得：运动饮料（小）*10、运动饮料（中）*10、功能饮料（中）*10 。");
		key.put(Keys.描述_比赛大礼包, "比赛必备大礼包，打开可获得：咆哮*5、嘘声*5、洞悉敌情*5、运动饮料（小）*5、运动饮料（中）*5 。");key.put(Keys.描述_豪华礼包, "在2012-2-22至2012-3-20期间，在莱尔富便利店购买MyCard指定点数进行储值，即可获取该礼包。");
		key.put(Keys.描述_大豪华礼包, "在2012-2-22至2012-3-20期间，在莱尔富便利店购买MyCard指定点数进行储值，即可获取该礼包。");
		key.put(Keys.描述_超级豪华礼包, "在2012-2-22至2012-3-20期间，在莱尔富便利店购买MyCard指定点数进行储值，即可获取该礼包。");
		key.put(Keys.描述_年费会员大礼包, "活动期间开通NBA年费会员，即可获取该礼包。");
		key.put(Keys.描述_月费会员大礼包, "活动期间开通NBA月费会员，即可获取该礼包。");
		key.put(Keys.描述_空间活动大礼包, "参与QQ空间7周年活动，即有机会获取该礼包。");
		key.put(Keys.描述_充值奖品A礼包,"在活动期间，充值球券100，即可获取该礼包。");
		key.put(Keys.描述_充值奖品B礼包,"在活动期间，充值球券300，即可获取该礼包。");
		key.put(Keys.描述_充值奖品C礼包,"在活动期间，充值球券500，即可获取该礼包。");
		key.put(Keys.描述_充值奖品D礼包,"在活动期间，充值球券1000，即可获取该礼包。");
		key.put(Keys.描述_充值奖品E礼包,"在活动期间，充值球券3000，即可获取该礼包。");
		key.put(Keys.描述_充值奖品F礼包,"在活动期间，充值球券5000，即可获取该礼包。");
		key.put(Keys.描述_合区大礼包,"为庆祝合区，合区的所有玩家均可获得该礼包。");
		key.put(Keys.描述_vip打折卡, "活动期间，凭此道具购买Vip可根据购买时长不同获得最高30%的绑定球券返还,活动结束后消失");
		key.put(Keys.描述_彩石,"彩石");
		key.put(Keys.描述_绑定球券,"绑定球券");
		key.put(Keys.描述_传奇巨星随机卡,"Wenn man Legende Super-Star zufall Karte benutzt, werden die Top-Spieler in seiner Mannschaft zufällig gewechselt.");
		key.put(Keys.描述_传奇巨星更换卡,"Wenn man Legende Super-Star Wechsel Karte benutzt, können SIe ein neue Top-Spieler für seine Mannschaft wählen.");
		key.put(Keys.描述_补偿礼包A, "Entschudigung für die Entstehende Probleme. Sie werden mit unsere Kompensation Paket erstattet. Danke schön für Ihre Unterstützen bei uns.");
		key.put(Keys.描述_补偿礼包B, "Entschudigung für die Entstehende Probleme. Sie werden mit unsere Kompensation Paket erstattet. Danke schön für Ihre Unterstützen bei uns.");
		key.put(Keys.描述_补偿礼包C, "Entschudigung für die Entstehende Probleme. Sie werden mit unsere Kompensation Paket erstattet. Danke schön für Ihre Unterstützen bei uns.");
		key.put(Keys.描述_补偿礼包D, "Entschudigung für die Entstehende Probleme. Sie werden mit unsere Kompensation Paket erstattet. Danke schön für Ihre Unterstützen bei uns.");
		key.put(Keys.描述_补偿礼包E, "Entschudigung für die Entstehende Probleme. Sie werden mit unsere Kompensation Paket erstattet. Danke schön für Ihre Unterstützen bei uns.");
		key.put(Keys.描述_充值大礼包,"Wenn Sie auf Ihr Konto erstenmal aufladen, werden Sie die Belohnungen bekommen.");
		key.put(Keys.描述_效果重置卡,"Wenn Sie die Karte benutzen, können Sie die Vergabe-Weise von Ihre Dream Kombination nach eigenen Wünschen einstellen.");
		key.put(Keys.描述_声望卷, "Mondkuchen Stand für Familientreffen und Alles Gute! Wenn Ihre Familie um einen Tisch sitzen, Mondkuchen essen. Was für eine glückliche Sache.");
		key.put(Keys.描述_电玩大礼包, "Durch Online games Biweekly können Sie das Paket erhalten. Darin gibt es Rückruf von Scountsx1,Sportgetränke(klein)x2, Sportgetränke(mittel)x2,Kredit Kartex1.");
		key.put(Keys.描述_新春礼包, "在2012/2/22-2012/3/18期间，使用MyCard線上支付一次性储值达到一定额度，可获取该礼包。");
		key.put(Keys.描述_新春大礼包, "在2012/2/22-2012/3/18期间，使用MyCard線上支付一次性储值达到一定额度，可获取该礼包。");
		key.put(Keys.描述_劳动节贺卡, "五一国际劳动节是全世界劳动人民的节日！收集足够的劳动节贺卡，可以换取丰厚奖励。");
		key.put(Keys.描述_抽奖道具, "五一国际劳动节是全世界劳动人民的节日！使用抽奖券，可进行抽奖，赢取丰厚奖励。");

		key.put(Keys.描述_知己知彼,"<font color='#00b42a'>Talent Taktik Durchsehen funktioniert. Ihrer Gegner hat Taktik %A benutzt</font>");
		key.put(Keys.描述_机敏,"Talent Findig funktioniert. Sie haben von die Einfluss aus %A von Gegner vermeiden");
		key.put(Keys.描述_士气大振,"Talent Ermunterung funktioniert. Ihre Mannschaft bekommen 10 Punkte Ermunterung");
		key.put(Keys.描述_体力充盈,"Talent Kraftvoll funktioniert. Wenn %A mit %B mitspielen, es hat kein Kraft verbraucht");
		key.put(Keys.描述_抛砖引玉,"<font color='#00b42a'>Talent bessere Idee funktioniert. Ihre Spieler bringt die Gegner einen Faul, und hat ein Korbwurf Chance bekommen</font>");
		key.put(Keys.描述_怒吼,"Talent Brausen funktioniert. Kraft von Spieler deines Gegner senkt sich um 1 Punkt");
		key.put(Keys.描述_终极绝杀,"Talent Finale Treffen funktioniert. Sie haben den letzen Korbwurf getroffen");
		key.put(Keys.描述_薄利多销,"Talent hoher Umsatz bei geringer Gewinnspanne Funktioniert. Sie haben einen 10% rabatt bekommen, wenn Sie %A kaufen");
		key.put(Keys.描述_战术大师,"Talent von Meister der Taktiken funktioniert. Sie haben %A Punkt Geschicktheit der Taktik gewinnen");
		key.put(Keys.描述_地位尊崇,"Talent von eine ehrende Position funktioniert. Sie haben %A Punkt Ruf erhalten");
		key.put(Keys.描述_慕名而来,"Talent von herkommen wegen Ihres bekannten Namen funktioniert. Sie haben für %A %B weniger bezahlt");
		key.put(Keys.描述_鼓舞,"Talent von Ermunterung funktioniert. Kraft von allen Spielern im Spiel haben sich um 1 Punkt erhöht");
		key.put(Keys.描述_反客为主,"Talent von vom Gast zu Gastgeber werden funktioniert. Wenn Sie an das NBA-Spiel teilnehmen, braucht es %A nicht zu verbrauchen");
		key.put(Keys.描述_自由买卖,"Talent von Freihandel funktioniert. Wenn Sie ihren Spieler in Frei-Handel-Zone verkaufen, haben es keine Erlaubnis-Karte verbraucht.");
		key.put(Keys.描述_伤病无忧,"Talent von keine Sorge um Verletzung funktioniert. Wenn Sie die verletzte Spieler %A feuert, werden Sie die Gesamtsumme von Marktpreis bekommen");
		key.put(Keys.描述_完美搭档,"Talent von ausgeteichnete Gruppenpartner funktioniert. Wenn Sie %A feuern, werden die Geschicktheit nicht gesenkt");
		key.put(Keys.描述_生龙活虎,"Talent von energievoll und sportlich funktioniert. wenn Sie den Spieler %A mit nicht voller Kraft, werden Sie auch die Gesamtsumme von Marktpreis bekommen");
		key.put(Keys.描述_常胜将军,"Talent von unbesiegbarer General funktioniert. Verlor dieses mal wird nicht auf den Record berechnet");
		key.put(Keys.描述_超级底薪,"Talent von super niedriger Gehalt funktioniert. Wenn Sie mit %A unterzeichnen, haben sich der Lohn um %B senkt");


		key.put(Keys.球队_公牛,"Bulls");
		key.put(Keys.球队_马刺,"Spurs");
		key.put(Keys.球队_灰熊,"Grizzlies");
		key.put(Keys.球队_快船,"Clippers");
		key.put(Keys.球队_湖人,"Lakers");
		key.put(Keys.球队_国王,"Kings");
		key.put(Keys.球队_热火,"Heat");
		key.put(Keys.球队_魔术,"Magic");
		key.put(Keys.球队_尼克斯,"Knicks");
		key.put(Keys.球队_雄鹿,"Bucks");
		key.put(Keys.球队_火箭,"Rockets");
		key.put(Keys.球队_勇士,"Warriors");
		key.put(Keys.球队_老鹰,"Hawks");
		key.put(Keys.球队_凯尔特人,"Celtics");
		key.put(Keys.球队_奇才,"Wizards");
		key.put(Keys.球队_黄蜂,"Bobcats");
		key.put(Keys.球队_活塞,"Pistons");
		key.put(Keys.球队_步行者,"Pacers");
		key.put(Keys.球队_骑士,"Cavaliers");
		key.put(Keys.球队_76人,"76ers");
		key.put(Keys.球队_小牛,"Mavericks");
		key.put(Keys.球队_鹈鹕,"Hornets");
		key.put(Keys.球队_太阳,"Suns");
		key.put(Keys.球队_森林狼,"Timberwolves");
		key.put(Keys.球队_开拓者,"Trail Blazers");
		key.put(Keys.球队_雷霆,"Thunder");
		key.put(Keys.球队_爵士,"Jazz");
		key.put(Keys.球队_篮网,"Brooklyn");
		key.put(Keys.球队_猛龙,"Raptors");
		key.put(Keys.球队_掘金,"Nuggets");
		key.put(Keys.球队_西部全明星,"Western all star");
		key.put(Keys.球队_东部全明星,"Easten all star");
		key.put(Keys.球队_巅峰全明星,"All star");
		key.put(Keys.球队_梦一队,"Dream Team 1");
		key.put(Keys.球队_梦二队,"Dream Team 2");
		key.put(Keys.球队_梦三队,"Dream Team 3");
		key.put(Keys.球队_梦四队,"Dream Team 4");
		key.put(Keys.球队_梦五队,"Dream Team 5");
		key.put(Keys.球队_梦六队,"Dream Team 6");
		key.put(Keys.球队_梦七队,"Dream Team 7");
		key.put(Keys.球队_梦八队,"Dream Team 8");
		key.put(Keys.球队_梦九队,"Dream Team 9");
		key.put(Keys.球队_梦之队,"Dream Team");
		key.put(Keys.球队_小试牛刀, "Probe");
		key.put(Keys.球队_为了胜利, "für Sieg");
		key.put(Keys.球队_新秀的考验, "Test für Newcomer");
		key.put(Keys.球队_强者如林, "Die echte Stärke");
		key.put(Keys.球队_联赛总冠军, "Miami");
		key.put(Keys.球队_名人堂元老队, "名人堂元老隊");
		key.put(Keys.球队_公牛2,"公牛");
		key.put(Keys.球队_马刺2,"马刺");
		key.put(Keys.球队_灰熊2,"灰熊");
		key.put(Keys.球队_快船2,"快船");
		key.put(Keys.球队_湖人2,"湖人");
		key.put(Keys.球队_国王2,"国王");
		key.put(Keys.球队_热火2,"热火");
		key.put(Keys.球队_魔术2,"魔术");
		key.put(Keys.球队_尼克斯2,"尼克斯");
		key.put(Keys.球队_雄鹿2,"雄鹿");
		key.put(Keys.球队_火箭2,"火箭");
		key.put(Keys.球队_勇士2,"勇士");
		key.put(Keys.球队_老鹰2,"老鹰");
		key.put(Keys.球队_凯尔特人2,"凯尔特人");
		key.put(Keys.球队_奇才2,"奇才");
		key.put(Keys.球队_山猫2,"山猫");
		key.put(Keys.球队_活塞2,"活塞");
		key.put(Keys.球队_步行者2,"步行者");
		key.put(Keys.球队_骑士2,"骑士");
		key.put(Keys.球队_76人2,"76人");
		key.put(Keys.球队_小牛2,"小牛");
		key.put(Keys.球队_黄蜂2,"黄蜂");
		key.put(Keys.球队_太阳2,"太阳");
		key.put(Keys.球队_森林狼2,"森林狼");
		key.put(Keys.球队_开拓者2,"开拓者");
		key.put(Keys.球队_雷霆2,"雷霆");
		key.put(Keys.球队_爵士2,"爵士");
		key.put(Keys.球队_篮网2,"篮网");
		key.put(Keys.球队_猛龙2,"猛龙");
		key.put(Keys.球队_掘金2,"掘金");
		key.put(Keys.球队_年代明星队60, "60年代明星队");
		key.put(Keys.球队_年代明星队70, "70年代明星队");
		key.put(Keys.球队_年代明星队80, "80年代明星队");
		key.put(Keys.球队_年代明星队90, "90年代明星队");
		key.put(Keys.球队_年代明星队2000, "2000年代明星队");

		key.put(Keys.团体赛_超快赛免费赢奖励,"schneller Kampf um Belohnung");
		key.put(Keys.团体赛_火热对战赛,"feurige Konfrontation（{1}）");
		key.put(Keys.团体赛_超快火热对战赛,"feurige Konfrontation（{1}）");
		key.put(Keys.团体赛_激情球券对战赛,"Konfrontation mit（{1} Geld）");
		key.put(Keys.团体赛_整点对战赛,"Kampf um X:00 Uhr （{1}）");
		key.put(Keys.团体赛_比赛赢取极品装备,"Kampf um beste Ausrüstung");
		key.put(Keys.团体赛_比赛赢取超级底薪巨星,"um Superstar mit MinimumLohn");
		key.put(Keys.团体赛_实物大奖免费送,"Spiel um kostenlose Geschenke");
		key.put(Keys.团体赛_Q币大放送,"Kampf um QQ-Währung");
		key.put(Keys.团体赛_每日送球券,"Kampf um Geld");
		key.put(Keys.团体赛_iphone手机大奖赛,"Kampf um Iphone");
		key.put(Keys.团体赛_周末酬谢大奖赛,"Kampf am Wochenende");
		key.put(Keys.团体赛_急速免费赛,"schneller und kostenloses Spiel");
		key.put(Keys.团体赛_强化石大赠送, "Kampf um Verstärkungsstein");

		key.put(Keys.广播_杯赛夺冠, "恭喜“{1}”在{2}中勇夺冠军，让我们为他欢呼吧！");
		key.put(Keys.广播_战胜梦之队, "“{1}”运筹帷幄，调兵遣将，经过一番激烈的战斗，竟然战胜了史上无敌的梦之队！");
		key.put(Keys.广播_周末大奖赛, "恭喜“{1}”在{2}中勇夺冠军！");
		key.put(Keys.广播_底薪巨星赛, "恭喜“{1}”在{2}中勇夺冠军！");
		key.put(Keys.广播_服务器50第一, "恭喜“{1}”成为服务器第一位满级玩家，成就急速巅峰！");
		key.put(Keys.广播_最高级别的球馆争霸赛, "“{1}”联盟团结一心，战胜强敌，成功占领舰队中心球队！");
		key.put(Keys.广播_挑战极限, "“{1}”战胜巅峰全明星队，成功挑战极限，获得了丰厚的奖励。");
		key.put(Keys.广播_节日送祝福, "“{1}”為他的朋友“{2}”送出一份最美麗的祝福：{3}");
		key.put(Keys.广播_申请书奖励得主, "“{1}”为竞技大赛提交申请书，竟然获得了{2}的奖励！");
		key.put(Keys.广播_等级达到50级, "“{1}”坚持不懈，终于成功升到{2}级！");
		key.put(Keys.广播_抽奖活动, "“{1}”在抽奖活动中幸运的获得了{2}的奖励，真是人品爆发！");
		key.put(Keys.广播_获得底薪球员, "“{1}”使用底薪球星卡，居然得到了底薪{2}，真让人羡慕嫉妒恨！");
		key.put(Keys.广播_答题活动第一, "恭喜“{1}”在幸運答題活動中展現了超群學識，以冠軍的身份獲得本次‘活動達人’稱號！");
		key.put(Keys.广播_完成粽动员, "恭喜“{1}”在端午‘粽’动员活动中通过不懈的努力达成了全部任务，获得了最终大奖—{2}一件！");
		key.put(Keys.广播_万圣节开启太妃糖, "{1}真是好运，参与万圣节活动时居然获得了“{2}”的奖励，惹来无数羡慕的目光！");
		key.put(Keys.广播_在线礼包, "{1}运气真好，打开脱光礼包居然获得了“{2}”的奖励，真是羡煞旁人啊！");

		key.put(Keys.私聊_节日送祝福, "亲爱的“{1}”，我是你最好的朋友“{2}”，在这美好的节日中，我祝福你：{3}");

		key.put(Keys.比赛_18_1, "Meine Damen und Herren, Herzlich willkommen bei uns. Heute Abend wird eine sehr heftige Konfrontation präsentiert. Ok, das Spiel beginnt. Durch Sprung hat {#teamname} das Ball erhalten.Verteidiger organisiert den ersten Angriff ruhrig");
		key.put(Keys.比赛_18_2, "Noch ein feurige Wettkampf beginnt. Genießen wir jetzt die Kampf zwischen Körper und Seele. Das ist der Reiz von Basketball. Nach einige Sprung von Mittelstürmer aus beiden Seite, erhalten {#teamname} endlich das Ball");
		key.put(Keys.比赛_18_3, "Arbeiter in dem Spielfeld hat die Stimmung von dem Spiel aufgeweckt. Spieler aus beiden Seite haben sich auch schon vorbreitet. Nach heftige Kampf, erhalten {#teamname} den Ball");
		key.put(Keys.比赛_18_4, "Welche Mannschaft wird der König von dieser Sasion? Wir werden es sehen.Mittelstürmer aus {#teamname} hat den Ball an seine Kollege erfolgreich gepasst");
		key.put(Keys.比赛_18_5, "Das Spiel ist noch nicht begonnen. Aber die Zuschauer sind schon sehr gefeuert. Manche Zuschauer aus Hause hat die Gäste provoziert.Mit der Hause-Stärke beginnt {#teamname} ihren Angriff");
		key.put(Keys.比赛_18_6, "Spieler aus beiden Seite beginnen, in den Spielplatz einzutretten. Ihre Trainier gehen um den Schiedsrichter. Überall ist voller Wettkampf. Ok, sei ernst. Lassen unsere Augen in den Spielsfeld. Schiedsrichter hat offensichtlich unlauter gemacht.{#teamname} hat den Ball sehr leicht bekommen");
		key.put(Keys.比赛_18_7, "Schiedsrichter wirft das Ball sehr hoch. Lange kann man den nicht gesehen. Achso, der Ball sind schon von Mittelstürmer aus {#teamname} an seinen Kollegen gepasst. Der erste Angriff ist schon begonnen");
		key.put(Keys.比赛_18_8, "Wenn der Gegener noch nichts tut, sind die Mittelstürmer aus {#teamname} schon sehr hoch gesprungen. Und das Ball fließt an seine Kollegen");

		key.put(Keys.比赛_19_1, "Der erste Abschnitt endet. Schöne Mädchen beginnt ihre Aufführung. Was? Es war aber Kurz. Jetzt beginnt der Zweite Abschnitt");
		key.put(Keys.比赛_19_2, "Der erste Abschnitt endet. Saufen, ins WC gehen...Jetzt beginnt der zweite Abschnitt");
		key.put(Keys.比赛_19_3, "Der erste Abschnitt endet.Wir können uns fühlen, die beide Seite haben schon ihre Bestes geben, um eine gute Start haben. Nach Kurz Pause beginnt der zweite Abschnitt");
		key.put(Keys.比赛_19_4, "Der erste Abschnitt endet schon. Aber die Atmosphäre ist ein bisschen Spanend. Ok, jetzt beginnt der zweite Abschnitt");
		key.put(Keys.比赛_19_5, "Wir haben einen perfekte Abschnitt schon geschaut. Wir Glauben, anschließend wird es viel besser");
		key.put(Keys.比赛_19_6, "Die beiden Seite haben uns Dunking-Show in ersten Abschnitt gebracht. Hoffe, es wird heftiger. Jetzt beginnt der zweite Abschnitt");
		key.put(Keys.比赛_19_7, "Die beiden Seite haben in den ersten Abschnitt konservativ gespielt. Immer Verteigigung. Hoffe, in kommenden Abschnitt, mehr Angriff");
		key.put(Keys.比赛_19_8, "Der ersten Abschnitt endet, die beiden Seite haben sehr heftig gespielt. Es scheint so, beide Seit möchte durch ersten Abschnitt Ihren Gegner besiegen. Aber die Zuschauer möchte gar nicht, folgende Zeit lebloses Spiel zu sehen");

		key.put(Keys.比赛_20_1, "der Zweite Abschnitt endet. Machen wir eine kurze Pause. Nächster Abschnitt ist erwartet");
		key.put(Keys.比赛_20_2, "der Zweite Abschnitt endet. Die Spieler ruhen sich aus. Trainier haben die Taktik gewechselt. Nach einer kurzer Pause beginnt der dritte Anschnitt");
		key.put(Keys.比赛_20_3, "Jetzt ruhen sich die Spieler in der Halbzeit aus. Hoffe, nach kurze pause wird einen schönere Spiel präsentiert");
		key.put(Keys.比赛_20_4, "Nach kurzer Pause wird der dritte Abschnitt bald beginnen");
		key.put(Keys.比赛_20_5, "Wer lacht am Ende, Lacht am Besten. Die erste Halbzeit ist sehr wunderschön. Hoffe, die nächste Halbzeit wird schöner. Jetzt haben wir den dritten Abschnitt");
		key.put(Keys.比赛_20_6, "Wir haben in den zweiten Abschnitt hochkarätige Wettkampf geschaut. Lassen uns jetzt in den dritte Abschnitt");
		key.put(Keys.比赛_20_7, "der zweite Abschnitt beendet. Plötzlich Sprung Klamauk aus Zuschauer. Achso, Cheerleader schenken den Zuschauern etwas. Im gegensatz zu Star-Spieler, es schein so, sie sind mehr begrüßt. Lassen uns jetzt in den dritte Abschnitt");
		key.put(Keys.比赛_20_8, "Jetzt ist Ruhezeit. Spiel ist schön, Slogan und Bekleidung von Zuschauer haben leute auch angezogen. Lassen unsere Augen wieder in den Spielfeld. Jetzt beginnt der zweite Halbzeit");

		key.put(Keys.比赛_21_1, "Der dritte Abschnitt endet. Beide Seite wird in den letzten Abschnitt eintreten. Wer wird die andere besiegen. Lass uns schauen");
		key.put(Keys.比赛_21_2, "Der dritte Abschnitt endet. Es gibt kein große Differenz zwischen der beiden Mannschaft. Letzte Abschnitt, letzte Kampf. Gib gas");
		key.put(Keys.比赛_21_3, "Der dritte Abschnitt endet, aber der vierte Abschnitt kommt schon");
		key.put(Keys.比赛_21_4, "Obwohl Freundschaft ist wichtiger als Wettkampf selbst, aber jede Mannschaft möchte Winner sein. Der vierte Abschnitt ist schon begonnen. Lassen uns sehen, wer der Winner ist");
		key.put(Keys.比赛_21_5, "Nee, Nee...es ist das Spiel von Glorie, wir können es nicht verloren");
		key.put(Keys.比赛_21_6, "Obwohl die Spiepler Kraftlos ist, aber die Kann ihrer Trieb nach Punkt nicht behindern");
		key.put(Keys.比赛_21_7, "Wärend Pause haben die Trainier Spieler um sich, sagen ihnen, was soll tun in den letzten Abschnitt. Nun kommt das vierte Abschnitt");

		key.put(Keys.比赛_22_1, "Beharrliche Spieler. Die beiden haben gleiche Punkt bekommt. Jetzt kommt die Verlängerung");
		key.put(Keys.比赛_22_2, "Nach ende der regulären Spielzeit gibt es keine Sieger. Hier kommt die erste Verlängerung");
		key.put(Keys.比赛_22_3, "Die beiden Seite haben sich gleich entfaltet. Der vierte Abschnitt schließt mit gleichen Punkt. Jetzt ist die erste Verlängerung");
		key.put(Keys.比赛_22_4, "Jetzt kommt die erste Verlängerung");
		key.put(Keys.比赛_22_5, "oh, Gott, das Spiel ist so heftig. Jetzt kommt die erste Verlängerung");
		key.put(Keys.比赛_22_6, "Nach vierte Abschnitt sind die Spieler von beiden Seite fast erschöpft. Aber sie müssen die Verlängerung weiter Spielen");
		key.put(Keys.比赛_22_7, "Jetzt ist die Verlängerung. Aber manche Zuschauer kommen nur vor Minute");

		key.put(Keys.比赛_23_1, "Unglaublich, jetzt kommt die zweite Verlängerung");
		key.put(Keys.比赛_23_2, "Gibt es Spiele, die Heftiger als dieser Mal. Hier beginnt die zweite Verlängerung");
		key.put(Keys.比赛_23_3, "Nichts zu Sagen. Nun beginnt die zweite Verlängerung");
		key.put(Keys.比赛_23_4, "Die Kraft von allen Spieler gehen fast aus. Ohne Pause kommt die zweite Verlängerung. Welche mit stärker Wille,wird das Spiel gewinnen");
		key.put(Keys.比赛_23_5, "Noch Mal gleiche Punkt. Das Spiel soll vom Beginn an Verlängerung heißen");
		key.put(Keys.比赛_23_6, "Die Zweite Verlängerung ist unvermeidbar. Spieler und Trainer weint, aber die Zuschauer lacht. Das Geld locht sich");

		key.put(Keys.比赛_24_1, "Endlich kommt das Spiel zum Ende.{#winname} besiegt {#lossname} mit {#score}. Kongratuliere, {#winname} hat das Spiel gewinnen. Wünsche {#lossname} in den nächsten Spiel ein bessere Ergibnis");
		key.put(Keys.比赛_24_2, "Endlich kommt das Spiel zum Schluss. {#winname} besiegt {#lossname} mit {#score}. Was für ein wunderschönes Spiel");
		key.put(Keys.比赛_24_3, "Endlich hat {#winname} das Spiel gewinnen.Beide Spieler schüttelten miteinander die Hände.  Kongratuliere, {#winname} hat das Spiel gewinnen. Wünsche {#lossname} in den nächsten Spiel ein bessere Ergibnis");
		key.put(Keys.比赛_24_4, "Zuschauer Jubeln. Spieler verlieren die Stadion. {#winname}hat mit {#score}{#lossname} besiegt");
		key.put(Keys.比赛_24_5, "Endlich kommt das Spiel zum Ende.{#winname} besiegt {#lossname} mit {#score}. Es scheint so,{#winname}entfalt sich besser");
		key.put(Keys.比赛_24_6, "Endlich kommt das Spiel zum Ende.{#winname} besiegt {#lossname} mit {#score}. {#lossname} kann dieser Tunier nicht weiter Spielen");
		key.put(Keys.比赛_24_7, "Endlich kommt das Spiel zum Ende.{#winname} besiegt {#lossname} mit {#score}, sagt die Anderen, wer ist der richtige Stärker. Es gibt immer Stoßen auf dem Weg zu König");
		key.put(Keys.比赛_24_8, "Endlich kommt das Spiel zum Ende.{#winname} besiegt {#lossname} mit {#score}. Beide Seite haben sich sehr fleißig gespielt. Das SPiel ist sehr wunderschön. Hoffe, nächst Mal wird er mehr wunderschön");
		key.put(Keys.比赛_24_9, "Endlich kommt das Spiel zum Ende. Spieler aus {#winname}jubelt für seine Erfolg. Obwohl {#lossname} das Spiel nicht gewinnen, die Spieler haben aber schon sein Bestens geben");
		**/
	}

	public static void main(String[] args){
		TreeMap<Integer,Integer> tree = new TreeMap<Integer,Integer>();
		Iterator<Integer> it = key.keySet().iterator();
		while(it.hasNext()){
			tree.put(it.next(), 1);
		}
		it = tree.keySet().iterator();
		while(it.hasNext()){
			System.out.println(it.next());
		}
	}

}
