// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AtvCardAward.proto

package com.ftkj.proto;

public final class AtvCardAwardPB {
  private AtvCardAwardPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AtvCardAwardDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .com.ftkj.proto.AtvCardData atvList = 1;
    java.util.List<com.ftkj.proto.AtvCardAwardPB.AtvCardData> 
        getAtvListList();
    com.ftkj.proto.AtvCardAwardPB.AtvCardData getAtvList(int index);
    int getAtvListCount();
    java.util.List<? extends com.ftkj.proto.AtvCardAwardPB.AtvCardDataOrBuilder> 
        getAtvListOrBuilderList();
    com.ftkj.proto.AtvCardAwardPB.AtvCardDataOrBuilder getAtvListOrBuilder(
        int index);
  }
  public static final class AtvCardAwardData extends
      com.google.protobuf.GeneratedMessage
      implements AtvCardAwardDataOrBuilder {
    // Use AtvCardAwardData.newBuilder() to construct.
    private AtvCardAwardData(Builder builder) {
      super(builder);
    }
    private AtvCardAwardData(boolean noInit) {}
    
    private static final AtvCardAwardData defaultInstance;
    public static AtvCardAwardData getDefaultInstance() {
      return defaultInstance;
    }
    
    public AtvCardAwardData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ftkj.proto.AtvCardAwardPB.internal_static_com_ftkj_proto_AtvCardAwardData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ftkj.proto.AtvCardAwardPB.internal_static_com_ftkj_proto_AtvCardAwardData_fieldAccessorTable;
    }
    
    // repeated .com.ftkj.proto.AtvCardData atvList = 1;
    public static final int ATVLIST_FIELD_NUMBER = 1;
    private java.util.List<com.ftkj.proto.AtvCardAwardPB.AtvCardData> atvList_;
    public java.util.List<com.ftkj.proto.AtvCardAwardPB.AtvCardData> getAtvListList() {
      return atvList_;
    }
    public java.util.List<? extends com.ftkj.proto.AtvCardAwardPB.AtvCardDataOrBuilder> 
        getAtvListOrBuilderList() {
      return atvList_;
    }
    public int getAtvListCount() {
      return atvList_.size();
    }
    public com.ftkj.proto.AtvCardAwardPB.AtvCardData getAtvList(int index) {
      return atvList_.get(index);
    }
    public com.ftkj.proto.AtvCardAwardPB.AtvCardDataOrBuilder getAtvListOrBuilder(
        int index) {
      return atvList_.get(index);
    }
    
    private void initFields() {
      atvList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getAtvListCount(); i++) {
        if (!getAtvList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < atvList_.size(); i++) {
        output.writeMessage(1, atvList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < atvList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, atvList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ftkj.proto.AtvCardAwardPB.AtvCardAwardDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ftkj.proto.AtvCardAwardPB.internal_static_com_ftkj_proto_AtvCardAwardData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ftkj.proto.AtvCardAwardPB.internal_static_com_ftkj_proto_AtvCardAwardData_fieldAccessorTable;
      }
      
      // Construct using com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAtvListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (atvListBuilder_ == null) {
          atvList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          atvListBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData.getDescriptor();
      }
      
      public com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData getDefaultInstanceForType() {
        return com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData.getDefaultInstance();
      }
      
      public com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData build() {
        com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData buildPartial() {
        com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData result = new com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData(this);
        int from_bitField0_ = bitField0_;
        if (atvListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            atvList_ = java.util.Collections.unmodifiableList(atvList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.atvList_ = atvList_;
        } else {
          result.atvList_ = atvListBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData) {
          return mergeFrom((com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData other) {
        if (other == com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData.getDefaultInstance()) return this;
        if (atvListBuilder_ == null) {
          if (!other.atvList_.isEmpty()) {
            if (atvList_.isEmpty()) {
              atvList_ = other.atvList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAtvListIsMutable();
              atvList_.addAll(other.atvList_);
            }
            onChanged();
          }
        } else {
          if (!other.atvList_.isEmpty()) {
            if (atvListBuilder_.isEmpty()) {
              atvListBuilder_.dispose();
              atvListBuilder_ = null;
              atvList_ = other.atvList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              atvListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAtvListFieldBuilder() : null;
            } else {
              atvListBuilder_.addAllMessages(other.atvList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getAtvListCount(); i++) {
          if (!getAtvList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.ftkj.proto.AtvCardAwardPB.AtvCardData.Builder subBuilder = com.ftkj.proto.AtvCardAwardPB.AtvCardData.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAtvList(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .com.ftkj.proto.AtvCardData atvList = 1;
      private java.util.List<com.ftkj.proto.AtvCardAwardPB.AtvCardData> atvList_ =
        java.util.Collections.emptyList();
      private void ensureAtvListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          atvList_ = new java.util.ArrayList<com.ftkj.proto.AtvCardAwardPB.AtvCardData>(atvList_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ftkj.proto.AtvCardAwardPB.AtvCardData, com.ftkj.proto.AtvCardAwardPB.AtvCardData.Builder, com.ftkj.proto.AtvCardAwardPB.AtvCardDataOrBuilder> atvListBuilder_;
      
      public java.util.List<com.ftkj.proto.AtvCardAwardPB.AtvCardData> getAtvListList() {
        if (atvListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(atvList_);
        } else {
          return atvListBuilder_.getMessageList();
        }
      }
      public int getAtvListCount() {
        if (atvListBuilder_ == null) {
          return atvList_.size();
        } else {
          return atvListBuilder_.getCount();
        }
      }
      public com.ftkj.proto.AtvCardAwardPB.AtvCardData getAtvList(int index) {
        if (atvListBuilder_ == null) {
          return atvList_.get(index);
        } else {
          return atvListBuilder_.getMessage(index);
        }
      }
      public Builder setAtvList(
          int index, com.ftkj.proto.AtvCardAwardPB.AtvCardData value) {
        if (atvListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAtvListIsMutable();
          atvList_.set(index, value);
          onChanged();
        } else {
          atvListBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setAtvList(
          int index, com.ftkj.proto.AtvCardAwardPB.AtvCardData.Builder builderForValue) {
        if (atvListBuilder_ == null) {
          ensureAtvListIsMutable();
          atvList_.set(index, builderForValue.build());
          onChanged();
        } else {
          atvListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAtvList(com.ftkj.proto.AtvCardAwardPB.AtvCardData value) {
        if (atvListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAtvListIsMutable();
          atvList_.add(value);
          onChanged();
        } else {
          atvListBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addAtvList(
          int index, com.ftkj.proto.AtvCardAwardPB.AtvCardData value) {
        if (atvListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAtvListIsMutable();
          atvList_.add(index, value);
          onChanged();
        } else {
          atvListBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addAtvList(
          com.ftkj.proto.AtvCardAwardPB.AtvCardData.Builder builderForValue) {
        if (atvListBuilder_ == null) {
          ensureAtvListIsMutable();
          atvList_.add(builderForValue.build());
          onChanged();
        } else {
          atvListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addAtvList(
          int index, com.ftkj.proto.AtvCardAwardPB.AtvCardData.Builder builderForValue) {
        if (atvListBuilder_ == null) {
          ensureAtvListIsMutable();
          atvList_.add(index, builderForValue.build());
          onChanged();
        } else {
          atvListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllAtvList(
          java.lang.Iterable<? extends com.ftkj.proto.AtvCardAwardPB.AtvCardData> values) {
        if (atvListBuilder_ == null) {
          ensureAtvListIsMutable();
          super.addAll(values, atvList_);
          onChanged();
        } else {
          atvListBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearAtvList() {
        if (atvListBuilder_ == null) {
          atvList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          atvListBuilder_.clear();
        }
        return this;
      }
      public Builder removeAtvList(int index) {
        if (atvListBuilder_ == null) {
          ensureAtvListIsMutable();
          atvList_.remove(index);
          onChanged();
        } else {
          atvListBuilder_.remove(index);
        }
        return this;
      }
      public com.ftkj.proto.AtvCardAwardPB.AtvCardData.Builder getAtvListBuilder(
          int index) {
        return getAtvListFieldBuilder().getBuilder(index);
      }
      public com.ftkj.proto.AtvCardAwardPB.AtvCardDataOrBuilder getAtvListOrBuilder(
          int index) {
        if (atvListBuilder_ == null) {
          return atvList_.get(index);  } else {
          return atvListBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.ftkj.proto.AtvCardAwardPB.AtvCardDataOrBuilder> 
           getAtvListOrBuilderList() {
        if (atvListBuilder_ != null) {
          return atvListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(atvList_);
        }
      }
      public com.ftkj.proto.AtvCardAwardPB.AtvCardData.Builder addAtvListBuilder() {
        return getAtvListFieldBuilder().addBuilder(
            com.ftkj.proto.AtvCardAwardPB.AtvCardData.getDefaultInstance());
      }
      public com.ftkj.proto.AtvCardAwardPB.AtvCardData.Builder addAtvListBuilder(
          int index) {
        return getAtvListFieldBuilder().addBuilder(
            index, com.ftkj.proto.AtvCardAwardPB.AtvCardData.getDefaultInstance());
      }
      public java.util.List<com.ftkj.proto.AtvCardAwardPB.AtvCardData.Builder> 
           getAtvListBuilderList() {
        return getAtvListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ftkj.proto.AtvCardAwardPB.AtvCardData, com.ftkj.proto.AtvCardAwardPB.AtvCardData.Builder, com.ftkj.proto.AtvCardAwardPB.AtvCardDataOrBuilder> 
          getAtvListFieldBuilder() {
        if (atvListBuilder_ == null) {
          atvListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.ftkj.proto.AtvCardAwardPB.AtvCardData, com.ftkj.proto.AtvCardAwardPB.AtvCardData.Builder, com.ftkj.proto.AtvCardAwardPB.AtvCardDataOrBuilder>(
                  atvList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          atvList_ = null;
        }
        return atvListBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.ftkj.proto.AtvCardAwardData)
    }
    
    static {
      defaultInstance = new AtvCardAwardData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ftkj.proto.AtvCardAwardData)
  }
  
  public interface AtvCardDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 atvId = 1;
    boolean hasAtvId();
    int getAtvId();
    
    // required int32 status = 2;
    boolean hasStatus();
    int getStatus();
    
    // required int32 days = 3;
    boolean hasDays();
    int getDays();
    
    // required bool buy = 4;
    boolean hasBuy();
    boolean getBuy();
  }
  public static final class AtvCardData extends
      com.google.protobuf.GeneratedMessage
      implements AtvCardDataOrBuilder {
    // Use AtvCardData.newBuilder() to construct.
    private AtvCardData(Builder builder) {
      super(builder);
    }
    private AtvCardData(boolean noInit) {}
    
    private static final AtvCardData defaultInstance;
    public static AtvCardData getDefaultInstance() {
      return defaultInstance;
    }
    
    public AtvCardData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ftkj.proto.AtvCardAwardPB.internal_static_com_ftkj_proto_AtvCardData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ftkj.proto.AtvCardAwardPB.internal_static_com_ftkj_proto_AtvCardData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 atvId = 1;
    public static final int ATVID_FIELD_NUMBER = 1;
    private int atvId_;
    public boolean hasAtvId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getAtvId() {
      return atvId_;
    }
    
    // required int32 status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getStatus() {
      return status_;
    }
    
    // required int32 days = 3;
    public static final int DAYS_FIELD_NUMBER = 3;
    private int days_;
    public boolean hasDays() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getDays() {
      return days_;
    }
    
    // required bool buy = 4;
    public static final int BUY_FIELD_NUMBER = 4;
    private boolean buy_;
    public boolean hasBuy() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public boolean getBuy() {
      return buy_;
    }
    
    private void initFields() {
      atvId_ = 0;
      status_ = 0;
      days_ = 0;
      buy_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasAtvId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDays()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBuy()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, atvId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, status_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, days_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, buy_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, atvId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, status_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, days_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, buy_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.ftkj.proto.AtvCardAwardPB.AtvCardData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.AtvCardAwardPB.AtvCardData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.AtvCardAwardPB.AtvCardData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.AtvCardAwardPB.AtvCardData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.AtvCardAwardPB.AtvCardData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.AtvCardAwardPB.AtvCardData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.AtvCardAwardPB.AtvCardData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.AtvCardAwardPB.AtvCardData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.AtvCardAwardPB.AtvCardData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.AtvCardAwardPB.AtvCardData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ftkj.proto.AtvCardAwardPB.AtvCardData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ftkj.proto.AtvCardAwardPB.AtvCardDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ftkj.proto.AtvCardAwardPB.internal_static_com_ftkj_proto_AtvCardData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ftkj.proto.AtvCardAwardPB.internal_static_com_ftkj_proto_AtvCardData_fieldAccessorTable;
      }
      
      // Construct using com.ftkj.proto.AtvCardAwardPB.AtvCardData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        atvId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        days_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        buy_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ftkj.proto.AtvCardAwardPB.AtvCardData.getDescriptor();
      }
      
      public com.ftkj.proto.AtvCardAwardPB.AtvCardData getDefaultInstanceForType() {
        return com.ftkj.proto.AtvCardAwardPB.AtvCardData.getDefaultInstance();
      }
      
      public com.ftkj.proto.AtvCardAwardPB.AtvCardData build() {
        com.ftkj.proto.AtvCardAwardPB.AtvCardData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.ftkj.proto.AtvCardAwardPB.AtvCardData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.ftkj.proto.AtvCardAwardPB.AtvCardData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.ftkj.proto.AtvCardAwardPB.AtvCardData buildPartial() {
        com.ftkj.proto.AtvCardAwardPB.AtvCardData result = new com.ftkj.proto.AtvCardAwardPB.AtvCardData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.atvId_ = atvId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.days_ = days_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.buy_ = buy_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ftkj.proto.AtvCardAwardPB.AtvCardData) {
          return mergeFrom((com.ftkj.proto.AtvCardAwardPB.AtvCardData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.ftkj.proto.AtvCardAwardPB.AtvCardData other) {
        if (other == com.ftkj.proto.AtvCardAwardPB.AtvCardData.getDefaultInstance()) return this;
        if (other.hasAtvId()) {
          setAtvId(other.getAtvId());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasDays()) {
          setDays(other.getDays());
        }
        if (other.hasBuy()) {
          setBuy(other.getBuy());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasAtvId()) {
          
          return false;
        }
        if (!hasStatus()) {
          
          return false;
        }
        if (!hasDays()) {
          
          return false;
        }
        if (!hasBuy()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              atvId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              status_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              days_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              buy_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 atvId = 1;
      private int atvId_ ;
      public boolean hasAtvId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getAtvId() {
        return atvId_;
      }
      public Builder setAtvId(int value) {
        bitField0_ |= 0x00000001;
        atvId_ = value;
        onChanged();
        return this;
      }
      public Builder clearAtvId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        atvId_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 status = 2;
      private int status_ ;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getStatus() {
        return status_;
      }
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 days = 3;
      private int days_ ;
      public boolean hasDays() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getDays() {
        return days_;
      }
      public Builder setDays(int value) {
        bitField0_ |= 0x00000004;
        days_ = value;
        onChanged();
        return this;
      }
      public Builder clearDays() {
        bitField0_ = (bitField0_ & ~0x00000004);
        days_ = 0;
        onChanged();
        return this;
      }
      
      // required bool buy = 4;
      private boolean buy_ ;
      public boolean hasBuy() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public boolean getBuy() {
        return buy_;
      }
      public Builder setBuy(boolean value) {
        bitField0_ |= 0x00000008;
        buy_ = value;
        onChanged();
        return this;
      }
      public Builder clearBuy() {
        bitField0_ = (bitField0_ & ~0x00000008);
        buy_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.ftkj.proto.AtvCardData)
    }
    
    static {
      defaultInstance = new AtvCardData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ftkj.proto.AtvCardData)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ftkj_proto_AtvCardAwardData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ftkj_proto_AtvCardAwardData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ftkj_proto_AtvCardData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ftkj_proto_AtvCardData_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022AtvCardAward.proto\022\016com.ftkj.proto\"@\n\020" +
      "AtvCardAwardData\022,\n\007atvList\030\001 \003(\0132\033.com." +
      "ftkj.proto.AtvCardData\"G\n\013AtvCardData\022\r\n" +
      "\005atvId\030\001 \002(\005\022\016\n\006status\030\002 \002(\005\022\014\n\004days\030\003 \002" +
      "(\005\022\013\n\003buy\030\004 \002(\010B\020B\016AtvCardAwardPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_ftkj_proto_AtvCardAwardData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_ftkj_proto_AtvCardAwardData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ftkj_proto_AtvCardAwardData_descriptor,
              new java.lang.String[] { "AtvList", },
              com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData.class,
              com.ftkj.proto.AtvCardAwardPB.AtvCardAwardData.Builder.class);
          internal_static_com_ftkj_proto_AtvCardData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_ftkj_proto_AtvCardData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ftkj_proto_AtvCardData_descriptor,
              new java.lang.String[] { "AtvId", "Status", "Days", "Buy", },
              com.ftkj.proto.AtvCardAwardPB.AtvCardData.class,
              com.ftkj.proto.AtvCardAwardPB.AtvCardData.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
