// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AtvLottery.proto

package com.ftkj.proto;

public final class AtvLotteryPB {
  private AtvLotteryPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AtvLotteryViewDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 totalCount = 1;
    boolean hasTotalCount();
    int getTotalCount();
    
    // optional int64 luckyTeamId = 2;
    boolean hasLuckyTeamId();
    long getLuckyTeamId();
    
    // optional string luckyTeamName = 3;
    boolean hasLuckyTeamName();
    String getLuckyTeamName();
  }
  public static final class AtvLotteryViewData extends
      com.google.protobuf.GeneratedMessage
      implements AtvLotteryViewDataOrBuilder {
    // Use AtvLotteryViewData.newBuilder() to construct.
    private AtvLotteryViewData(Builder builder) {
      super(builder);
    }
    private AtvLotteryViewData(boolean noInit) {}
    
    private static final AtvLotteryViewData defaultInstance;
    public static AtvLotteryViewData getDefaultInstance() {
      return defaultInstance;
    }
    
    public AtvLotteryViewData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ftkj.proto.AtvLotteryPB.internal_static_com_ftkj_proto_AtvLotteryViewData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ftkj.proto.AtvLotteryPB.internal_static_com_ftkj_proto_AtvLotteryViewData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 totalCount = 1;
    public static final int TOTALCOUNT_FIELD_NUMBER = 1;
    private int totalCount_;
    public boolean hasTotalCount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getTotalCount() {
      return totalCount_;
    }
    
    // optional int64 luckyTeamId = 2;
    public static final int LUCKYTEAMID_FIELD_NUMBER = 2;
    private long luckyTeamId_;
    public boolean hasLuckyTeamId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getLuckyTeamId() {
      return luckyTeamId_;
    }
    
    // optional string luckyTeamName = 3;
    public static final int LUCKYTEAMNAME_FIELD_NUMBER = 3;
    private java.lang.Object luckyTeamName_;
    public boolean hasLuckyTeamName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getLuckyTeamName() {
      java.lang.Object ref = luckyTeamName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          luckyTeamName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLuckyTeamNameBytes() {
      java.lang.Object ref = luckyTeamName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        luckyTeamName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      totalCount_ = 0;
      luckyTeamId_ = 0L;
      luckyTeamName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, totalCount_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, luckyTeamId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLuckyTeamNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, totalCount_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, luckyTeamId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLuckyTeamNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ftkj.proto.AtvLotteryPB.AtvLotteryViewDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ftkj.proto.AtvLotteryPB.internal_static_com_ftkj_proto_AtvLotteryViewData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ftkj.proto.AtvLotteryPB.internal_static_com_ftkj_proto_AtvLotteryViewData_fieldAccessorTable;
      }
      
      // Construct using com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        totalCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        luckyTeamId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        luckyTeamName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData.getDescriptor();
      }
      
      public com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData getDefaultInstanceForType() {
        return com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData.getDefaultInstance();
      }
      
      public com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData build() {
        com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData buildPartial() {
        com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData result = new com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.totalCount_ = totalCount_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.luckyTeamId_ = luckyTeamId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.luckyTeamName_ = luckyTeamName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData) {
          return mergeFrom((com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData other) {
        if (other == com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData.getDefaultInstance()) return this;
        if (other.hasTotalCount()) {
          setTotalCount(other.getTotalCount());
        }
        if (other.hasLuckyTeamId()) {
          setLuckyTeamId(other.getLuckyTeamId());
        }
        if (other.hasLuckyTeamName()) {
          setLuckyTeamName(other.getLuckyTeamName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              totalCount_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              luckyTeamId_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              luckyTeamName_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 totalCount = 1;
      private int totalCount_ ;
      public boolean hasTotalCount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getTotalCount() {
        return totalCount_;
      }
      public Builder setTotalCount(int value) {
        bitField0_ |= 0x00000001;
        totalCount_ = value;
        onChanged();
        return this;
      }
      public Builder clearTotalCount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        totalCount_ = 0;
        onChanged();
        return this;
      }
      
      // optional int64 luckyTeamId = 2;
      private long luckyTeamId_ ;
      public boolean hasLuckyTeamId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getLuckyTeamId() {
        return luckyTeamId_;
      }
      public Builder setLuckyTeamId(long value) {
        bitField0_ |= 0x00000002;
        luckyTeamId_ = value;
        onChanged();
        return this;
      }
      public Builder clearLuckyTeamId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        luckyTeamId_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string luckyTeamName = 3;
      private java.lang.Object luckyTeamName_ = "";
      public boolean hasLuckyTeamName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getLuckyTeamName() {
        java.lang.Object ref = luckyTeamName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          luckyTeamName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLuckyTeamName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        luckyTeamName_ = value;
        onChanged();
        return this;
      }
      public Builder clearLuckyTeamName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        luckyTeamName_ = getDefaultInstance().getLuckyTeamName();
        onChanged();
        return this;
      }
      void setLuckyTeamName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        luckyTeamName_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.ftkj.proto.AtvLotteryViewData)
    }
    
    static {
      defaultInstance = new AtvLotteryViewData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ftkj.proto.AtvLotteryViewData)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ftkj_proto_AtvLotteryViewData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ftkj_proto_AtvLotteryViewData_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020AtvLottery.proto\022\016com.ftkj.proto\"T\n\022At" +
      "vLotteryViewData\022\022\n\ntotalCount\030\001 \001(\005\022\023\n\013" +
      "luckyTeamId\030\002 \001(\003\022\025\n\rluckyTeamName\030\003 \001(\t" +
      "B\016B\014AtvLotteryPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_ftkj_proto_AtvLotteryViewData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_ftkj_proto_AtvLotteryViewData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ftkj_proto_AtvLotteryViewData_descriptor,
              new java.lang.String[] { "TotalCount", "LuckyTeamId", "LuckyTeamName", },
              com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData.class,
              com.ftkj.proto.AtvLotteryPB.AtvLotteryViewData.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
