// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AtvStarLoad.proto

package com.ftkj.proto;

public final class AtvStarLoadPB {
  private AtvStarLoadPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StarLoadDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 value = 1;
    boolean hasValue();
    int getValue();
    
    // repeated int32 status = 2;
    java.util.List<java.lang.Integer> getStatusList();
    int getStatusCount();
    int getStatus(int index);
    
    // required int32 rank = 3;
    boolean hasRank();
    int getRank();
    
    // required int32 rankStatus = 4;
    boolean hasRankStatus();
    int getRankStatus();
    
    // repeated .com.ftkj.proto.AtvTeamRankData rankList = 5;
    java.util.List<com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData> 
        getRankListList();
    com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData getRankList(int index);
    int getRankListCount();
    java.util.List<? extends com.ftkj.proto.AtvStarLoadPB.AtvTeamRankDataOrBuilder> 
        getRankListOrBuilderList();
    com.ftkj.proto.AtvStarLoadPB.AtvTeamRankDataOrBuilder getRankListOrBuilder(
        int index);
    
    // optional int32 serverStartDay = 6;
    boolean hasServerStartDay();
    int getServerStartDay();
    
    // required int32 atvId = 7;
    boolean hasAtvId();
    int getAtvId();
  }
  public static final class StarLoadData extends
      com.google.protobuf.GeneratedMessage
      implements StarLoadDataOrBuilder {
    // Use StarLoadData.newBuilder() to construct.
    private StarLoadData(Builder builder) {
      super(builder);
    }
    private StarLoadData(boolean noInit) {}
    
    private static final StarLoadData defaultInstance;
    public static StarLoadData getDefaultInstance() {
      return defaultInstance;
    }
    
    public StarLoadData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ftkj.proto.AtvStarLoadPB.internal_static_com_ftkj_proto_StarLoadData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ftkj.proto.AtvStarLoadPB.internal_static_com_ftkj_proto_StarLoadData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 value = 1;
    public static final int VALUE_FIELD_NUMBER = 1;
    private int value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getValue() {
      return value_;
    }
    
    // repeated int32 status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> status_;
    public java.util.List<java.lang.Integer>
        getStatusList() {
      return status_;
    }
    public int getStatusCount() {
      return status_.size();
    }
    public int getStatus(int index) {
      return status_.get(index);
    }
    
    // required int32 rank = 3;
    public static final int RANK_FIELD_NUMBER = 3;
    private int rank_;
    public boolean hasRank() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getRank() {
      return rank_;
    }
    
    // required int32 rankStatus = 4;
    public static final int RANKSTATUS_FIELD_NUMBER = 4;
    private int rankStatus_;
    public boolean hasRankStatus() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getRankStatus() {
      return rankStatus_;
    }
    
    // repeated .com.ftkj.proto.AtvTeamRankData rankList = 5;
    public static final int RANKLIST_FIELD_NUMBER = 5;
    private java.util.List<com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData> rankList_;
    public java.util.List<com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData> getRankListList() {
      return rankList_;
    }
    public java.util.List<? extends com.ftkj.proto.AtvStarLoadPB.AtvTeamRankDataOrBuilder> 
        getRankListOrBuilderList() {
      return rankList_;
    }
    public int getRankListCount() {
      return rankList_.size();
    }
    public com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData getRankList(int index) {
      return rankList_.get(index);
    }
    public com.ftkj.proto.AtvStarLoadPB.AtvTeamRankDataOrBuilder getRankListOrBuilder(
        int index) {
      return rankList_.get(index);
    }
    
    // optional int32 serverStartDay = 6;
    public static final int SERVERSTARTDAY_FIELD_NUMBER = 6;
    private int serverStartDay_;
    public boolean hasServerStartDay() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getServerStartDay() {
      return serverStartDay_;
    }
    
    // required int32 atvId = 7;
    public static final int ATVID_FIELD_NUMBER = 7;
    private int atvId_;
    public boolean hasAtvId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getAtvId() {
      return atvId_;
    }
    
    private void initFields() {
      value_ = 0;
      status_ = java.util.Collections.emptyList();;
      rank_ = 0;
      rankStatus_ = 0;
      rankList_ = java.util.Collections.emptyList();
      serverStartDay_ = 0;
      atvId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRank()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRankStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAtvId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getRankListCount(); i++) {
        if (!getRankList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, value_);
      }
      for (int i = 0; i < status_.size(); i++) {
        output.writeInt32(2, status_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, rank_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, rankStatus_);
      }
      for (int i = 0; i < rankList_.size(); i++) {
        output.writeMessage(5, rankList_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(6, serverStartDay_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(7, atvId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, value_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < status_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(status_.get(i));
        }
        size += dataSize;
        size += 1 * getStatusList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, rank_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, rankStatus_);
      }
      for (int i = 0; i < rankList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, rankList_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, serverStartDay_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, atvId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.ftkj.proto.AtvStarLoadPB.StarLoadData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.AtvStarLoadPB.StarLoadData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.AtvStarLoadPB.StarLoadData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.AtvStarLoadPB.StarLoadData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.AtvStarLoadPB.StarLoadData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.AtvStarLoadPB.StarLoadData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.AtvStarLoadPB.StarLoadData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.AtvStarLoadPB.StarLoadData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.AtvStarLoadPB.StarLoadData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.AtvStarLoadPB.StarLoadData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ftkj.proto.AtvStarLoadPB.StarLoadData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ftkj.proto.AtvStarLoadPB.StarLoadDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ftkj.proto.AtvStarLoadPB.internal_static_com_ftkj_proto_StarLoadData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ftkj.proto.AtvStarLoadPB.internal_static_com_ftkj_proto_StarLoadData_fieldAccessorTable;
      }
      
      // Construct using com.ftkj.proto.AtvStarLoadPB.StarLoadData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRankListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        value_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        rank_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        rankStatus_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (rankListBuilder_ == null) {
          rankList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          rankListBuilder_.clear();
        }
        serverStartDay_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        atvId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ftkj.proto.AtvStarLoadPB.StarLoadData.getDescriptor();
      }
      
      public com.ftkj.proto.AtvStarLoadPB.StarLoadData getDefaultInstanceForType() {
        return com.ftkj.proto.AtvStarLoadPB.StarLoadData.getDefaultInstance();
      }
      
      public com.ftkj.proto.AtvStarLoadPB.StarLoadData build() {
        com.ftkj.proto.AtvStarLoadPB.StarLoadData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.ftkj.proto.AtvStarLoadPB.StarLoadData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.ftkj.proto.AtvStarLoadPB.StarLoadData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.ftkj.proto.AtvStarLoadPB.StarLoadData buildPartial() {
        com.ftkj.proto.AtvStarLoadPB.StarLoadData result = new com.ftkj.proto.AtvStarLoadPB.StarLoadData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.value_ = value_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          status_ = java.util.Collections.unmodifiableList(status_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rank_ = rank_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.rankStatus_ = rankStatus_;
        if (rankListBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            rankList_ = java.util.Collections.unmodifiableList(rankList_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.rankList_ = rankList_;
        } else {
          result.rankList_ = rankListBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000008;
        }
        result.serverStartDay_ = serverStartDay_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000010;
        }
        result.atvId_ = atvId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ftkj.proto.AtvStarLoadPB.StarLoadData) {
          return mergeFrom((com.ftkj.proto.AtvStarLoadPB.StarLoadData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.ftkj.proto.AtvStarLoadPB.StarLoadData other) {
        if (other == com.ftkj.proto.AtvStarLoadPB.StarLoadData.getDefaultInstance()) return this;
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (!other.status_.isEmpty()) {
          if (status_.isEmpty()) {
            status_ = other.status_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureStatusIsMutable();
            status_.addAll(other.status_);
          }
          onChanged();
        }
        if (other.hasRank()) {
          setRank(other.getRank());
        }
        if (other.hasRankStatus()) {
          setRankStatus(other.getRankStatus());
        }
        if (rankListBuilder_ == null) {
          if (!other.rankList_.isEmpty()) {
            if (rankList_.isEmpty()) {
              rankList_ = other.rankList_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureRankListIsMutable();
              rankList_.addAll(other.rankList_);
            }
            onChanged();
          }
        } else {
          if (!other.rankList_.isEmpty()) {
            if (rankListBuilder_.isEmpty()) {
              rankListBuilder_.dispose();
              rankListBuilder_ = null;
              rankList_ = other.rankList_;
              bitField0_ = (bitField0_ & ~0x00000010);
              rankListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRankListFieldBuilder() : null;
            } else {
              rankListBuilder_.addAllMessages(other.rankList_);
            }
          }
        }
        if (other.hasServerStartDay()) {
          setServerStartDay(other.getServerStartDay());
        }
        if (other.hasAtvId()) {
          setAtvId(other.getAtvId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasValue()) {
          
          return false;
        }
        if (!hasRank()) {
          
          return false;
        }
        if (!hasRankStatus()) {
          
          return false;
        }
        if (!hasAtvId()) {
          
          return false;
        }
        for (int i = 0; i < getRankListCount(); i++) {
          if (!getRankList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              value_ = input.readInt32();
              break;
            }
            case 16: {
              ensureStatusIsMutable();
              status_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addStatus(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              rank_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              rankStatus_ = input.readInt32();
              break;
            }
            case 42: {
              com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData.Builder subBuilder = com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addRankList(subBuilder.buildPartial());
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              serverStartDay_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              atvId_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 value = 1;
      private int value_ ;
      public boolean hasValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getValue() {
        return value_;
      }
      public Builder setValue(int value) {
        bitField0_ |= 0x00000001;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0;
        onChanged();
        return this;
      }
      
      // repeated int32 status = 2;
      private java.util.List<java.lang.Integer> status_ = java.util.Collections.emptyList();;
      private void ensureStatusIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          status_ = new java.util.ArrayList<java.lang.Integer>(status_);
          bitField0_ |= 0x00000002;
         }
      }
      public java.util.List<java.lang.Integer>
          getStatusList() {
        return java.util.Collections.unmodifiableList(status_);
      }
      public int getStatusCount() {
        return status_.size();
      }
      public int getStatus(int index) {
        return status_.get(index);
      }
      public Builder setStatus(
          int index, int value) {
        ensureStatusIsMutable();
        status_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addStatus(int value) {
        ensureStatusIsMutable();
        status_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllStatus(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureStatusIsMutable();
        super.addAll(values, status_);
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        status_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      
      // required int32 rank = 3;
      private int rank_ ;
      public boolean hasRank() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getRank() {
        return rank_;
      }
      public Builder setRank(int value) {
        bitField0_ |= 0x00000004;
        rank_ = value;
        onChanged();
        return this;
      }
      public Builder clearRank() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rank_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 rankStatus = 4;
      private int rankStatus_ ;
      public boolean hasRankStatus() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getRankStatus() {
        return rankStatus_;
      }
      public Builder setRankStatus(int value) {
        bitField0_ |= 0x00000008;
        rankStatus_ = value;
        onChanged();
        return this;
      }
      public Builder clearRankStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        rankStatus_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .com.ftkj.proto.AtvTeamRankData rankList = 5;
      private java.util.List<com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData> rankList_ =
        java.util.Collections.emptyList();
      private void ensureRankListIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          rankList_ = new java.util.ArrayList<com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData>(rankList_);
          bitField0_ |= 0x00000010;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData, com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData.Builder, com.ftkj.proto.AtvStarLoadPB.AtvTeamRankDataOrBuilder> rankListBuilder_;
      
      public java.util.List<com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData> getRankListList() {
        if (rankListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rankList_);
        } else {
          return rankListBuilder_.getMessageList();
        }
      }
      public int getRankListCount() {
        if (rankListBuilder_ == null) {
          return rankList_.size();
        } else {
          return rankListBuilder_.getCount();
        }
      }
      public com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData getRankList(int index) {
        if (rankListBuilder_ == null) {
          return rankList_.get(index);
        } else {
          return rankListBuilder_.getMessage(index);
        }
      }
      public Builder setRankList(
          int index, com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData value) {
        if (rankListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRankListIsMutable();
          rankList_.set(index, value);
          onChanged();
        } else {
          rankListBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setRankList(
          int index, com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData.Builder builderForValue) {
        if (rankListBuilder_ == null) {
          ensureRankListIsMutable();
          rankList_.set(index, builderForValue.build());
          onChanged();
        } else {
          rankListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addRankList(com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData value) {
        if (rankListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRankListIsMutable();
          rankList_.add(value);
          onChanged();
        } else {
          rankListBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addRankList(
          int index, com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData value) {
        if (rankListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRankListIsMutable();
          rankList_.add(index, value);
          onChanged();
        } else {
          rankListBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addRankList(
          com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData.Builder builderForValue) {
        if (rankListBuilder_ == null) {
          ensureRankListIsMutable();
          rankList_.add(builderForValue.build());
          onChanged();
        } else {
          rankListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addRankList(
          int index, com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData.Builder builderForValue) {
        if (rankListBuilder_ == null) {
          ensureRankListIsMutable();
          rankList_.add(index, builderForValue.build());
          onChanged();
        } else {
          rankListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllRankList(
          java.lang.Iterable<? extends com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData> values) {
        if (rankListBuilder_ == null) {
          ensureRankListIsMutable();
          super.addAll(values, rankList_);
          onChanged();
        } else {
          rankListBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearRankList() {
        if (rankListBuilder_ == null) {
          rankList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          rankListBuilder_.clear();
        }
        return this;
      }
      public Builder removeRankList(int index) {
        if (rankListBuilder_ == null) {
          ensureRankListIsMutable();
          rankList_.remove(index);
          onChanged();
        } else {
          rankListBuilder_.remove(index);
        }
        return this;
      }
      public com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData.Builder getRankListBuilder(
          int index) {
        return getRankListFieldBuilder().getBuilder(index);
      }
      public com.ftkj.proto.AtvStarLoadPB.AtvTeamRankDataOrBuilder getRankListOrBuilder(
          int index) {
        if (rankListBuilder_ == null) {
          return rankList_.get(index);  } else {
          return rankListBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.ftkj.proto.AtvStarLoadPB.AtvTeamRankDataOrBuilder> 
           getRankListOrBuilderList() {
        if (rankListBuilder_ != null) {
          return rankListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rankList_);
        }
      }
      public com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData.Builder addRankListBuilder() {
        return getRankListFieldBuilder().addBuilder(
            com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData.getDefaultInstance());
      }
      public com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData.Builder addRankListBuilder(
          int index) {
        return getRankListFieldBuilder().addBuilder(
            index, com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData.getDefaultInstance());
      }
      public java.util.List<com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData.Builder> 
           getRankListBuilderList() {
        return getRankListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData, com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData.Builder, com.ftkj.proto.AtvStarLoadPB.AtvTeamRankDataOrBuilder> 
          getRankListFieldBuilder() {
        if (rankListBuilder_ == null) {
          rankListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData, com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData.Builder, com.ftkj.proto.AtvStarLoadPB.AtvTeamRankDataOrBuilder>(
                  rankList_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          rankList_ = null;
        }
        return rankListBuilder_;
      }
      
      // optional int32 serverStartDay = 6;
      private int serverStartDay_ ;
      public boolean hasServerStartDay() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getServerStartDay() {
        return serverStartDay_;
      }
      public Builder setServerStartDay(int value) {
        bitField0_ |= 0x00000020;
        serverStartDay_ = value;
        onChanged();
        return this;
      }
      public Builder clearServerStartDay() {
        bitField0_ = (bitField0_ & ~0x00000020);
        serverStartDay_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 atvId = 7;
      private int atvId_ ;
      public boolean hasAtvId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getAtvId() {
        return atvId_;
      }
      public Builder setAtvId(int value) {
        bitField0_ |= 0x00000040;
        atvId_ = value;
        onChanged();
        return this;
      }
      public Builder clearAtvId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        atvId_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.ftkj.proto.StarLoadData)
    }
    
    static {
      defaultInstance = new StarLoadData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ftkj.proto.StarLoadData)
  }
  
  public interface AtvTeamRankDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 teamId = 1;
    boolean hasTeamId();
    long getTeamId();
    
    // required string teamName = 2;
    boolean hasTeamName();
    String getTeamName();
    
    // required int32 lv = 3;
    boolean hasLv();
    int getLv();
    
    // required int32 rank = 4;
    boolean hasRank();
    int getRank();
  }
  public static final class AtvTeamRankData extends
      com.google.protobuf.GeneratedMessage
      implements AtvTeamRankDataOrBuilder {
    // Use AtvTeamRankData.newBuilder() to construct.
    private AtvTeamRankData(Builder builder) {
      super(builder);
    }
    private AtvTeamRankData(boolean noInit) {}
    
    private static final AtvTeamRankData defaultInstance;
    public static AtvTeamRankData getDefaultInstance() {
      return defaultInstance;
    }
    
    public AtvTeamRankData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ftkj.proto.AtvStarLoadPB.internal_static_com_ftkj_proto_AtvTeamRankData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ftkj.proto.AtvStarLoadPB.internal_static_com_ftkj_proto_AtvTeamRankData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int64 teamId = 1;
    public static final int TEAMID_FIELD_NUMBER = 1;
    private long teamId_;
    public boolean hasTeamId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTeamId() {
      return teamId_;
    }
    
    // required string teamName = 2;
    public static final int TEAMNAME_FIELD_NUMBER = 2;
    private java.lang.Object teamName_;
    public boolean hasTeamName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTeamName() {
      java.lang.Object ref = teamName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          teamName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTeamNameBytes() {
      java.lang.Object ref = teamName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        teamName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 lv = 3;
    public static final int LV_FIELD_NUMBER = 3;
    private int lv_;
    public boolean hasLv() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getLv() {
      return lv_;
    }
    
    // required int32 rank = 4;
    public static final int RANK_FIELD_NUMBER = 4;
    private int rank_;
    public boolean hasRank() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getRank() {
      return rank_;
    }
    
    private void initFields() {
      teamId_ = 0L;
      teamName_ = "";
      lv_ = 0;
      rank_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTeamId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTeamName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLv()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRank()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, teamId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTeamNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, lv_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, rank_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, teamId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTeamNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, lv_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, rank_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ftkj.proto.AtvStarLoadPB.AtvTeamRankDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ftkj.proto.AtvStarLoadPB.internal_static_com_ftkj_proto_AtvTeamRankData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ftkj.proto.AtvStarLoadPB.internal_static_com_ftkj_proto_AtvTeamRankData_fieldAccessorTable;
      }
      
      // Construct using com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        teamId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        teamName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        lv_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        rank_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData.getDescriptor();
      }
      
      public com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData getDefaultInstanceForType() {
        return com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData.getDefaultInstance();
      }
      
      public com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData build() {
        com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData buildPartial() {
        com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData result = new com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.teamId_ = teamId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.teamName_ = teamName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lv_ = lv_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.rank_ = rank_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData) {
          return mergeFrom((com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData other) {
        if (other == com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData.getDefaultInstance()) return this;
        if (other.hasTeamId()) {
          setTeamId(other.getTeamId());
        }
        if (other.hasTeamName()) {
          setTeamName(other.getTeamName());
        }
        if (other.hasLv()) {
          setLv(other.getLv());
        }
        if (other.hasRank()) {
          setRank(other.getRank());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTeamId()) {
          
          return false;
        }
        if (!hasTeamName()) {
          
          return false;
        }
        if (!hasLv()) {
          
          return false;
        }
        if (!hasRank()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              teamId_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              teamName_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              lv_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              rank_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 teamId = 1;
      private long teamId_ ;
      public boolean hasTeamId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTeamId() {
        return teamId_;
      }
      public Builder setTeamId(long value) {
        bitField0_ |= 0x00000001;
        teamId_ = value;
        onChanged();
        return this;
      }
      public Builder clearTeamId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        teamId_ = 0L;
        onChanged();
        return this;
      }
      
      // required string teamName = 2;
      private java.lang.Object teamName_ = "";
      public boolean hasTeamName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTeamName() {
        java.lang.Object ref = teamName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          teamName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTeamName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        teamName_ = value;
        onChanged();
        return this;
      }
      public Builder clearTeamName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        teamName_ = getDefaultInstance().getTeamName();
        onChanged();
        return this;
      }
      void setTeamName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        teamName_ = value;
        onChanged();
      }
      
      // required int32 lv = 3;
      private int lv_ ;
      public boolean hasLv() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getLv() {
        return lv_;
      }
      public Builder setLv(int value) {
        bitField0_ |= 0x00000004;
        lv_ = value;
        onChanged();
        return this;
      }
      public Builder clearLv() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lv_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 rank = 4;
      private int rank_ ;
      public boolean hasRank() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getRank() {
        return rank_;
      }
      public Builder setRank(int value) {
        bitField0_ |= 0x00000008;
        rank_ = value;
        onChanged();
        return this;
      }
      public Builder clearRank() {
        bitField0_ = (bitField0_ & ~0x00000008);
        rank_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.ftkj.proto.AtvTeamRankData)
    }
    
    static {
      defaultInstance = new AtvTeamRankData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ftkj.proto.AtvTeamRankData)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ftkj_proto_StarLoadData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ftkj_proto_StarLoadData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ftkj_proto_AtvTeamRankData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ftkj_proto_AtvTeamRankData_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021AtvStarLoad.proto\022\016com.ftkj.proto\"\251\001\n\014" +
      "StarLoadData\022\r\n\005value\030\001 \002(\005\022\016\n\006status\030\002 " +
      "\003(\005\022\014\n\004rank\030\003 \002(\005\022\022\n\nrankStatus\030\004 \002(\005\0221\n" +
      "\010rankList\030\005 \003(\0132\037.com.ftkj.proto.AtvTeam" +
      "RankData\022\026\n\016serverStartDay\030\006 \001(\005\022\r\n\005atvI" +
      "d\030\007 \002(\005\"M\n\017AtvTeamRankData\022\016\n\006teamId\030\001 \002" +
      "(\003\022\020\n\010teamName\030\002 \002(\t\022\n\n\002lv\030\003 \002(\005\022\014\n\004rank" +
      "\030\004 \002(\005B\017B\rAtvStarLoadPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_ftkj_proto_StarLoadData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_ftkj_proto_StarLoadData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ftkj_proto_StarLoadData_descriptor,
              new java.lang.String[] { "Value", "Status", "Rank", "RankStatus", "RankList", "ServerStartDay", "AtvId", },
              com.ftkj.proto.AtvStarLoadPB.StarLoadData.class,
              com.ftkj.proto.AtvStarLoadPB.StarLoadData.Builder.class);
          internal_static_com_ftkj_proto_AtvTeamRankData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_ftkj_proto_AtvTeamRankData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ftkj_proto_AtvTeamRankData_descriptor,
              new java.lang.String[] { "TeamId", "TeamName", "Lv", "Rank", },
              com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData.class,
              com.ftkj.proto.AtvStarLoadPB.AtvTeamRankData.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
