// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Buff.proto

package com.ftkj.proto;

public final class BuffPB {
  private BuffPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BuffDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
    
    // repeated int32 values = 2;
    java.util.List<java.lang.Integer> getValuesList();
    int getValuesCount();
    int getValues(int index);
    
    // required int64 endTime = 3;
    boolean hasEndTime();
    long getEndTime();
  }
  public static final class BuffData extends
      com.google.protobuf.GeneratedMessage
      implements BuffDataOrBuilder {
    // Use BuffData.newBuilder() to construct.
    private BuffData(Builder builder) {
      super(builder);
    }
    private BuffData(boolean noInit) {}
    
    private static final BuffData defaultInstance;
    public static BuffData getDefaultInstance() {
      return defaultInstance;
    }
    
    public BuffData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ftkj.proto.BuffPB.internal_static_com_ftkj_proto_BuffData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ftkj.proto.BuffPB.internal_static_com_ftkj_proto_BuffData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // repeated int32 values = 2;
    public static final int VALUES_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> values_;
    public java.util.List<java.lang.Integer>
        getValuesList() {
      return values_;
    }
    public int getValuesCount() {
      return values_.size();
    }
    public int getValues(int index) {
      return values_.get(index);
    }
    
    // required int64 endTime = 3;
    public static final int ENDTIME_FIELD_NUMBER = 3;
    private long endTime_;
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getEndTime() {
      return endTime_;
    }
    
    private void initFields() {
      id_ = 0;
      values_ = java.util.Collections.emptyList();;
      endTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEndTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      for (int i = 0; i < values_.size(); i++) {
        output.writeInt32(2, values_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(3, endTime_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < values_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(values_.get(i));
        }
        size += dataSize;
        size += 1 * getValuesList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, endTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.ftkj.proto.BuffPB.BuffData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.BuffPB.BuffData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.BuffPB.BuffData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.BuffPB.BuffData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.BuffPB.BuffData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.BuffPB.BuffData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.BuffPB.BuffData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.BuffPB.BuffData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.BuffPB.BuffData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.BuffPB.BuffData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ftkj.proto.BuffPB.BuffData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ftkj.proto.BuffPB.BuffDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ftkj.proto.BuffPB.internal_static_com_ftkj_proto_BuffData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ftkj.proto.BuffPB.internal_static_com_ftkj_proto_BuffData_fieldAccessorTable;
      }
      
      // Construct using com.ftkj.proto.BuffPB.BuffData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        values_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        endTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ftkj.proto.BuffPB.BuffData.getDescriptor();
      }
      
      public com.ftkj.proto.BuffPB.BuffData getDefaultInstanceForType() {
        return com.ftkj.proto.BuffPB.BuffData.getDefaultInstance();
      }
      
      public com.ftkj.proto.BuffPB.BuffData build() {
        com.ftkj.proto.BuffPB.BuffData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.ftkj.proto.BuffPB.BuffData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.ftkj.proto.BuffPB.BuffData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.ftkj.proto.BuffPB.BuffData buildPartial() {
        com.ftkj.proto.BuffPB.BuffData result = new com.ftkj.proto.BuffPB.BuffData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          values_ = java.util.Collections.unmodifiableList(values_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.values_ = values_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.endTime_ = endTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ftkj.proto.BuffPB.BuffData) {
          return mergeFrom((com.ftkj.proto.BuffPB.BuffData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.ftkj.proto.BuffPB.BuffData other) {
        if (other == com.ftkj.proto.BuffPB.BuffData.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (!other.values_.isEmpty()) {
          if (values_.isEmpty()) {
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureValuesIsMutable();
            values_.addAll(other.values_);
          }
          onChanged();
        }
        if (other.hasEndTime()) {
          setEndTime(other.getEndTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasEndTime()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              ensureValuesIsMutable();
              values_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addValues(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              endTime_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // repeated int32 values = 2;
      private java.util.List<java.lang.Integer> values_ = java.util.Collections.emptyList();;
      private void ensureValuesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          values_ = new java.util.ArrayList<java.lang.Integer>(values_);
          bitField0_ |= 0x00000002;
         }
      }
      public java.util.List<java.lang.Integer>
          getValuesList() {
        return java.util.Collections.unmodifiableList(values_);
      }
      public int getValuesCount() {
        return values_.size();
      }
      public int getValues(int index) {
        return values_.get(index);
      }
      public Builder setValues(
          int index, int value) {
        ensureValuesIsMutable();
        values_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addValues(int value) {
        ensureValuesIsMutable();
        values_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllValues(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureValuesIsMutable();
        super.addAll(values, values_);
        onChanged();
        return this;
      }
      public Builder clearValues() {
        values_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      
      // required int64 endTime = 3;
      private long endTime_ ;
      public boolean hasEndTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getEndTime() {
        return endTime_;
      }
      public Builder setEndTime(long value) {
        bitField0_ |= 0x00000004;
        endTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        endTime_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.ftkj.proto.BuffData)
    }
    
    static {
      defaultInstance = new BuffData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ftkj.proto.BuffData)
  }
  
  public interface TeamBuffListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .com.ftkj.proto.BuffData buffList = 1;
    java.util.List<com.ftkj.proto.BuffPB.BuffData> 
        getBuffListList();
    com.ftkj.proto.BuffPB.BuffData getBuffList(int index);
    int getBuffListCount();
    java.util.List<? extends com.ftkj.proto.BuffPB.BuffDataOrBuilder> 
        getBuffListOrBuilderList();
    com.ftkj.proto.BuffPB.BuffDataOrBuilder getBuffListOrBuilder(
        int index);
  }
  public static final class TeamBuffList extends
      com.google.protobuf.GeneratedMessage
      implements TeamBuffListOrBuilder {
    // Use TeamBuffList.newBuilder() to construct.
    private TeamBuffList(Builder builder) {
      super(builder);
    }
    private TeamBuffList(boolean noInit) {}
    
    private static final TeamBuffList defaultInstance;
    public static TeamBuffList getDefaultInstance() {
      return defaultInstance;
    }
    
    public TeamBuffList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ftkj.proto.BuffPB.internal_static_com_ftkj_proto_TeamBuffList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ftkj.proto.BuffPB.internal_static_com_ftkj_proto_TeamBuffList_fieldAccessorTable;
    }
    
    // repeated .com.ftkj.proto.BuffData buffList = 1;
    public static final int BUFFLIST_FIELD_NUMBER = 1;
    private java.util.List<com.ftkj.proto.BuffPB.BuffData> buffList_;
    public java.util.List<com.ftkj.proto.BuffPB.BuffData> getBuffListList() {
      return buffList_;
    }
    public java.util.List<? extends com.ftkj.proto.BuffPB.BuffDataOrBuilder> 
        getBuffListOrBuilderList() {
      return buffList_;
    }
    public int getBuffListCount() {
      return buffList_.size();
    }
    public com.ftkj.proto.BuffPB.BuffData getBuffList(int index) {
      return buffList_.get(index);
    }
    public com.ftkj.proto.BuffPB.BuffDataOrBuilder getBuffListOrBuilder(
        int index) {
      return buffList_.get(index);
    }
    
    private void initFields() {
      buffList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getBuffListCount(); i++) {
        if (!getBuffList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < buffList_.size(); i++) {
        output.writeMessage(1, buffList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < buffList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, buffList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.ftkj.proto.BuffPB.TeamBuffList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.BuffPB.TeamBuffList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.BuffPB.TeamBuffList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.BuffPB.TeamBuffList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.BuffPB.TeamBuffList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.BuffPB.TeamBuffList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.BuffPB.TeamBuffList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.BuffPB.TeamBuffList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.BuffPB.TeamBuffList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.BuffPB.TeamBuffList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ftkj.proto.BuffPB.TeamBuffList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ftkj.proto.BuffPB.TeamBuffListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ftkj.proto.BuffPB.internal_static_com_ftkj_proto_TeamBuffList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ftkj.proto.BuffPB.internal_static_com_ftkj_proto_TeamBuffList_fieldAccessorTable;
      }
      
      // Construct using com.ftkj.proto.BuffPB.TeamBuffList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBuffListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (buffListBuilder_ == null) {
          buffList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          buffListBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ftkj.proto.BuffPB.TeamBuffList.getDescriptor();
      }
      
      public com.ftkj.proto.BuffPB.TeamBuffList getDefaultInstanceForType() {
        return com.ftkj.proto.BuffPB.TeamBuffList.getDefaultInstance();
      }
      
      public com.ftkj.proto.BuffPB.TeamBuffList build() {
        com.ftkj.proto.BuffPB.TeamBuffList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.ftkj.proto.BuffPB.TeamBuffList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.ftkj.proto.BuffPB.TeamBuffList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.ftkj.proto.BuffPB.TeamBuffList buildPartial() {
        com.ftkj.proto.BuffPB.TeamBuffList result = new com.ftkj.proto.BuffPB.TeamBuffList(this);
        int from_bitField0_ = bitField0_;
        if (buffListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            buffList_ = java.util.Collections.unmodifiableList(buffList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.buffList_ = buffList_;
        } else {
          result.buffList_ = buffListBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ftkj.proto.BuffPB.TeamBuffList) {
          return mergeFrom((com.ftkj.proto.BuffPB.TeamBuffList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.ftkj.proto.BuffPB.TeamBuffList other) {
        if (other == com.ftkj.proto.BuffPB.TeamBuffList.getDefaultInstance()) return this;
        if (buffListBuilder_ == null) {
          if (!other.buffList_.isEmpty()) {
            if (buffList_.isEmpty()) {
              buffList_ = other.buffList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBuffListIsMutable();
              buffList_.addAll(other.buffList_);
            }
            onChanged();
          }
        } else {
          if (!other.buffList_.isEmpty()) {
            if (buffListBuilder_.isEmpty()) {
              buffListBuilder_.dispose();
              buffListBuilder_ = null;
              buffList_ = other.buffList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              buffListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBuffListFieldBuilder() : null;
            } else {
              buffListBuilder_.addAllMessages(other.buffList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getBuffListCount(); i++) {
          if (!getBuffList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.ftkj.proto.BuffPB.BuffData.Builder subBuilder = com.ftkj.proto.BuffPB.BuffData.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addBuffList(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .com.ftkj.proto.BuffData buffList = 1;
      private java.util.List<com.ftkj.proto.BuffPB.BuffData> buffList_ =
        java.util.Collections.emptyList();
      private void ensureBuffListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          buffList_ = new java.util.ArrayList<com.ftkj.proto.BuffPB.BuffData>(buffList_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ftkj.proto.BuffPB.BuffData, com.ftkj.proto.BuffPB.BuffData.Builder, com.ftkj.proto.BuffPB.BuffDataOrBuilder> buffListBuilder_;
      
      public java.util.List<com.ftkj.proto.BuffPB.BuffData> getBuffListList() {
        if (buffListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(buffList_);
        } else {
          return buffListBuilder_.getMessageList();
        }
      }
      public int getBuffListCount() {
        if (buffListBuilder_ == null) {
          return buffList_.size();
        } else {
          return buffListBuilder_.getCount();
        }
      }
      public com.ftkj.proto.BuffPB.BuffData getBuffList(int index) {
        if (buffListBuilder_ == null) {
          return buffList_.get(index);
        } else {
          return buffListBuilder_.getMessage(index);
        }
      }
      public Builder setBuffList(
          int index, com.ftkj.proto.BuffPB.BuffData value) {
        if (buffListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBuffListIsMutable();
          buffList_.set(index, value);
          onChanged();
        } else {
          buffListBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setBuffList(
          int index, com.ftkj.proto.BuffPB.BuffData.Builder builderForValue) {
        if (buffListBuilder_ == null) {
          ensureBuffListIsMutable();
          buffList_.set(index, builderForValue.build());
          onChanged();
        } else {
          buffListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addBuffList(com.ftkj.proto.BuffPB.BuffData value) {
        if (buffListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBuffListIsMutable();
          buffList_.add(value);
          onChanged();
        } else {
          buffListBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addBuffList(
          int index, com.ftkj.proto.BuffPB.BuffData value) {
        if (buffListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBuffListIsMutable();
          buffList_.add(index, value);
          onChanged();
        } else {
          buffListBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addBuffList(
          com.ftkj.proto.BuffPB.BuffData.Builder builderForValue) {
        if (buffListBuilder_ == null) {
          ensureBuffListIsMutable();
          buffList_.add(builderForValue.build());
          onChanged();
        } else {
          buffListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addBuffList(
          int index, com.ftkj.proto.BuffPB.BuffData.Builder builderForValue) {
        if (buffListBuilder_ == null) {
          ensureBuffListIsMutable();
          buffList_.add(index, builderForValue.build());
          onChanged();
        } else {
          buffListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllBuffList(
          java.lang.Iterable<? extends com.ftkj.proto.BuffPB.BuffData> values) {
        if (buffListBuilder_ == null) {
          ensureBuffListIsMutable();
          super.addAll(values, buffList_);
          onChanged();
        } else {
          buffListBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearBuffList() {
        if (buffListBuilder_ == null) {
          buffList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          buffListBuilder_.clear();
        }
        return this;
      }
      public Builder removeBuffList(int index) {
        if (buffListBuilder_ == null) {
          ensureBuffListIsMutable();
          buffList_.remove(index);
          onChanged();
        } else {
          buffListBuilder_.remove(index);
        }
        return this;
      }
      public com.ftkj.proto.BuffPB.BuffData.Builder getBuffListBuilder(
          int index) {
        return getBuffListFieldBuilder().getBuilder(index);
      }
      public com.ftkj.proto.BuffPB.BuffDataOrBuilder getBuffListOrBuilder(
          int index) {
        if (buffListBuilder_ == null) {
          return buffList_.get(index);  } else {
          return buffListBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.ftkj.proto.BuffPB.BuffDataOrBuilder> 
           getBuffListOrBuilderList() {
        if (buffListBuilder_ != null) {
          return buffListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(buffList_);
        }
      }
      public com.ftkj.proto.BuffPB.BuffData.Builder addBuffListBuilder() {
        return getBuffListFieldBuilder().addBuilder(
            com.ftkj.proto.BuffPB.BuffData.getDefaultInstance());
      }
      public com.ftkj.proto.BuffPB.BuffData.Builder addBuffListBuilder(
          int index) {
        return getBuffListFieldBuilder().addBuilder(
            index, com.ftkj.proto.BuffPB.BuffData.getDefaultInstance());
      }
      public java.util.List<com.ftkj.proto.BuffPB.BuffData.Builder> 
           getBuffListBuilderList() {
        return getBuffListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ftkj.proto.BuffPB.BuffData, com.ftkj.proto.BuffPB.BuffData.Builder, com.ftkj.proto.BuffPB.BuffDataOrBuilder> 
          getBuffListFieldBuilder() {
        if (buffListBuilder_ == null) {
          buffListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.ftkj.proto.BuffPB.BuffData, com.ftkj.proto.BuffPB.BuffData.Builder, com.ftkj.proto.BuffPB.BuffDataOrBuilder>(
                  buffList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          buffList_ = null;
        }
        return buffListBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.ftkj.proto.TeamBuffList)
    }
    
    static {
      defaultInstance = new TeamBuffList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ftkj.proto.TeamBuffList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ftkj_proto_BuffData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ftkj_proto_BuffData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ftkj_proto_TeamBuffList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ftkj_proto_TeamBuffList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nBuff.proto\022\016com.ftkj.proto\"7\n\010BuffData" +
      "\022\n\n\002id\030\001 \002(\005\022\016\n\006values\030\002 \003(\005\022\017\n\007endTime\030" +
      "\003 \002(\003\":\n\014TeamBuffList\022*\n\010buffList\030\001 \003(\0132" +
      "\030.com.ftkj.proto.BuffDataB\010B\006BuffPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_ftkj_proto_BuffData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_ftkj_proto_BuffData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ftkj_proto_BuffData_descriptor,
              new java.lang.String[] { "Id", "Values", "EndTime", },
              com.ftkj.proto.BuffPB.BuffData.class,
              com.ftkj.proto.BuffPB.BuffData.Builder.class);
          internal_static_com_ftkj_proto_TeamBuffList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_ftkj_proto_TeamBuffList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ftkj_proto_TeamBuffList_descriptor,
              new java.lang.String[] { "BuffList", },
              com.ftkj.proto.BuffPB.TeamBuffList.class,
              com.ftkj.proto.BuffPB.TeamBuffList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
