// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LimitChallenge.proto

package com.ftkj.proto;

public final class LimitChallengePB {
  private LimitChallengePB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LimitChallengeViewOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 todayTitle = 1;
    boolean hasTodayTitle();
    int getTodayTitle();
    
    // repeated .com.ftkj.proto.LimitChallengeRank playerRank = 2;
    java.util.List<com.ftkj.proto.LimitChallengePB.LimitChallengeRank> 
        getPlayerRankList();
    com.ftkj.proto.LimitChallengePB.LimitChallengeRank getPlayerRank(int index);
    int getPlayerRankCount();
    java.util.List<? extends com.ftkj.proto.LimitChallengePB.LimitChallengeRankOrBuilder> 
        getPlayerRankOrBuilderList();
    com.ftkj.proto.LimitChallengePB.LimitChallengeRankOrBuilder getPlayerRankOrBuilder(
        int index);
    
    // optional .com.ftkj.proto.LimitChallengeRank myData = 3;
    boolean hasMyData();
    com.ftkj.proto.LimitChallengePB.LimitChallengeRank getMyData();
    com.ftkj.proto.LimitChallengePB.LimitChallengeRankOrBuilder getMyDataOrBuilder();
    
    // optional int32 leftChallengeNum = 4;
    boolean hasLeftChallengeNum();
    int getLeftChallengeNum();
    
    // optional int32 cdEndTime = 5;
    boolean hasCdEndTime();
    int getCdEndTime();
    
    // optional int32 buyNum = 6;
    boolean hasBuyNum();
    int getBuyNum();
    
    // optional int32 npcId = 7;
    boolean hasNpcId();
    int getNpcId();
    
    // optional string startTime = 8;
    boolean hasStartTime();
    String getStartTime();
    
    // optional string endTime = 9;
    boolean hasEndTime();
    String getEndTime();
    
    // optional string rewardTime = 10;
    boolean hasRewardTime();
    String getRewardTime();
  }
  public static final class LimitChallengeView extends
      com.google.protobuf.GeneratedMessage
      implements LimitChallengeViewOrBuilder {
    // Use LimitChallengeView.newBuilder() to construct.
    private LimitChallengeView(Builder builder) {
      super(builder);
    }
    private LimitChallengeView(boolean noInit) {}
    
    private static final LimitChallengeView defaultInstance;
    public static LimitChallengeView getDefaultInstance() {
      return defaultInstance;
    }
    
    public LimitChallengeView getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ftkj.proto.LimitChallengePB.internal_static_com_ftkj_proto_LimitChallengeView_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ftkj.proto.LimitChallengePB.internal_static_com_ftkj_proto_LimitChallengeView_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 todayTitle = 1;
    public static final int TODAYTITLE_FIELD_NUMBER = 1;
    private int todayTitle_;
    public boolean hasTodayTitle() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getTodayTitle() {
      return todayTitle_;
    }
    
    // repeated .com.ftkj.proto.LimitChallengeRank playerRank = 2;
    public static final int PLAYERRANK_FIELD_NUMBER = 2;
    private java.util.List<com.ftkj.proto.LimitChallengePB.LimitChallengeRank> playerRank_;
    public java.util.List<com.ftkj.proto.LimitChallengePB.LimitChallengeRank> getPlayerRankList() {
      return playerRank_;
    }
    public java.util.List<? extends com.ftkj.proto.LimitChallengePB.LimitChallengeRankOrBuilder> 
        getPlayerRankOrBuilderList() {
      return playerRank_;
    }
    public int getPlayerRankCount() {
      return playerRank_.size();
    }
    public com.ftkj.proto.LimitChallengePB.LimitChallengeRank getPlayerRank(int index) {
      return playerRank_.get(index);
    }
    public com.ftkj.proto.LimitChallengePB.LimitChallengeRankOrBuilder getPlayerRankOrBuilder(
        int index) {
      return playerRank_.get(index);
    }
    
    // optional .com.ftkj.proto.LimitChallengeRank myData = 3;
    public static final int MYDATA_FIELD_NUMBER = 3;
    private com.ftkj.proto.LimitChallengePB.LimitChallengeRank myData_;
    public boolean hasMyData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.ftkj.proto.LimitChallengePB.LimitChallengeRank getMyData() {
      return myData_;
    }
    public com.ftkj.proto.LimitChallengePB.LimitChallengeRankOrBuilder getMyDataOrBuilder() {
      return myData_;
    }
    
    // optional int32 leftChallengeNum = 4;
    public static final int LEFTCHALLENGENUM_FIELD_NUMBER = 4;
    private int leftChallengeNum_;
    public boolean hasLeftChallengeNum() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getLeftChallengeNum() {
      return leftChallengeNum_;
    }
    
    // optional int32 cdEndTime = 5;
    public static final int CDENDTIME_FIELD_NUMBER = 5;
    private int cdEndTime_;
    public boolean hasCdEndTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getCdEndTime() {
      return cdEndTime_;
    }
    
    // optional int32 buyNum = 6;
    public static final int BUYNUM_FIELD_NUMBER = 6;
    private int buyNum_;
    public boolean hasBuyNum() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getBuyNum() {
      return buyNum_;
    }
    
    // optional int32 npcId = 7;
    public static final int NPCID_FIELD_NUMBER = 7;
    private int npcId_;
    public boolean hasNpcId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getNpcId() {
      return npcId_;
    }
    
    // optional string startTime = 8;
    public static final int STARTTIME_FIELD_NUMBER = 8;
    private java.lang.Object startTime_;
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getStartTime() {
      java.lang.Object ref = startTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          startTime_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getStartTimeBytes() {
      java.lang.Object ref = startTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        startTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string endTime = 9;
    public static final int ENDTIME_FIELD_NUMBER = 9;
    private java.lang.Object endTime_;
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getEndTime() {
      java.lang.Object ref = endTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          endTime_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEndTimeBytes() {
      java.lang.Object ref = endTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        endTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string rewardTime = 10;
    public static final int REWARDTIME_FIELD_NUMBER = 10;
    private java.lang.Object rewardTime_;
    public boolean hasRewardTime() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getRewardTime() {
      java.lang.Object ref = rewardTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          rewardTime_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRewardTimeBytes() {
      java.lang.Object ref = rewardTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        rewardTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      todayTitle_ = 0;
      playerRank_ = java.util.Collections.emptyList();
      myData_ = com.ftkj.proto.LimitChallengePB.LimitChallengeRank.getDefaultInstance();
      leftChallengeNum_ = 0;
      cdEndTime_ = 0;
      buyNum_ = 0;
      npcId_ = 0;
      startTime_ = "";
      endTime_ = "";
      rewardTime_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, todayTitle_);
      }
      for (int i = 0; i < playerRank_.size(); i++) {
        output.writeMessage(2, playerRank_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(3, myData_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, leftChallengeNum_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(5, cdEndTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(6, buyNum_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(7, npcId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(8, getStartTimeBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(9, getEndTimeBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(10, getRewardTimeBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, todayTitle_);
      }
      for (int i = 0; i < playerRank_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, playerRank_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, myData_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, leftChallengeNum_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, cdEndTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, buyNum_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, npcId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getStartTimeBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getEndTimeBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getRewardTimeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.ftkj.proto.LimitChallengePB.LimitChallengeView parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.LimitChallengePB.LimitChallengeView parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.LimitChallengePB.LimitChallengeView parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.LimitChallengePB.LimitChallengeView parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.LimitChallengePB.LimitChallengeView parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.LimitChallengePB.LimitChallengeView parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.LimitChallengePB.LimitChallengeView parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.LimitChallengePB.LimitChallengeView parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.LimitChallengePB.LimitChallengeView parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.LimitChallengePB.LimitChallengeView parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ftkj.proto.LimitChallengePB.LimitChallengeView prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ftkj.proto.LimitChallengePB.LimitChallengeViewOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ftkj.proto.LimitChallengePB.internal_static_com_ftkj_proto_LimitChallengeView_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ftkj.proto.LimitChallengePB.internal_static_com_ftkj_proto_LimitChallengeView_fieldAccessorTable;
      }
      
      // Construct using com.ftkj.proto.LimitChallengePB.LimitChallengeView.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPlayerRankFieldBuilder();
          getMyDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        todayTitle_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (playerRankBuilder_ == null) {
          playerRank_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          playerRankBuilder_.clear();
        }
        if (myDataBuilder_ == null) {
          myData_ = com.ftkj.proto.LimitChallengePB.LimitChallengeRank.getDefaultInstance();
        } else {
          myDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        leftChallengeNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        cdEndTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        buyNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        npcId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        startTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        endTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        rewardTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ftkj.proto.LimitChallengePB.LimitChallengeView.getDescriptor();
      }
      
      public com.ftkj.proto.LimitChallengePB.LimitChallengeView getDefaultInstanceForType() {
        return com.ftkj.proto.LimitChallengePB.LimitChallengeView.getDefaultInstance();
      }
      
      public com.ftkj.proto.LimitChallengePB.LimitChallengeView build() {
        com.ftkj.proto.LimitChallengePB.LimitChallengeView result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.ftkj.proto.LimitChallengePB.LimitChallengeView buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.ftkj.proto.LimitChallengePB.LimitChallengeView result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.ftkj.proto.LimitChallengePB.LimitChallengeView buildPartial() {
        com.ftkj.proto.LimitChallengePB.LimitChallengeView result = new com.ftkj.proto.LimitChallengePB.LimitChallengeView(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.todayTitle_ = todayTitle_;
        if (playerRankBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            playerRank_ = java.util.Collections.unmodifiableList(playerRank_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.playerRank_ = playerRank_;
        } else {
          result.playerRank_ = playerRankBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        if (myDataBuilder_ == null) {
          result.myData_ = myData_;
        } else {
          result.myData_ = myDataBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.leftChallengeNum_ = leftChallengeNum_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.cdEndTime_ = cdEndTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.buyNum_ = buyNum_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.npcId_ = npcId_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        result.startTime_ = startTime_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000080;
        }
        result.endTime_ = endTime_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000100;
        }
        result.rewardTime_ = rewardTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ftkj.proto.LimitChallengePB.LimitChallengeView) {
          return mergeFrom((com.ftkj.proto.LimitChallengePB.LimitChallengeView)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.ftkj.proto.LimitChallengePB.LimitChallengeView other) {
        if (other == com.ftkj.proto.LimitChallengePB.LimitChallengeView.getDefaultInstance()) return this;
        if (other.hasTodayTitle()) {
          setTodayTitle(other.getTodayTitle());
        }
        if (playerRankBuilder_ == null) {
          if (!other.playerRank_.isEmpty()) {
            if (playerRank_.isEmpty()) {
              playerRank_ = other.playerRank_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePlayerRankIsMutable();
              playerRank_.addAll(other.playerRank_);
            }
            onChanged();
          }
        } else {
          if (!other.playerRank_.isEmpty()) {
            if (playerRankBuilder_.isEmpty()) {
              playerRankBuilder_.dispose();
              playerRankBuilder_ = null;
              playerRank_ = other.playerRank_;
              bitField0_ = (bitField0_ & ~0x00000002);
              playerRankBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPlayerRankFieldBuilder() : null;
            } else {
              playerRankBuilder_.addAllMessages(other.playerRank_);
            }
          }
        }
        if (other.hasMyData()) {
          mergeMyData(other.getMyData());
        }
        if (other.hasLeftChallengeNum()) {
          setLeftChallengeNum(other.getLeftChallengeNum());
        }
        if (other.hasCdEndTime()) {
          setCdEndTime(other.getCdEndTime());
        }
        if (other.hasBuyNum()) {
          setBuyNum(other.getBuyNum());
        }
        if (other.hasNpcId()) {
          setNpcId(other.getNpcId());
        }
        if (other.hasStartTime()) {
          setStartTime(other.getStartTime());
        }
        if (other.hasEndTime()) {
          setEndTime(other.getEndTime());
        }
        if (other.hasRewardTime()) {
          setRewardTime(other.getRewardTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              todayTitle_ = input.readInt32();
              break;
            }
            case 18: {
              com.ftkj.proto.LimitChallengePB.LimitChallengeRank.Builder subBuilder = com.ftkj.proto.LimitChallengePB.LimitChallengeRank.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPlayerRank(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.ftkj.proto.LimitChallengePB.LimitChallengeRank.Builder subBuilder = com.ftkj.proto.LimitChallengePB.LimitChallengeRank.newBuilder();
              if (hasMyData()) {
                subBuilder.mergeFrom(getMyData());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMyData(subBuilder.buildPartial());
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              leftChallengeNum_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              cdEndTime_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              buyNum_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              npcId_ = input.readInt32();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              startTime_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              endTime_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              rewardTime_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 todayTitle = 1;
      private int todayTitle_ ;
      public boolean hasTodayTitle() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getTodayTitle() {
        return todayTitle_;
      }
      public Builder setTodayTitle(int value) {
        bitField0_ |= 0x00000001;
        todayTitle_ = value;
        onChanged();
        return this;
      }
      public Builder clearTodayTitle() {
        bitField0_ = (bitField0_ & ~0x00000001);
        todayTitle_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .com.ftkj.proto.LimitChallengeRank playerRank = 2;
      private java.util.List<com.ftkj.proto.LimitChallengePB.LimitChallengeRank> playerRank_ =
        java.util.Collections.emptyList();
      private void ensurePlayerRankIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          playerRank_ = new java.util.ArrayList<com.ftkj.proto.LimitChallengePB.LimitChallengeRank>(playerRank_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ftkj.proto.LimitChallengePB.LimitChallengeRank, com.ftkj.proto.LimitChallengePB.LimitChallengeRank.Builder, com.ftkj.proto.LimitChallengePB.LimitChallengeRankOrBuilder> playerRankBuilder_;
      
      public java.util.List<com.ftkj.proto.LimitChallengePB.LimitChallengeRank> getPlayerRankList() {
        if (playerRankBuilder_ == null) {
          return java.util.Collections.unmodifiableList(playerRank_);
        } else {
          return playerRankBuilder_.getMessageList();
        }
      }
      public int getPlayerRankCount() {
        if (playerRankBuilder_ == null) {
          return playerRank_.size();
        } else {
          return playerRankBuilder_.getCount();
        }
      }
      public com.ftkj.proto.LimitChallengePB.LimitChallengeRank getPlayerRank(int index) {
        if (playerRankBuilder_ == null) {
          return playerRank_.get(index);
        } else {
          return playerRankBuilder_.getMessage(index);
        }
      }
      public Builder setPlayerRank(
          int index, com.ftkj.proto.LimitChallengePB.LimitChallengeRank value) {
        if (playerRankBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayerRankIsMutable();
          playerRank_.set(index, value);
          onChanged();
        } else {
          playerRankBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setPlayerRank(
          int index, com.ftkj.proto.LimitChallengePB.LimitChallengeRank.Builder builderForValue) {
        if (playerRankBuilder_ == null) {
          ensurePlayerRankIsMutable();
          playerRank_.set(index, builderForValue.build());
          onChanged();
        } else {
          playerRankBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addPlayerRank(com.ftkj.proto.LimitChallengePB.LimitChallengeRank value) {
        if (playerRankBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayerRankIsMutable();
          playerRank_.add(value);
          onChanged();
        } else {
          playerRankBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addPlayerRank(
          int index, com.ftkj.proto.LimitChallengePB.LimitChallengeRank value) {
        if (playerRankBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayerRankIsMutable();
          playerRank_.add(index, value);
          onChanged();
        } else {
          playerRankBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addPlayerRank(
          com.ftkj.proto.LimitChallengePB.LimitChallengeRank.Builder builderForValue) {
        if (playerRankBuilder_ == null) {
          ensurePlayerRankIsMutable();
          playerRank_.add(builderForValue.build());
          onChanged();
        } else {
          playerRankBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addPlayerRank(
          int index, com.ftkj.proto.LimitChallengePB.LimitChallengeRank.Builder builderForValue) {
        if (playerRankBuilder_ == null) {
          ensurePlayerRankIsMutable();
          playerRank_.add(index, builderForValue.build());
          onChanged();
        } else {
          playerRankBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllPlayerRank(
          java.lang.Iterable<? extends com.ftkj.proto.LimitChallengePB.LimitChallengeRank> values) {
        if (playerRankBuilder_ == null) {
          ensurePlayerRankIsMutable();
          super.addAll(values, playerRank_);
          onChanged();
        } else {
          playerRankBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearPlayerRank() {
        if (playerRankBuilder_ == null) {
          playerRank_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          playerRankBuilder_.clear();
        }
        return this;
      }
      public Builder removePlayerRank(int index) {
        if (playerRankBuilder_ == null) {
          ensurePlayerRankIsMutable();
          playerRank_.remove(index);
          onChanged();
        } else {
          playerRankBuilder_.remove(index);
        }
        return this;
      }
      public com.ftkj.proto.LimitChallengePB.LimitChallengeRank.Builder getPlayerRankBuilder(
          int index) {
        return getPlayerRankFieldBuilder().getBuilder(index);
      }
      public com.ftkj.proto.LimitChallengePB.LimitChallengeRankOrBuilder getPlayerRankOrBuilder(
          int index) {
        if (playerRankBuilder_ == null) {
          return playerRank_.get(index);  } else {
          return playerRankBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.ftkj.proto.LimitChallengePB.LimitChallengeRankOrBuilder> 
           getPlayerRankOrBuilderList() {
        if (playerRankBuilder_ != null) {
          return playerRankBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(playerRank_);
        }
      }
      public com.ftkj.proto.LimitChallengePB.LimitChallengeRank.Builder addPlayerRankBuilder() {
        return getPlayerRankFieldBuilder().addBuilder(
            com.ftkj.proto.LimitChallengePB.LimitChallengeRank.getDefaultInstance());
      }
      public com.ftkj.proto.LimitChallengePB.LimitChallengeRank.Builder addPlayerRankBuilder(
          int index) {
        return getPlayerRankFieldBuilder().addBuilder(
            index, com.ftkj.proto.LimitChallengePB.LimitChallengeRank.getDefaultInstance());
      }
      public java.util.List<com.ftkj.proto.LimitChallengePB.LimitChallengeRank.Builder> 
           getPlayerRankBuilderList() {
        return getPlayerRankFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ftkj.proto.LimitChallengePB.LimitChallengeRank, com.ftkj.proto.LimitChallengePB.LimitChallengeRank.Builder, com.ftkj.proto.LimitChallengePB.LimitChallengeRankOrBuilder> 
          getPlayerRankFieldBuilder() {
        if (playerRankBuilder_ == null) {
          playerRankBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.ftkj.proto.LimitChallengePB.LimitChallengeRank, com.ftkj.proto.LimitChallengePB.LimitChallengeRank.Builder, com.ftkj.proto.LimitChallengePB.LimitChallengeRankOrBuilder>(
                  playerRank_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          playerRank_ = null;
        }
        return playerRankBuilder_;
      }
      
      // optional .com.ftkj.proto.LimitChallengeRank myData = 3;
      private com.ftkj.proto.LimitChallengePB.LimitChallengeRank myData_ = com.ftkj.proto.LimitChallengePB.LimitChallengeRank.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.ftkj.proto.LimitChallengePB.LimitChallengeRank, com.ftkj.proto.LimitChallengePB.LimitChallengeRank.Builder, com.ftkj.proto.LimitChallengePB.LimitChallengeRankOrBuilder> myDataBuilder_;
      public boolean hasMyData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.ftkj.proto.LimitChallengePB.LimitChallengeRank getMyData() {
        if (myDataBuilder_ == null) {
          return myData_;
        } else {
          return myDataBuilder_.getMessage();
        }
      }
      public Builder setMyData(com.ftkj.proto.LimitChallengePB.LimitChallengeRank value) {
        if (myDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          myData_ = value;
          onChanged();
        } else {
          myDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setMyData(
          com.ftkj.proto.LimitChallengePB.LimitChallengeRank.Builder builderForValue) {
        if (myDataBuilder_ == null) {
          myData_ = builderForValue.build();
          onChanged();
        } else {
          myDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeMyData(com.ftkj.proto.LimitChallengePB.LimitChallengeRank value) {
        if (myDataBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              myData_ != com.ftkj.proto.LimitChallengePB.LimitChallengeRank.getDefaultInstance()) {
            myData_ =
              com.ftkj.proto.LimitChallengePB.LimitChallengeRank.newBuilder(myData_).mergeFrom(value).buildPartial();
          } else {
            myData_ = value;
          }
          onChanged();
        } else {
          myDataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearMyData() {
        if (myDataBuilder_ == null) {
          myData_ = com.ftkj.proto.LimitChallengePB.LimitChallengeRank.getDefaultInstance();
          onChanged();
        } else {
          myDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public com.ftkj.proto.LimitChallengePB.LimitChallengeRank.Builder getMyDataBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getMyDataFieldBuilder().getBuilder();
      }
      public com.ftkj.proto.LimitChallengePB.LimitChallengeRankOrBuilder getMyDataOrBuilder() {
        if (myDataBuilder_ != null) {
          return myDataBuilder_.getMessageOrBuilder();
        } else {
          return myData_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.ftkj.proto.LimitChallengePB.LimitChallengeRank, com.ftkj.proto.LimitChallengePB.LimitChallengeRank.Builder, com.ftkj.proto.LimitChallengePB.LimitChallengeRankOrBuilder> 
          getMyDataFieldBuilder() {
        if (myDataBuilder_ == null) {
          myDataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.ftkj.proto.LimitChallengePB.LimitChallengeRank, com.ftkj.proto.LimitChallengePB.LimitChallengeRank.Builder, com.ftkj.proto.LimitChallengePB.LimitChallengeRankOrBuilder>(
                  myData_,
                  getParentForChildren(),
                  isClean());
          myData_ = null;
        }
        return myDataBuilder_;
      }
      
      // optional int32 leftChallengeNum = 4;
      private int leftChallengeNum_ ;
      public boolean hasLeftChallengeNum() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getLeftChallengeNum() {
        return leftChallengeNum_;
      }
      public Builder setLeftChallengeNum(int value) {
        bitField0_ |= 0x00000008;
        leftChallengeNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearLeftChallengeNum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        leftChallengeNum_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 cdEndTime = 5;
      private int cdEndTime_ ;
      public boolean hasCdEndTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getCdEndTime() {
        return cdEndTime_;
      }
      public Builder setCdEndTime(int value) {
        bitField0_ |= 0x00000010;
        cdEndTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearCdEndTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        cdEndTime_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 buyNum = 6;
      private int buyNum_ ;
      public boolean hasBuyNum() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getBuyNum() {
        return buyNum_;
      }
      public Builder setBuyNum(int value) {
        bitField0_ |= 0x00000020;
        buyNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearBuyNum() {
        bitField0_ = (bitField0_ & ~0x00000020);
        buyNum_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 npcId = 7;
      private int npcId_ ;
      public boolean hasNpcId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getNpcId() {
        return npcId_;
      }
      public Builder setNpcId(int value) {
        bitField0_ |= 0x00000040;
        npcId_ = value;
        onChanged();
        return this;
      }
      public Builder clearNpcId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        npcId_ = 0;
        onChanged();
        return this;
      }
      
      // optional string startTime = 8;
      private java.lang.Object startTime_ = "";
      public boolean hasStartTime() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getStartTime() {
        java.lang.Object ref = startTime_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          startTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setStartTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        startTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000080);
        startTime_ = getDefaultInstance().getStartTime();
        onChanged();
        return this;
      }
      void setStartTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        startTime_ = value;
        onChanged();
      }
      
      // optional string endTime = 9;
      private java.lang.Object endTime_ = "";
      public boolean hasEndTime() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getEndTime() {
        java.lang.Object ref = endTime_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          endTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEndTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        endTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000100);
        endTime_ = getDefaultInstance().getEndTime();
        onChanged();
        return this;
      }
      void setEndTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        endTime_ = value;
        onChanged();
      }
      
      // optional string rewardTime = 10;
      private java.lang.Object rewardTime_ = "";
      public boolean hasRewardTime() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getRewardTime() {
        java.lang.Object ref = rewardTime_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          rewardTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRewardTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        rewardTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearRewardTime() {
        bitField0_ = (bitField0_ & ~0x00000200);
        rewardTime_ = getDefaultInstance().getRewardTime();
        onChanged();
        return this;
      }
      void setRewardTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        rewardTime_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.ftkj.proto.LimitChallengeView)
    }
    
    static {
      defaultInstance = new LimitChallengeView(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ftkj.proto.LimitChallengeView)
  }
  
  public interface LimitChallengeRankOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 serverId = 1;
    boolean hasServerId();
    int getServerId();
    
    // optional string teamName = 2;
    boolean hasTeamName();
    String getTeamName();
    
    // optional int32 df = 3;
    boolean hasDf();
    int getDf();
    
    // optional int32 lb = 4;
    boolean hasLb();
    int getLb();
    
    // optional int32 zg = 5;
    boolean hasZg();
    int getZg();
    
    // optional int32 qd = 6;
    boolean hasQd();
    int getQd();
    
    // optional int32 gm = 7;
    boolean hasGm();
    int getGm();
    
    // optional int32 rank = 8;
    boolean hasRank();
    int getRank();
  }
  public static final class LimitChallengeRank extends
      com.google.protobuf.GeneratedMessage
      implements LimitChallengeRankOrBuilder {
    // Use LimitChallengeRank.newBuilder() to construct.
    private LimitChallengeRank(Builder builder) {
      super(builder);
    }
    private LimitChallengeRank(boolean noInit) {}
    
    private static final LimitChallengeRank defaultInstance;
    public static LimitChallengeRank getDefaultInstance() {
      return defaultInstance;
    }
    
    public LimitChallengeRank getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ftkj.proto.LimitChallengePB.internal_static_com_ftkj_proto_LimitChallengeRank_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ftkj.proto.LimitChallengePB.internal_static_com_ftkj_proto_LimitChallengeRank_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 serverId = 1;
    public static final int SERVERID_FIELD_NUMBER = 1;
    private int serverId_;
    public boolean hasServerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getServerId() {
      return serverId_;
    }
    
    // optional string teamName = 2;
    public static final int TEAMNAME_FIELD_NUMBER = 2;
    private java.lang.Object teamName_;
    public boolean hasTeamName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTeamName() {
      java.lang.Object ref = teamName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          teamName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTeamNameBytes() {
      java.lang.Object ref = teamName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        teamName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 df = 3;
    public static final int DF_FIELD_NUMBER = 3;
    private int df_;
    public boolean hasDf() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getDf() {
      return df_;
    }
    
    // optional int32 lb = 4;
    public static final int LB_FIELD_NUMBER = 4;
    private int lb_;
    public boolean hasLb() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getLb() {
      return lb_;
    }
    
    // optional int32 zg = 5;
    public static final int ZG_FIELD_NUMBER = 5;
    private int zg_;
    public boolean hasZg() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getZg() {
      return zg_;
    }
    
    // optional int32 qd = 6;
    public static final int QD_FIELD_NUMBER = 6;
    private int qd_;
    public boolean hasQd() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getQd() {
      return qd_;
    }
    
    // optional int32 gm = 7;
    public static final int GM_FIELD_NUMBER = 7;
    private int gm_;
    public boolean hasGm() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getGm() {
      return gm_;
    }
    
    // optional int32 rank = 8;
    public static final int RANK_FIELD_NUMBER = 8;
    private int rank_;
    public boolean hasRank() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public int getRank() {
      return rank_;
    }
    
    private void initFields() {
      serverId_ = 0;
      teamName_ = "";
      df_ = 0;
      lb_ = 0;
      zg_ = 0;
      qd_ = 0;
      gm_ = 0;
      rank_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, serverId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTeamNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, df_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, lb_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, zg_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, qd_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, gm_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, rank_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serverId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTeamNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, df_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, lb_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, zg_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, qd_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, gm_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, rank_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.ftkj.proto.LimitChallengePB.LimitChallengeRank parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.LimitChallengePB.LimitChallengeRank parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.LimitChallengePB.LimitChallengeRank parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.LimitChallengePB.LimitChallengeRank parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.LimitChallengePB.LimitChallengeRank parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.LimitChallengePB.LimitChallengeRank parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.LimitChallengePB.LimitChallengeRank parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.LimitChallengePB.LimitChallengeRank parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.LimitChallengePB.LimitChallengeRank parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.LimitChallengePB.LimitChallengeRank parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ftkj.proto.LimitChallengePB.LimitChallengeRank prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ftkj.proto.LimitChallengePB.LimitChallengeRankOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ftkj.proto.LimitChallengePB.internal_static_com_ftkj_proto_LimitChallengeRank_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ftkj.proto.LimitChallengePB.internal_static_com_ftkj_proto_LimitChallengeRank_fieldAccessorTable;
      }
      
      // Construct using com.ftkj.proto.LimitChallengePB.LimitChallengeRank.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        serverId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        teamName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        df_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        lb_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        zg_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        qd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        gm_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        rank_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ftkj.proto.LimitChallengePB.LimitChallengeRank.getDescriptor();
      }
      
      public com.ftkj.proto.LimitChallengePB.LimitChallengeRank getDefaultInstanceForType() {
        return com.ftkj.proto.LimitChallengePB.LimitChallengeRank.getDefaultInstance();
      }
      
      public com.ftkj.proto.LimitChallengePB.LimitChallengeRank build() {
        com.ftkj.proto.LimitChallengePB.LimitChallengeRank result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.ftkj.proto.LimitChallengePB.LimitChallengeRank buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.ftkj.proto.LimitChallengePB.LimitChallengeRank result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.ftkj.proto.LimitChallengePB.LimitChallengeRank buildPartial() {
        com.ftkj.proto.LimitChallengePB.LimitChallengeRank result = new com.ftkj.proto.LimitChallengePB.LimitChallengeRank(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverId_ = serverId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.teamName_ = teamName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.df_ = df_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.lb_ = lb_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.zg_ = zg_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.qd_ = qd_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.gm_ = gm_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.rank_ = rank_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ftkj.proto.LimitChallengePB.LimitChallengeRank) {
          return mergeFrom((com.ftkj.proto.LimitChallengePB.LimitChallengeRank)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.ftkj.proto.LimitChallengePB.LimitChallengeRank other) {
        if (other == com.ftkj.proto.LimitChallengePB.LimitChallengeRank.getDefaultInstance()) return this;
        if (other.hasServerId()) {
          setServerId(other.getServerId());
        }
        if (other.hasTeamName()) {
          setTeamName(other.getTeamName());
        }
        if (other.hasDf()) {
          setDf(other.getDf());
        }
        if (other.hasLb()) {
          setLb(other.getLb());
        }
        if (other.hasZg()) {
          setZg(other.getZg());
        }
        if (other.hasQd()) {
          setQd(other.getQd());
        }
        if (other.hasGm()) {
          setGm(other.getGm());
        }
        if (other.hasRank()) {
          setRank(other.getRank());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serverId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              teamName_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              df_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              lb_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              zg_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              qd_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              gm_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              rank_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 serverId = 1;
      private int serverId_ ;
      public boolean hasServerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getServerId() {
        return serverId_;
      }
      public Builder setServerId(int value) {
        bitField0_ |= 0x00000001;
        serverId_ = value;
        onChanged();
        return this;
      }
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverId_ = 0;
        onChanged();
        return this;
      }
      
      // optional string teamName = 2;
      private java.lang.Object teamName_ = "";
      public boolean hasTeamName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTeamName() {
        java.lang.Object ref = teamName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          teamName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTeamName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        teamName_ = value;
        onChanged();
        return this;
      }
      public Builder clearTeamName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        teamName_ = getDefaultInstance().getTeamName();
        onChanged();
        return this;
      }
      void setTeamName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        teamName_ = value;
        onChanged();
      }
      
      // optional int32 df = 3;
      private int df_ ;
      public boolean hasDf() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getDf() {
        return df_;
      }
      public Builder setDf(int value) {
        bitField0_ |= 0x00000004;
        df_ = value;
        onChanged();
        return this;
      }
      public Builder clearDf() {
        bitField0_ = (bitField0_ & ~0x00000004);
        df_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 lb = 4;
      private int lb_ ;
      public boolean hasLb() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getLb() {
        return lb_;
      }
      public Builder setLb(int value) {
        bitField0_ |= 0x00000008;
        lb_ = value;
        onChanged();
        return this;
      }
      public Builder clearLb() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lb_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 zg = 5;
      private int zg_ ;
      public boolean hasZg() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getZg() {
        return zg_;
      }
      public Builder setZg(int value) {
        bitField0_ |= 0x00000010;
        zg_ = value;
        onChanged();
        return this;
      }
      public Builder clearZg() {
        bitField0_ = (bitField0_ & ~0x00000010);
        zg_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 qd = 6;
      private int qd_ ;
      public boolean hasQd() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getQd() {
        return qd_;
      }
      public Builder setQd(int value) {
        bitField0_ |= 0x00000020;
        qd_ = value;
        onChanged();
        return this;
      }
      public Builder clearQd() {
        bitField0_ = (bitField0_ & ~0x00000020);
        qd_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 gm = 7;
      private int gm_ ;
      public boolean hasGm() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getGm() {
        return gm_;
      }
      public Builder setGm(int value) {
        bitField0_ |= 0x00000040;
        gm_ = value;
        onChanged();
        return this;
      }
      public Builder clearGm() {
        bitField0_ = (bitField0_ & ~0x00000040);
        gm_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 rank = 8;
      private int rank_ ;
      public boolean hasRank() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public int getRank() {
        return rank_;
      }
      public Builder setRank(int value) {
        bitField0_ |= 0x00000080;
        rank_ = value;
        onChanged();
        return this;
      }
      public Builder clearRank() {
        bitField0_ = (bitField0_ & ~0x00000080);
        rank_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.ftkj.proto.LimitChallengeRank)
    }
    
    static {
      defaultInstance = new LimitChallengeRank(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ftkj.proto.LimitChallengeRank)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ftkj_proto_LimitChallengeView_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ftkj_proto_LimitChallengeView_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ftkj_proto_LimitChallengeRank_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ftkj_proto_LimitChallengeRank_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024LimitChallenge.proto\022\016com.ftkj.proto\"\230" +
      "\002\n\022LimitChallengeView\022\022\n\ntodayTitle\030\001 \001(" +
      "\005\0226\n\nplayerRank\030\002 \003(\0132\".com.ftkj.proto.L" +
      "imitChallengeRank\0222\n\006myData\030\003 \001(\0132\".com." +
      "ftkj.proto.LimitChallengeRank\022\030\n\020leftCha" +
      "llengeNum\030\004 \001(\005\022\021\n\tcdEndTime\030\005 \001(\005\022\016\n\006bu" +
      "yNum\030\006 \001(\005\022\r\n\005npcId\030\007 \001(\005\022\021\n\tstartTime\030\010" +
      " \001(\t\022\017\n\007endTime\030\t \001(\t\022\022\n\nrewardTime\030\n \001(" +
      "\t\"\202\001\n\022LimitChallengeRank\022\020\n\010serverId\030\001 \001" +
      "(\005\022\020\n\010teamName\030\002 \001(\t\022\n\n\002df\030\003 \001(\005\022\n\n\002lb\030\004",
      " \001(\005\022\n\n\002zg\030\005 \001(\005\022\n\n\002qd\030\006 \001(\005\022\n\n\002gm\030\007 \001(\005" +
      "\022\014\n\004rank\030\010 \001(\005B\022B\020LimitChallengePB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_ftkj_proto_LimitChallengeView_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_ftkj_proto_LimitChallengeView_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ftkj_proto_LimitChallengeView_descriptor,
              new java.lang.String[] { "TodayTitle", "PlayerRank", "MyData", "LeftChallengeNum", "CdEndTime", "BuyNum", "NpcId", "StartTime", "EndTime", "RewardTime", },
              com.ftkj.proto.LimitChallengePB.LimitChallengeView.class,
              com.ftkj.proto.LimitChallengePB.LimitChallengeView.Builder.class);
          internal_static_com_ftkj_proto_LimitChallengeRank_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_ftkj_proto_LimitChallengeRank_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ftkj_proto_LimitChallengeRank_descriptor,
              new java.lang.String[] { "ServerId", "TeamName", "Df", "Lb", "Zg", "Qd", "Gm", "Rank", },
              com.ftkj.proto.LimitChallengePB.LimitChallengeRank.class,
              com.ftkj.proto.LimitChallengePB.LimitChallengeRank.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
