// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerInvestment.proto

package com.ftkj.proto;

public final class PlayerInvestmentPB {
  private PlayerInvestmentPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TeamInvestmentMainDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .com.ftkj.proto.TeamInvestmentInfoData teamInfo = 1;
    boolean hasTeamInfo();
    com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData getTeamInfo();
    com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoDataOrBuilder getTeamInfoOrBuilder();
    
    // repeated .com.ftkj.proto.TeamPlayerInvestmentData players = 2;
    java.util.List<com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData> 
        getPlayersList();
    com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData getPlayers(int index);
    int getPlayersCount();
    java.util.List<? extends com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentDataOrBuilder> 
        getPlayersOrBuilderList();
    com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentDataOrBuilder getPlayersOrBuilder(
        int index);
  }
  public static final class TeamInvestmentMainData extends
      com.google.protobuf.GeneratedMessage
      implements TeamInvestmentMainDataOrBuilder {
    // Use TeamInvestmentMainData.newBuilder() to construct.
    private TeamInvestmentMainData(Builder builder) {
      super(builder);
    }
    private TeamInvestmentMainData(boolean noInit) {}
    
    private static final TeamInvestmentMainData defaultInstance;
    public static TeamInvestmentMainData getDefaultInstance() {
      return defaultInstance;
    }
    
    public TeamInvestmentMainData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ftkj.proto.PlayerInvestmentPB.internal_static_com_ftkj_proto_TeamInvestmentMainData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ftkj.proto.PlayerInvestmentPB.internal_static_com_ftkj_proto_TeamInvestmentMainData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .com.ftkj.proto.TeamInvestmentInfoData teamInfo = 1;
    public static final int TEAMINFO_FIELD_NUMBER = 1;
    private com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData teamInfo_;
    public boolean hasTeamInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData getTeamInfo() {
      return teamInfo_;
    }
    public com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoDataOrBuilder getTeamInfoOrBuilder() {
      return teamInfo_;
    }
    
    // repeated .com.ftkj.proto.TeamPlayerInvestmentData players = 2;
    public static final int PLAYERS_FIELD_NUMBER = 2;
    private java.util.List<com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData> players_;
    public java.util.List<com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData> getPlayersList() {
      return players_;
    }
    public java.util.List<? extends com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentDataOrBuilder> 
        getPlayersOrBuilderList() {
      return players_;
    }
    public int getPlayersCount() {
      return players_.size();
    }
    public com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData getPlayers(int index) {
      return players_.get(index);
    }
    public com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentDataOrBuilder getPlayersOrBuilder(
        int index) {
      return players_.get(index);
    }
    
    private void initFields() {
      teamInfo_ = com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData.getDefaultInstance();
      players_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTeamInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getTeamInfo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPlayersCount(); i++) {
        if (!getPlayers(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, teamInfo_);
      }
      for (int i = 0; i < players_.size(); i++) {
        output.writeMessage(2, players_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, teamInfo_);
      }
      for (int i = 0; i < players_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, players_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ftkj.proto.PlayerInvestmentPB.internal_static_com_ftkj_proto_TeamInvestmentMainData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ftkj.proto.PlayerInvestmentPB.internal_static_com_ftkj_proto_TeamInvestmentMainData_fieldAccessorTable;
      }
      
      // Construct using com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTeamInfoFieldBuilder();
          getPlayersFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (teamInfoBuilder_ == null) {
          teamInfo_ = com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData.getDefaultInstance();
        } else {
          teamInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (playersBuilder_ == null) {
          players_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          playersBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData.getDescriptor();
      }
      
      public com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData getDefaultInstanceForType() {
        return com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData.getDefaultInstance();
      }
      
      public com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData build() {
        com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData buildPartial() {
        com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData result = new com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (teamInfoBuilder_ == null) {
          result.teamInfo_ = teamInfo_;
        } else {
          result.teamInfo_ = teamInfoBuilder_.build();
        }
        if (playersBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            players_ = java.util.Collections.unmodifiableList(players_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.players_ = players_;
        } else {
          result.players_ = playersBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData) {
          return mergeFrom((com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData other) {
        if (other == com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData.getDefaultInstance()) return this;
        if (other.hasTeamInfo()) {
          mergeTeamInfo(other.getTeamInfo());
        }
        if (playersBuilder_ == null) {
          if (!other.players_.isEmpty()) {
            if (players_.isEmpty()) {
              players_ = other.players_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePlayersIsMutable();
              players_.addAll(other.players_);
            }
            onChanged();
          }
        } else {
          if (!other.players_.isEmpty()) {
            if (playersBuilder_.isEmpty()) {
              playersBuilder_.dispose();
              playersBuilder_ = null;
              players_ = other.players_;
              bitField0_ = (bitField0_ & ~0x00000002);
              playersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPlayersFieldBuilder() : null;
            } else {
              playersBuilder_.addAllMessages(other.players_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTeamInfo()) {
          
          return false;
        }
        if (!getTeamInfo().isInitialized()) {
          
          return false;
        }
        for (int i = 0; i < getPlayersCount(); i++) {
          if (!getPlayers(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData.Builder subBuilder = com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData.newBuilder();
              if (hasTeamInfo()) {
                subBuilder.mergeFrom(getTeamInfo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setTeamInfo(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData.Builder subBuilder = com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPlayers(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .com.ftkj.proto.TeamInvestmentInfoData teamInfo = 1;
      private com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData teamInfo_ = com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData, com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData.Builder, com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoDataOrBuilder> teamInfoBuilder_;
      public boolean hasTeamInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData getTeamInfo() {
        if (teamInfoBuilder_ == null) {
          return teamInfo_;
        } else {
          return teamInfoBuilder_.getMessage();
        }
      }
      public Builder setTeamInfo(com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData value) {
        if (teamInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          teamInfo_ = value;
          onChanged();
        } else {
          teamInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setTeamInfo(
          com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData.Builder builderForValue) {
        if (teamInfoBuilder_ == null) {
          teamInfo_ = builderForValue.build();
          onChanged();
        } else {
          teamInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeTeamInfo(com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData value) {
        if (teamInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              teamInfo_ != com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData.getDefaultInstance()) {
            teamInfo_ =
              com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData.newBuilder(teamInfo_).mergeFrom(value).buildPartial();
          } else {
            teamInfo_ = value;
          }
          onChanged();
        } else {
          teamInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearTeamInfo() {
        if (teamInfoBuilder_ == null) {
          teamInfo_ = com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData.getDefaultInstance();
          onChanged();
        } else {
          teamInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData.Builder getTeamInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getTeamInfoFieldBuilder().getBuilder();
      }
      public com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoDataOrBuilder getTeamInfoOrBuilder() {
        if (teamInfoBuilder_ != null) {
          return teamInfoBuilder_.getMessageOrBuilder();
        } else {
          return teamInfo_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData, com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData.Builder, com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoDataOrBuilder> 
          getTeamInfoFieldBuilder() {
        if (teamInfoBuilder_ == null) {
          teamInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData, com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData.Builder, com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoDataOrBuilder>(
                  teamInfo_,
                  getParentForChildren(),
                  isClean());
          teamInfo_ = null;
        }
        return teamInfoBuilder_;
      }
      
      // repeated .com.ftkj.proto.TeamPlayerInvestmentData players = 2;
      private java.util.List<com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData> players_ =
        java.util.Collections.emptyList();
      private void ensurePlayersIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          players_ = new java.util.ArrayList<com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData>(players_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData, com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData.Builder, com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentDataOrBuilder> playersBuilder_;
      
      public java.util.List<com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData> getPlayersList() {
        if (playersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(players_);
        } else {
          return playersBuilder_.getMessageList();
        }
      }
      public int getPlayersCount() {
        if (playersBuilder_ == null) {
          return players_.size();
        } else {
          return playersBuilder_.getCount();
        }
      }
      public com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData getPlayers(int index) {
        if (playersBuilder_ == null) {
          return players_.get(index);
        } else {
          return playersBuilder_.getMessage(index);
        }
      }
      public Builder setPlayers(
          int index, com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData value) {
        if (playersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayersIsMutable();
          players_.set(index, value);
          onChanged();
        } else {
          playersBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setPlayers(
          int index, com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData.Builder builderForValue) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.set(index, builderForValue.build());
          onChanged();
        } else {
          playersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addPlayers(com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData value) {
        if (playersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayersIsMutable();
          players_.add(value);
          onChanged();
        } else {
          playersBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addPlayers(
          int index, com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData value) {
        if (playersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayersIsMutable();
          players_.add(index, value);
          onChanged();
        } else {
          playersBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addPlayers(
          com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData.Builder builderForValue) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.add(builderForValue.build());
          onChanged();
        } else {
          playersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addPlayers(
          int index, com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData.Builder builderForValue) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.add(index, builderForValue.build());
          onChanged();
        } else {
          playersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllPlayers(
          java.lang.Iterable<? extends com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData> values) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          super.addAll(values, players_);
          onChanged();
        } else {
          playersBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearPlayers() {
        if (playersBuilder_ == null) {
          players_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          playersBuilder_.clear();
        }
        return this;
      }
      public Builder removePlayers(int index) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.remove(index);
          onChanged();
        } else {
          playersBuilder_.remove(index);
        }
        return this;
      }
      public com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData.Builder getPlayersBuilder(
          int index) {
        return getPlayersFieldBuilder().getBuilder(index);
      }
      public com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentDataOrBuilder getPlayersOrBuilder(
          int index) {
        if (playersBuilder_ == null) {
          return players_.get(index);  } else {
          return playersBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentDataOrBuilder> 
           getPlayersOrBuilderList() {
        if (playersBuilder_ != null) {
          return playersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(players_);
        }
      }
      public com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData.Builder addPlayersBuilder() {
        return getPlayersFieldBuilder().addBuilder(
            com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData.getDefaultInstance());
      }
      public com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData.Builder addPlayersBuilder(
          int index) {
        return getPlayersFieldBuilder().addBuilder(
            index, com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData.getDefaultInstance());
      }
      public java.util.List<com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData.Builder> 
           getPlayersBuilderList() {
        return getPlayersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData, com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData.Builder, com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentDataOrBuilder> 
          getPlayersFieldBuilder() {
        if (playersBuilder_ == null) {
          playersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData, com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData.Builder, com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentDataOrBuilder>(
                  players_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          players_ = null;
        }
        return playersBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.ftkj.proto.TeamInvestmentMainData)
    }
    
    static {
      defaultInstance = new TeamInvestmentMainData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ftkj.proto.TeamInvestmentMainData)
  }
  
  public interface TeamInvestmentInfoDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 maxTotal = 1;
    boolean hasMaxTotal();
    int getMaxTotal();
    
    // required int32 money = 2;
    boolean hasMoney();
    int getMoney();
    
    // optional int32 buyCount = 3;
    boolean hasBuyCount();
    int getBuyCount();
  }
  public static final class TeamInvestmentInfoData extends
      com.google.protobuf.GeneratedMessage
      implements TeamInvestmentInfoDataOrBuilder {
    // Use TeamInvestmentInfoData.newBuilder() to construct.
    private TeamInvestmentInfoData(Builder builder) {
      super(builder);
    }
    private TeamInvestmentInfoData(boolean noInit) {}
    
    private static final TeamInvestmentInfoData defaultInstance;
    public static TeamInvestmentInfoData getDefaultInstance() {
      return defaultInstance;
    }
    
    public TeamInvestmentInfoData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ftkj.proto.PlayerInvestmentPB.internal_static_com_ftkj_proto_TeamInvestmentInfoData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ftkj.proto.PlayerInvestmentPB.internal_static_com_ftkj_proto_TeamInvestmentInfoData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 maxTotal = 1;
    public static final int MAXTOTAL_FIELD_NUMBER = 1;
    private int maxTotal_;
    public boolean hasMaxTotal() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getMaxTotal() {
      return maxTotal_;
    }
    
    // required int32 money = 2;
    public static final int MONEY_FIELD_NUMBER = 2;
    private int money_;
    public boolean hasMoney() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getMoney() {
      return money_;
    }
    
    // optional int32 buyCount = 3;
    public static final int BUYCOUNT_FIELD_NUMBER = 3;
    private int buyCount_;
    public boolean hasBuyCount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getBuyCount() {
      return buyCount_;
    }
    
    private void initFields() {
      maxTotal_ = 0;
      money_ = 0;
      buyCount_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMaxTotal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMoney()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, maxTotal_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, money_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, buyCount_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, maxTotal_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, money_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, buyCount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ftkj.proto.PlayerInvestmentPB.internal_static_com_ftkj_proto_TeamInvestmentInfoData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ftkj.proto.PlayerInvestmentPB.internal_static_com_ftkj_proto_TeamInvestmentInfoData_fieldAccessorTable;
      }
      
      // Construct using com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        maxTotal_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        money_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        buyCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData.getDescriptor();
      }
      
      public com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData getDefaultInstanceForType() {
        return com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData.getDefaultInstance();
      }
      
      public com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData build() {
        com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData buildPartial() {
        com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData result = new com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.maxTotal_ = maxTotal_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.money_ = money_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.buyCount_ = buyCount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData) {
          return mergeFrom((com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData other) {
        if (other == com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData.getDefaultInstance()) return this;
        if (other.hasMaxTotal()) {
          setMaxTotal(other.getMaxTotal());
        }
        if (other.hasMoney()) {
          setMoney(other.getMoney());
        }
        if (other.hasBuyCount()) {
          setBuyCount(other.getBuyCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMaxTotal()) {
          
          return false;
        }
        if (!hasMoney()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              maxTotal_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              money_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              buyCount_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 maxTotal = 1;
      private int maxTotal_ ;
      public boolean hasMaxTotal() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getMaxTotal() {
        return maxTotal_;
      }
      public Builder setMaxTotal(int value) {
        bitField0_ |= 0x00000001;
        maxTotal_ = value;
        onChanged();
        return this;
      }
      public Builder clearMaxTotal() {
        bitField0_ = (bitField0_ & ~0x00000001);
        maxTotal_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 money = 2;
      private int money_ ;
      public boolean hasMoney() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getMoney() {
        return money_;
      }
      public Builder setMoney(int value) {
        bitField0_ |= 0x00000002;
        money_ = value;
        onChanged();
        return this;
      }
      public Builder clearMoney() {
        bitField0_ = (bitField0_ & ~0x00000002);
        money_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 buyCount = 3;
      private int buyCount_ ;
      public boolean hasBuyCount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getBuyCount() {
        return buyCount_;
      }
      public Builder setBuyCount(int value) {
        bitField0_ |= 0x00000004;
        buyCount_ = value;
        onChanged();
        return this;
      }
      public Builder clearBuyCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        buyCount_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.ftkj.proto.TeamInvestmentInfoData)
    }
    
    static {
      defaultInstance = new TeamInvestmentInfoData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ftkj.proto.TeamInvestmentInfoData)
  }
  
  public interface TeamPlayerInvestmentDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 playerId = 1;
    boolean hasPlayerId();
    int getPlayerId();
    
    // required int32 total = 2;
    boolean hasTotal();
    int getTotal();
    
    // required float basePrice = 3;
    boolean hasBasePrice();
    float getBasePrice();
    
    // required int32 buyDay = 4;
    boolean hasBuyDay();
    int getBuyDay();
  }
  public static final class TeamPlayerInvestmentData extends
      com.google.protobuf.GeneratedMessage
      implements TeamPlayerInvestmentDataOrBuilder {
    // Use TeamPlayerInvestmentData.newBuilder() to construct.
    private TeamPlayerInvestmentData(Builder builder) {
      super(builder);
    }
    private TeamPlayerInvestmentData(boolean noInit) {}
    
    private static final TeamPlayerInvestmentData defaultInstance;
    public static TeamPlayerInvestmentData getDefaultInstance() {
      return defaultInstance;
    }
    
    public TeamPlayerInvestmentData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ftkj.proto.PlayerInvestmentPB.internal_static_com_ftkj_proto_TeamPlayerInvestmentData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ftkj.proto.PlayerInvestmentPB.internal_static_com_ftkj_proto_TeamPlayerInvestmentData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 playerId = 1;
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private int playerId_;
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getPlayerId() {
      return playerId_;
    }
    
    // required int32 total = 2;
    public static final int TOTAL_FIELD_NUMBER = 2;
    private int total_;
    public boolean hasTotal() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getTotal() {
      return total_;
    }
    
    // required float basePrice = 3;
    public static final int BASEPRICE_FIELD_NUMBER = 3;
    private float basePrice_;
    public boolean hasBasePrice() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public float getBasePrice() {
      return basePrice_;
    }
    
    // required int32 buyDay = 4;
    public static final int BUYDAY_FIELD_NUMBER = 4;
    private int buyDay_;
    public boolean hasBuyDay() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getBuyDay() {
      return buyDay_;
    }
    
    private void initFields() {
      playerId_ = 0;
      total_ = 0;
      basePrice_ = 0F;
      buyDay_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTotal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBasePrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBuyDay()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, total_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, basePrice_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, buyDay_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, total_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, basePrice_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, buyDay_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ftkj.proto.PlayerInvestmentPB.internal_static_com_ftkj_proto_TeamPlayerInvestmentData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ftkj.proto.PlayerInvestmentPB.internal_static_com_ftkj_proto_TeamPlayerInvestmentData_fieldAccessorTable;
      }
      
      // Construct using com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        playerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        total_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        basePrice_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        buyDay_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData.getDescriptor();
      }
      
      public com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData getDefaultInstanceForType() {
        return com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData.getDefaultInstance();
      }
      
      public com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData build() {
        com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData buildPartial() {
        com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData result = new com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.total_ = total_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.basePrice_ = basePrice_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.buyDay_ = buyDay_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData) {
          return mergeFrom((com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData other) {
        if (other == com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasTotal()) {
          setTotal(other.getTotal());
        }
        if (other.hasBasePrice()) {
          setBasePrice(other.getBasePrice());
        }
        if (other.hasBuyDay()) {
          setBuyDay(other.getBuyDay());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPlayerId()) {
          
          return false;
        }
        if (!hasTotal()) {
          
          return false;
        }
        if (!hasBasePrice()) {
          
          return false;
        }
        if (!hasBuyDay()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              total_ = input.readInt32();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              basePrice_ = input.readFloat();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              buyDay_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 playerId = 1;
      private int playerId_ ;
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getPlayerId() {
        return playerId_;
      }
      public Builder setPlayerId(int value) {
        bitField0_ |= 0x00000001;
        playerId_ = value;
        onChanged();
        return this;
      }
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 total = 2;
      private int total_ ;
      public boolean hasTotal() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getTotal() {
        return total_;
      }
      public Builder setTotal(int value) {
        bitField0_ |= 0x00000002;
        total_ = value;
        onChanged();
        return this;
      }
      public Builder clearTotal() {
        bitField0_ = (bitField0_ & ~0x00000002);
        total_ = 0;
        onChanged();
        return this;
      }
      
      // required float basePrice = 3;
      private float basePrice_ ;
      public boolean hasBasePrice() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public float getBasePrice() {
        return basePrice_;
      }
      public Builder setBasePrice(float value) {
        bitField0_ |= 0x00000004;
        basePrice_ = value;
        onChanged();
        return this;
      }
      public Builder clearBasePrice() {
        bitField0_ = (bitField0_ & ~0x00000004);
        basePrice_ = 0F;
        onChanged();
        return this;
      }
      
      // required int32 buyDay = 4;
      private int buyDay_ ;
      public boolean hasBuyDay() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getBuyDay() {
        return buyDay_;
      }
      public Builder setBuyDay(int value) {
        bitField0_ |= 0x00000008;
        buyDay_ = value;
        onChanged();
        return this;
      }
      public Builder clearBuyDay() {
        bitField0_ = (bitField0_ & ~0x00000008);
        buyDay_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.ftkj.proto.TeamPlayerInvestmentData)
    }
    
    static {
      defaultInstance = new TeamPlayerInvestmentData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ftkj.proto.TeamPlayerInvestmentData)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ftkj_proto_TeamInvestmentMainData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ftkj_proto_TeamInvestmentMainData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ftkj_proto_TeamInvestmentInfoData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ftkj_proto_TeamInvestmentInfoData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ftkj_proto_TeamPlayerInvestmentData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ftkj_proto_TeamPlayerInvestmentData_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026PlayerInvestment.proto\022\016com.ftkj.proto" +
      "\"\215\001\n\026TeamInvestmentMainData\0228\n\010teamInfo\030" +
      "\001 \002(\0132&.com.ftkj.proto.TeamInvestmentInf" +
      "oData\0229\n\007players\030\002 \003(\0132(.com.ftkj.proto." +
      "TeamPlayerInvestmentData\"K\n\026TeamInvestme" +
      "ntInfoData\022\020\n\010maxTotal\030\001 \002(\005\022\r\n\005money\030\002 " +
      "\002(\005\022\020\n\010buyCount\030\003 \001(\005\"^\n\030TeamPlayerInves" +
      "tmentData\022\020\n\010playerId\030\001 \002(\005\022\r\n\005total\030\002 \002" +
      "(\005\022\021\n\tbasePrice\030\003 \002(\002\022\016\n\006buyDay\030\004 \002(\005B\024B" +
      "\022PlayerInvestmentPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_ftkj_proto_TeamInvestmentMainData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_ftkj_proto_TeamInvestmentMainData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ftkj_proto_TeamInvestmentMainData_descriptor,
              new java.lang.String[] { "TeamInfo", "Players", },
              com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData.class,
              com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentMainData.Builder.class);
          internal_static_com_ftkj_proto_TeamInvestmentInfoData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_ftkj_proto_TeamInvestmentInfoData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ftkj_proto_TeamInvestmentInfoData_descriptor,
              new java.lang.String[] { "MaxTotal", "Money", "BuyCount", },
              com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData.class,
              com.ftkj.proto.PlayerInvestmentPB.TeamInvestmentInfoData.Builder.class);
          internal_static_com_ftkj_proto_TeamPlayerInvestmentData_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_ftkj_proto_TeamPlayerInvestmentData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ftkj_proto_TeamPlayerInvestmentData_descriptor,
              new java.lang.String[] { "PlayerId", "Total", "BasePrice", "BuyDay", },
              com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData.class,
              com.ftkj.proto.PlayerInvestmentPB.TeamPlayerInvestmentData.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
