// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tactics.proto

package com.ftkj.proto;

public final class TacticsPB {
  private TacticsPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TeamTacticsDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 defJg = 1;
    boolean hasDefJg();
    int getDefJg();
    
    // required int32 defFs = 2;
    boolean hasDefFs();
    int getDefFs();
    
    // repeated .com.ftkj.proto.TacticsData tacticsList = 3;
    java.util.List<com.ftkj.proto.TacticsPB.TacticsData> 
        getTacticsListList();
    com.ftkj.proto.TacticsPB.TacticsData getTacticsList(int index);
    int getTacticsListCount();
    java.util.List<? extends com.ftkj.proto.TacticsPB.TacticsDataOrBuilder> 
        getTacticsListOrBuilderList();
    com.ftkj.proto.TacticsPB.TacticsDataOrBuilder getTacticsListOrBuilder(
        int index);
  }
  public static final class TeamTacticsData extends
      com.google.protobuf.GeneratedMessage
      implements TeamTacticsDataOrBuilder {
    // Use TeamTacticsData.newBuilder() to construct.
    private TeamTacticsData(Builder builder) {
      super(builder);
    }
    private TeamTacticsData(boolean noInit) {}
    
    private static final TeamTacticsData defaultInstance;
    public static TeamTacticsData getDefaultInstance() {
      return defaultInstance;
    }
    
    public TeamTacticsData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ftkj.proto.TacticsPB.internal_static_com_ftkj_proto_TeamTacticsData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ftkj.proto.TacticsPB.internal_static_com_ftkj_proto_TeamTacticsData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 defJg = 1;
    public static final int DEFJG_FIELD_NUMBER = 1;
    private int defJg_;
    public boolean hasDefJg() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getDefJg() {
      return defJg_;
    }
    
    // required int32 defFs = 2;
    public static final int DEFFS_FIELD_NUMBER = 2;
    private int defFs_;
    public boolean hasDefFs() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getDefFs() {
      return defFs_;
    }
    
    // repeated .com.ftkj.proto.TacticsData tacticsList = 3;
    public static final int TACTICSLIST_FIELD_NUMBER = 3;
    private java.util.List<com.ftkj.proto.TacticsPB.TacticsData> tacticsList_;
    public java.util.List<com.ftkj.proto.TacticsPB.TacticsData> getTacticsListList() {
      return tacticsList_;
    }
    public java.util.List<? extends com.ftkj.proto.TacticsPB.TacticsDataOrBuilder> 
        getTacticsListOrBuilderList() {
      return tacticsList_;
    }
    public int getTacticsListCount() {
      return tacticsList_.size();
    }
    public com.ftkj.proto.TacticsPB.TacticsData getTacticsList(int index) {
      return tacticsList_.get(index);
    }
    public com.ftkj.proto.TacticsPB.TacticsDataOrBuilder getTacticsListOrBuilder(
        int index) {
      return tacticsList_.get(index);
    }
    
    private void initFields() {
      defJg_ = 0;
      defFs_ = 0;
      tacticsList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasDefJg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDefFs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getTacticsListCount(); i++) {
        if (!getTacticsList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, defJg_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, defFs_);
      }
      for (int i = 0; i < tacticsList_.size(); i++) {
        output.writeMessage(3, tacticsList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, defJg_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, defFs_);
      }
      for (int i = 0; i < tacticsList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, tacticsList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.ftkj.proto.TacticsPB.TeamTacticsData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.TacticsPB.TeamTacticsData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.TacticsPB.TeamTacticsData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.TacticsPB.TeamTacticsData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.TacticsPB.TeamTacticsData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.TacticsPB.TeamTacticsData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.TacticsPB.TeamTacticsData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.TacticsPB.TeamTacticsData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.TacticsPB.TeamTacticsData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.TacticsPB.TeamTacticsData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ftkj.proto.TacticsPB.TeamTacticsData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ftkj.proto.TacticsPB.TeamTacticsDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ftkj.proto.TacticsPB.internal_static_com_ftkj_proto_TeamTacticsData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ftkj.proto.TacticsPB.internal_static_com_ftkj_proto_TeamTacticsData_fieldAccessorTable;
      }
      
      // Construct using com.ftkj.proto.TacticsPB.TeamTacticsData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTacticsListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        defJg_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        defFs_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (tacticsListBuilder_ == null) {
          tacticsList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          tacticsListBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ftkj.proto.TacticsPB.TeamTacticsData.getDescriptor();
      }
      
      public com.ftkj.proto.TacticsPB.TeamTacticsData getDefaultInstanceForType() {
        return com.ftkj.proto.TacticsPB.TeamTacticsData.getDefaultInstance();
      }
      
      public com.ftkj.proto.TacticsPB.TeamTacticsData build() {
        com.ftkj.proto.TacticsPB.TeamTacticsData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.ftkj.proto.TacticsPB.TeamTacticsData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.ftkj.proto.TacticsPB.TeamTacticsData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.ftkj.proto.TacticsPB.TeamTacticsData buildPartial() {
        com.ftkj.proto.TacticsPB.TeamTacticsData result = new com.ftkj.proto.TacticsPB.TeamTacticsData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.defJg_ = defJg_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.defFs_ = defFs_;
        if (tacticsListBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            tacticsList_ = java.util.Collections.unmodifiableList(tacticsList_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.tacticsList_ = tacticsList_;
        } else {
          result.tacticsList_ = tacticsListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ftkj.proto.TacticsPB.TeamTacticsData) {
          return mergeFrom((com.ftkj.proto.TacticsPB.TeamTacticsData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.ftkj.proto.TacticsPB.TeamTacticsData other) {
        if (other == com.ftkj.proto.TacticsPB.TeamTacticsData.getDefaultInstance()) return this;
        if (other.hasDefJg()) {
          setDefJg(other.getDefJg());
        }
        if (other.hasDefFs()) {
          setDefFs(other.getDefFs());
        }
        if (tacticsListBuilder_ == null) {
          if (!other.tacticsList_.isEmpty()) {
            if (tacticsList_.isEmpty()) {
              tacticsList_ = other.tacticsList_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureTacticsListIsMutable();
              tacticsList_.addAll(other.tacticsList_);
            }
            onChanged();
          }
        } else {
          if (!other.tacticsList_.isEmpty()) {
            if (tacticsListBuilder_.isEmpty()) {
              tacticsListBuilder_.dispose();
              tacticsListBuilder_ = null;
              tacticsList_ = other.tacticsList_;
              bitField0_ = (bitField0_ & ~0x00000004);
              tacticsListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTacticsListFieldBuilder() : null;
            } else {
              tacticsListBuilder_.addAllMessages(other.tacticsList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasDefJg()) {
          
          return false;
        }
        if (!hasDefFs()) {
          
          return false;
        }
        for (int i = 0; i < getTacticsListCount(); i++) {
          if (!getTacticsList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              defJg_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              defFs_ = input.readInt32();
              break;
            }
            case 26: {
              com.ftkj.proto.TacticsPB.TacticsData.Builder subBuilder = com.ftkj.proto.TacticsPB.TacticsData.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addTacticsList(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 defJg = 1;
      private int defJg_ ;
      public boolean hasDefJg() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getDefJg() {
        return defJg_;
      }
      public Builder setDefJg(int value) {
        bitField0_ |= 0x00000001;
        defJg_ = value;
        onChanged();
        return this;
      }
      public Builder clearDefJg() {
        bitField0_ = (bitField0_ & ~0x00000001);
        defJg_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 defFs = 2;
      private int defFs_ ;
      public boolean hasDefFs() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getDefFs() {
        return defFs_;
      }
      public Builder setDefFs(int value) {
        bitField0_ |= 0x00000002;
        defFs_ = value;
        onChanged();
        return this;
      }
      public Builder clearDefFs() {
        bitField0_ = (bitField0_ & ~0x00000002);
        defFs_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .com.ftkj.proto.TacticsData tacticsList = 3;
      private java.util.List<com.ftkj.proto.TacticsPB.TacticsData> tacticsList_ =
        java.util.Collections.emptyList();
      private void ensureTacticsListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          tacticsList_ = new java.util.ArrayList<com.ftkj.proto.TacticsPB.TacticsData>(tacticsList_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ftkj.proto.TacticsPB.TacticsData, com.ftkj.proto.TacticsPB.TacticsData.Builder, com.ftkj.proto.TacticsPB.TacticsDataOrBuilder> tacticsListBuilder_;
      
      public java.util.List<com.ftkj.proto.TacticsPB.TacticsData> getTacticsListList() {
        if (tacticsListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tacticsList_);
        } else {
          return tacticsListBuilder_.getMessageList();
        }
      }
      public int getTacticsListCount() {
        if (tacticsListBuilder_ == null) {
          return tacticsList_.size();
        } else {
          return tacticsListBuilder_.getCount();
        }
      }
      public com.ftkj.proto.TacticsPB.TacticsData getTacticsList(int index) {
        if (tacticsListBuilder_ == null) {
          return tacticsList_.get(index);
        } else {
          return tacticsListBuilder_.getMessage(index);
        }
      }
      public Builder setTacticsList(
          int index, com.ftkj.proto.TacticsPB.TacticsData value) {
        if (tacticsListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTacticsListIsMutable();
          tacticsList_.set(index, value);
          onChanged();
        } else {
          tacticsListBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setTacticsList(
          int index, com.ftkj.proto.TacticsPB.TacticsData.Builder builderForValue) {
        if (tacticsListBuilder_ == null) {
          ensureTacticsListIsMutable();
          tacticsList_.set(index, builderForValue.build());
          onChanged();
        } else {
          tacticsListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addTacticsList(com.ftkj.proto.TacticsPB.TacticsData value) {
        if (tacticsListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTacticsListIsMutable();
          tacticsList_.add(value);
          onChanged();
        } else {
          tacticsListBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addTacticsList(
          int index, com.ftkj.proto.TacticsPB.TacticsData value) {
        if (tacticsListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTacticsListIsMutable();
          tacticsList_.add(index, value);
          onChanged();
        } else {
          tacticsListBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addTacticsList(
          com.ftkj.proto.TacticsPB.TacticsData.Builder builderForValue) {
        if (tacticsListBuilder_ == null) {
          ensureTacticsListIsMutable();
          tacticsList_.add(builderForValue.build());
          onChanged();
        } else {
          tacticsListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addTacticsList(
          int index, com.ftkj.proto.TacticsPB.TacticsData.Builder builderForValue) {
        if (tacticsListBuilder_ == null) {
          ensureTacticsListIsMutable();
          tacticsList_.add(index, builderForValue.build());
          onChanged();
        } else {
          tacticsListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllTacticsList(
          java.lang.Iterable<? extends com.ftkj.proto.TacticsPB.TacticsData> values) {
        if (tacticsListBuilder_ == null) {
          ensureTacticsListIsMutable();
          super.addAll(values, tacticsList_);
          onChanged();
        } else {
          tacticsListBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearTacticsList() {
        if (tacticsListBuilder_ == null) {
          tacticsList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          tacticsListBuilder_.clear();
        }
        return this;
      }
      public Builder removeTacticsList(int index) {
        if (tacticsListBuilder_ == null) {
          ensureTacticsListIsMutable();
          tacticsList_.remove(index);
          onChanged();
        } else {
          tacticsListBuilder_.remove(index);
        }
        return this;
      }
      public com.ftkj.proto.TacticsPB.TacticsData.Builder getTacticsListBuilder(
          int index) {
        return getTacticsListFieldBuilder().getBuilder(index);
      }
      public com.ftkj.proto.TacticsPB.TacticsDataOrBuilder getTacticsListOrBuilder(
          int index) {
        if (tacticsListBuilder_ == null) {
          return tacticsList_.get(index);  } else {
          return tacticsListBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.ftkj.proto.TacticsPB.TacticsDataOrBuilder> 
           getTacticsListOrBuilderList() {
        if (tacticsListBuilder_ != null) {
          return tacticsListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tacticsList_);
        }
      }
      public com.ftkj.proto.TacticsPB.TacticsData.Builder addTacticsListBuilder() {
        return getTacticsListFieldBuilder().addBuilder(
            com.ftkj.proto.TacticsPB.TacticsData.getDefaultInstance());
      }
      public com.ftkj.proto.TacticsPB.TacticsData.Builder addTacticsListBuilder(
          int index) {
        return getTacticsListFieldBuilder().addBuilder(
            index, com.ftkj.proto.TacticsPB.TacticsData.getDefaultInstance());
      }
      public java.util.List<com.ftkj.proto.TacticsPB.TacticsData.Builder> 
           getTacticsListBuilderList() {
        return getTacticsListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ftkj.proto.TacticsPB.TacticsData, com.ftkj.proto.TacticsPB.TacticsData.Builder, com.ftkj.proto.TacticsPB.TacticsDataOrBuilder> 
          getTacticsListFieldBuilder() {
        if (tacticsListBuilder_ == null) {
          tacticsListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.ftkj.proto.TacticsPB.TacticsData, com.ftkj.proto.TacticsPB.TacticsData.Builder, com.ftkj.proto.TacticsPB.TacticsDataOrBuilder>(
                  tacticsList_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          tacticsList_ = null;
        }
        return tacticsListBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.ftkj.proto.TeamTacticsData)
    }
    
    static {
      defaultInstance = new TeamTacticsData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ftkj.proto.TeamTacticsData)
  }
  
  public interface TacticsDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
    
    // required int32 lv = 2;
    boolean hasLv();
    int getLv();
    
    // required int64 buffTime = 3;
    boolean hasBuffTime();
    long getBuffTime();
  }
  public static final class TacticsData extends
      com.google.protobuf.GeneratedMessage
      implements TacticsDataOrBuilder {
    // Use TacticsData.newBuilder() to construct.
    private TacticsData(Builder builder) {
      super(builder);
    }
    private TacticsData(boolean noInit) {}
    
    private static final TacticsData defaultInstance;
    public static TacticsData getDefaultInstance() {
      return defaultInstance;
    }
    
    public TacticsData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ftkj.proto.TacticsPB.internal_static_com_ftkj_proto_TacticsData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ftkj.proto.TacticsPB.internal_static_com_ftkj_proto_TacticsData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // required int32 lv = 2;
    public static final int LV_FIELD_NUMBER = 2;
    private int lv_;
    public boolean hasLv() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getLv() {
      return lv_;
    }
    
    // required int64 buffTime = 3;
    public static final int BUFFTIME_FIELD_NUMBER = 3;
    private long buffTime_;
    public boolean hasBuffTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getBuffTime() {
      return buffTime_;
    }
    
    private void initFields() {
      id_ = 0;
      lv_ = 0;
      buffTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLv()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBuffTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, lv_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, buffTime_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, lv_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, buffTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.ftkj.proto.TacticsPB.TacticsData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.TacticsPB.TacticsData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.TacticsPB.TacticsData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ftkj.proto.TacticsPB.TacticsData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.TacticsPB.TacticsData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.TacticsPB.TacticsData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.ftkj.proto.TacticsPB.TacticsData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.TacticsPB.TacticsData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ftkj.proto.TacticsPB.TacticsData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ftkj.proto.TacticsPB.TacticsData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ftkj.proto.TacticsPB.TacticsData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ftkj.proto.TacticsPB.TacticsDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ftkj.proto.TacticsPB.internal_static_com_ftkj_proto_TacticsData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ftkj.proto.TacticsPB.internal_static_com_ftkj_proto_TacticsData_fieldAccessorTable;
      }
      
      // Construct using com.ftkj.proto.TacticsPB.TacticsData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        lv_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        buffTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ftkj.proto.TacticsPB.TacticsData.getDescriptor();
      }
      
      public com.ftkj.proto.TacticsPB.TacticsData getDefaultInstanceForType() {
        return com.ftkj.proto.TacticsPB.TacticsData.getDefaultInstance();
      }
      
      public com.ftkj.proto.TacticsPB.TacticsData build() {
        com.ftkj.proto.TacticsPB.TacticsData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.ftkj.proto.TacticsPB.TacticsData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.ftkj.proto.TacticsPB.TacticsData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.ftkj.proto.TacticsPB.TacticsData buildPartial() {
        com.ftkj.proto.TacticsPB.TacticsData result = new com.ftkj.proto.TacticsPB.TacticsData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lv_ = lv_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.buffTime_ = buffTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ftkj.proto.TacticsPB.TacticsData) {
          return mergeFrom((com.ftkj.proto.TacticsPB.TacticsData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.ftkj.proto.TacticsPB.TacticsData other) {
        if (other == com.ftkj.proto.TacticsPB.TacticsData.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasLv()) {
          setLv(other.getLv());
        }
        if (other.hasBuffTime()) {
          setBuffTime(other.getBuffTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasLv()) {
          
          return false;
        }
        if (!hasBuffTime()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              lv_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              buffTime_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 lv = 2;
      private int lv_ ;
      public boolean hasLv() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getLv() {
        return lv_;
      }
      public Builder setLv(int value) {
        bitField0_ |= 0x00000002;
        lv_ = value;
        onChanged();
        return this;
      }
      public Builder clearLv() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lv_ = 0;
        onChanged();
        return this;
      }
      
      // required int64 buffTime = 3;
      private long buffTime_ ;
      public boolean hasBuffTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getBuffTime() {
        return buffTime_;
      }
      public Builder setBuffTime(long value) {
        bitField0_ |= 0x00000004;
        buffTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearBuffTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        buffTime_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.ftkj.proto.TacticsData)
    }
    
    static {
      defaultInstance = new TacticsData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ftkj.proto.TacticsData)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ftkj_proto_TeamTacticsData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ftkj_proto_TeamTacticsData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ftkj_proto_TacticsData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ftkj_proto_TacticsData_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rTactics.proto\022\016com.ftkj.proto\"a\n\017TeamT" +
      "acticsData\022\r\n\005defJg\030\001 \002(\005\022\r\n\005defFs\030\002 \002(\005" +
      "\0220\n\013tacticsList\030\003 \003(\0132\033.com.ftkj.proto.T" +
      "acticsData\"7\n\013TacticsData\022\n\n\002id\030\001 \002(\005\022\n\n" +
      "\002lv\030\002 \002(\005\022\020\n\010buffTime\030\003 \002(\003B\013B\tTacticsPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_ftkj_proto_TeamTacticsData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_ftkj_proto_TeamTacticsData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ftkj_proto_TeamTacticsData_descriptor,
              new java.lang.String[] { "DefJg", "DefFs", "TacticsList", },
              com.ftkj.proto.TacticsPB.TeamTacticsData.class,
              com.ftkj.proto.TacticsPB.TeamTacticsData.Builder.class);
          internal_static_com_ftkj_proto_TacticsData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_ftkj_proto_TacticsData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ftkj_proto_TacticsData_descriptor,
              new java.lang.String[] { "Id", "Lv", "BuffTime", },
              com.ftkj.proto.TacticsPB.TacticsData.class,
              com.ftkj.proto.TacticsPB.TacticsData.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
